### ISSUE TITLE
Rename test

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#100]
## Description

The name of this test implies charges should be assigned. Rename it to something like: 'test it does not assign charges'

### Background information
This test used to checked for assignments, but it was later found to be impractical to assign the charges to the case at the record level parser. It was later tweaked to assign charges to a case at the case level parser.

### This task is done when:

- [ ] This test https://github.com/CodeForPortland/recordexpungPDX/blob/master/src/backend/tests/parser/test_record_parser.py#L62 is named more appropriately.

**Comment by wittejm** [comment]
completed with #781 . thanks @m-murasovs !
