### ISSUE TITLE
Assign balance due to case object

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#101]
## Description
Currently the balance due is being parsed by the `case_parser`, and is assigned to the case parser object here: https://github.com/CodeForPortland/recordexpungPDX/blob/master/src/backend/expungeservice/crawler/parsers/case_parser/case_parser.py#L20, however that information is lost as it's not being assigned to the case object by the crawler.

### This task is done when:

- [ ] Create a test for assigning the `balance_due` attribute to the case object.
- [ ] Add `balance_due` as an attribute of the Case object.
- [ ] Implement the balance_due assignment.

#### Additional information:
- The test can be added to `test_crawler.py` file here: https://github.com/CodeForPortland/recordexpungPDX/blob/master/src/backend/tests/crawler/test_crawler.py#L71 : currently here at line 71 it is parsing the `CASEJD1` file, however that file has a balance due of $0.  Add test to this test method that checks it assigns `0.00` balance due, and create a new test method that parses the case `CASE_X1`. Case X1 has a balance due of $1,516.80 as shown here: https://github.com/CodeForPortland/recordexpungPDX/blob/master/src/backend/tests/fixtures/case_details.py#L70 It is important to test that it assigns a non-zero value as the default value is zero.
- Once the test is built the attribute can be added in the `Case` class here: https://github.com/CodeForPortland/recordexpungPDX/blob/master/src/backend/expungeservice/crawler/models/case.py#L14
- Assignment can be done after parsing the case file here: https://github.com/CodeForPortland/recordexpungPDX/blob/master/src/backend/expungeservice/crawler/crawler.py#L36

**Comment by wittejm** [comment]
I'd suggest we only add a new test method to check all case balances rather than add one of them into an existing test case that checks for convictions. I guess that means redundantly calling the requests_mocker for that case file, but it seems nice to keep test methods distinct from each other .

**Comment by NickSchimek** [comment]
Yes, that would be perfect, and would be the best way to go!

**Comment by NickSchimek** [comment]
Thanks for looking into this @wittejm
