### ISSUE TITLE
need "recordsponge" docker hub organization owner IDs

### ISSUE THREAD

**Issue by kenichi** [codeforpdx/recordexpungPDX#1026]
New devops are based on using the "recordsponge" docker hub organization, and deploying requires a login with a user that is an owner of that organization.

### This task is done when:

- docker hub IDs for deploy users are supplied to @kenichi 
- @kenichi has added those IDs as owners to the org

**Comment by kenichi** [comment]
n.b. general use of the dev image does NOT require a docker hub login/ID

**Comment by wittejm** [comment]
my docker hub account appears to be busted and requiring customer support but I'll send my ID when it's either working or replaced. Also @KentShikama should have access at least.

**Comment by kenichi** [comment]
added @KentShikama this morning, will leave issue open until we get yours in @wittejm - thanks

**Comment by wittejm** [comment]
Ok, I made a new handle rather than keep waiting for customer support, my ID is **witte**

**Comment by kenichi** [comment]
alright, thanks - you're added as an owner now, i'll close the issue
