### ISSUE TITLE
Add Manual

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#1042]
We have a manual to document how to use RecordSponge and how to file for expungement in a [Google Doc](https://docs.google.com/document/d/1Su078uVl_tg0TuvyAUGr8n2IBQolhWl0H3rN1LUFRNI/edit). We want to take the information in the Google Doc and put it on our website & app. Unauthenticated users will also have access to it.

### This task is done when:
 - A page is created on recordsponge.com with the Manual content that can be accessed when you are logged in or not

![Screen_Shot_2020-04-15_at_8_14_00_PM](https://user-images.githubusercontent.com/6887982/79403871-c1e24280-7f55-11ea-81d4-c3889eea4b4a.png)
----
![Screen_Shot_2020-04-15_at_8_11_09_PM](https://user-images.githubusercontent.com/6887982/79403875-c4449c80-7f55-11ea-8701-99c35f79f9f1.png)

**Comment by hmarcks** [comment]
I'm currently making some edits to the content and creating the HTML. See progress here - feedback welcome: https://codepen.io/hmarcks/full/oNjgmZV

I'll need help with actually creating the view in React.

**Comment by wittejm** [comment]
completed with #1047
