### ISSUE TITLE
Mark an Unclassified charge as "needs more analysis"

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#1051]
An unclassified charge can have an undetermined impact on eligibility of all other charges, depending on whether the charge is blocking. 
We're getting close to having zero known unclassified charges. We're also planning a feature to manually edit the charge type along with other charge info. For all these reasons, we should alert the user to any unclassified charges in the results.   

### This task is done when:
 - Error behavior for an unclassified charge matches the behavior of an unrecognized disposition

**Comment by wittejm** [comment]
Once the app supports manually changing the charge type, we can refer to this occurrence as a "case requiring additional information" and not an error, so we can complete this feature after #1079

**Comment by KentShikama** [comment]
@wittejm This should now be ready right?

**Comment by wittejm** [comment]
Yep

**Comment by KentShikama** [comment]
We should ensure that an error banner shows at the top.
