### ISSUE TITLE
Feature: Create & Edit Cases & Charges

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#1079]
Placeholder for the feature to add and edit cases and charges.

### This task is done when:
 - Many things

**Comment by hmarcks** [comment]
Here's a first draft of the UI to continue our conversation:

![add-case-and-charge](https://user-images.githubusercontent.com/6887982/80750469-c2e6a880-8aed-11ea-9c9e-6d264b2baf74.png)

**Comment by wittejm** [comment]
Sweet!

**Comment by hmarcks** [comment]
Some more thoughts on how to handle unknown vs unrecognized dispositions when we have this full edit functionality, and how to handle the other clarification questions:

![unknown-vs-unrecognized](https://user-images.githubusercontent.com/6887982/81139136-4d823a00-8f2a-11ea-8cc9-e66ca1da18bc.png)

**Comment by hmarcks** [comment]
UI for undo edits and removing cases / charges. This should finish up the UI design for adding & editing cases & charges.

<img src="https://user-images.githubusercontent.com/6887982/81746062-77c48200-946b-11ea-9a65-d5f113b74dc3.png" height="400">

**Comment by wittejm** [comment]
It just occurred to me that changing the case number is a weird mechanic. We identify the data objects by their case numbers, so when we apply edits we're reconciling a custom case number with a different OECI case number. We would need to retain the real case number and spoof it with the visible case number. Then the user could see the true case number only by undoing their edits to the case. I'm not sure there's actual value to this. But if someone disagrees and thinks some version of this is useful (@michaelzhang43 ?) it's doable. 

But being able to change case numbers of new cases is nice: Making the case number optional means one will get generated like `CASE001` or such. But if you want to rename your custom cases, then that's useful. 

Maybe, if it's an OECI case, display the case number but not in an editable field, or gray out the field?

**Comment by michaelzhang43** [comment]
That sounds good. I agree that we should only allow changes to case number for custom cases. Are there any engineering reasons not to?

**Comment by wittejm** [comment]
Only allowing changes to the case number for custom cases would be easy.

**Comment by michaelzhang43** [comment]
Great, let's go with that then

**Comment by hmarcks** [comment]
Sounds good, I updated the mockup. @wittejm I'll have some HTML for you soon.

**Comment by KentShikama** [comment]
I'm thinking we should just auto-generate the case number for the user if it is a user-generated case.

**Comment by hmarcks** [comment]
The one potential issue I see with that is if the user or @michaelzhang43 wants to enter a real case that is missing and send out the PDF to the client - it's more clear if the actual case number is entered.

But I don't know how legitimate of a scenario this is.

**Comment by michaelzhang43** [comment]
Here's my thinking on this:

It feels like we are adding a lot of new functions and I want to keep the app simple to use and only prompt for user input when necessary. Therefore, auto-generating the case number makes sense, and people can keep track of their real cases with our corresponding case numbers externally. Especially if the case numbers generated were simple, like "1", "2" or "000001", "000002" etc.

**Comment by hmarcks** [comment]
I've updated the three mockups in this issue based on our discussions on Thursday:

Add case & charge • Edit case & charge •  Open case / unrecognized disposition / needs clarification
<img src="https://user-images.githubusercontent.com/6887982/82630155-7e639f80-9bb7-11ea-9284-fc5f4372d40e.png" height="400"><img src="https://user-images.githubusercontent.com/6887982/82630109-61c76780-9bb7-11ea-9e9a-4323763e7389.png" height="400"><img src="https://user-images.githubusercontent.com/6887982/82742205-9c004880-9d20-11ea-9e90-307c40c85f17.png" height="400">

**Comment by wittejm** [comment]
Completed.
