### ISSUE TITLE
Excluding Schedule 3 from Marijuana consideration

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#1096]
Drug Delivery/Manufacturing/Possession offenses for marijuana are subject to different rules than other drug offenses. Non-marijuana offenses follow "normal" rules while marijuana offenses have special rules. We currently can tell that a Delivery/Manufacturing/Possession does not involve marijuana if it says that the name of the charge contains (Schedule) "II" or "2". 

**Similarly, we should parse out chargenames that contain "III" or "3" or "IV" or "4" **

### This task is done when:
 -
 -

**Comment by KentShikama** [comment]
We do exclude Schedule 3/4 from being classified as a MJ offense: https://github.com/codeforpdx/recordexpungPDX/blob/3d0ccc7b8318838cfa373554a9dd7d6385fd3dd9/src/backend/expungeservice/charge_classifier.py#L161-L162. If the charge name contains both "MJ" and "3", then "MJ" takes precedence: https://github.com/codeforpdx/recordexpungPDX/blob/3d0ccc7b8318838cfa373554a9dd7d6385fd3dd9/src/backend/expungeservice/charge_classifier.py#L105-L106

**Comment by wittejm** [comment]
Need to check also for "III" and "IV"
