### ISSUE TITLE
Display Ineligible Charges (instead of ineligible cases) in Summary Panel 

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#1097]
After using the software, I feel that we should switch to displaying ineligible non-traffic violation charges (like we like eligible charges), rather than Ineligible Cases. When we first implemented the feature, I believe our rationale was that it seemed like displaying ineligible cases rather than ineligible charges would be a more optimistic approach. After using the software for a while, I feel that the summary panel would be more informative by listing ineligible charges, and that this benefit outweighs the cost of the 'optimism'

### This task is done when:
 -
 -

**Comment by KentShikama** [comment]
Does https://github.com/codeforpdx/recordexpungPDX/pull/1104#issuecomment-626019574 address this issue?
