### ISSUE TITLE
Attempt to Commit a Class [ ] Felony

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#1100]
Problem: Attempt to Commit a Class [] Felony is treated, for expungement purposes, as the type of crime for the underlying charge. For example, a sex crime that's an Attempt to Commit a Class C Felony is not eligible for expungement. 

Therefore:
If a statute  is 161.405(2)(b) or its chargename is "Attempt to Commit a Class A Felony" then it will charged as a Class B Felony. We should mark these as Further Analysis Needed, and prompt user to answer whether the underlying conduct was for 1) Drug Crime (non-marijuana) 2) Drug Crime (marijuana) or 3) Non-drug crime. If the user selects 3), the charge should be marked as Type-ineligible. 

If a statute  is 161.405(2)(c) or its chargename is "Attempt to Commit a Class B Felony" then it will charged as a Class C Felony. We should mark these as Further Analysis Needed, and prompt user to answer whether the underlying conduct was for 1) Sex Crime or 2) Not a Sex Crime. If the user selects 1), the charge should be marked as Type-ineligible. 

If a statute  is 161.405(2)(d) or its chargename is "Attempt to Commit a Class C Felony" then it will charged as a Class A Misdemeanor. We should mark these as Further Analysis Needed, and prompt user to answer whether the underlying conduct was for 1) Sex Crime or 2) Not a Sex Crime. If the user selects 1), the charge should be marked as Type-ineligible. 

### This task is done when:
 -
 -

**Comment by KentShikama** [comment]
@wittejm Do you know what the status of this issue is?

**Comment by wittejm** [comment]
I'm pretty sure no one ever started this one.

**Comment by KentShikama** [comment]
Proposed tests

```
def test_attempt_to_commit_felony_class_a_charge():
    felony_class_b_convicted = ChargeFactory.create(
        name="Attempt to Commit a Class A Felony",
        statute="161.405(2)(b)",
        level="Felony Class B",
        disposition=Dispositions.CONVICTED,
    )
```

and

```
def test_attempt_to_commit_felony_class_b_charge():
    felony_class_c_convicted = ChargeFactory.create(
        name="Attempt to Commit a Class B Felony",
        statute="161.405(2)(c)",
        level="Felony Class C",
        disposition=Dispositions.CONVICTED,
    )
```

**Comment by KentShikama** [comment]
@michaelzhang43 Please review

Charge: An attempt to commit a class A felony
Question: "Was this a drug-related offense where the underlying substance was marijuana?"
Options: If yes, MarijuanaEligible. If no, PersonFelonyClassB.

Charge: An attempt to commit a class B felony/class C felony
Question: "Was the underlying conduct a sex crime that is not eligible under 137.225(6)(f)?"
Options: If yes, RomeoAndJulietIneligibleSexCrime. If no, classify by level.

**Comment by michaelzhang43** [comment]
For attempt B/C felony, no need to ask if it would qualify under 6(f) - 6(f) only includes misdemeanors. 
So if sex crime - automatically ineligible. If no, then eligible. 

For attempt A felony, if not marijuana, still need to ask if it's non-person Felony B. If it is, then it's eligible under Felony B rules. 

Does that make sense?

**Comment by KentShikama** [comment]
> no need to ask if it would qualify under 6(f) - 6(f) only includes misdemeanors.

Good catch, thanks.

> For attempt A felony, if not marijuana, still need to ask if it's non-person Felony B.

I thought there were no class A felonies that were non-person/non-drug, and the only non-person/non-drug class B felony was aggravated theft.

**Comment by michaelzhang43** [comment]
So if a person has a delivery of heroin charge that was ultimately convicted as 'attempt to commit an A Felony', how would it get resolved?

**Comment by KentShikama** [comment]
Right, it needs to be type eligible as it is a class B felony. Thanks.

**Comment by KentShikama** [comment]
@michaelzhang43 Screenshot of some examples of "Attempt to commit an A Felony". Please review.

![Screen Shot 2020-08-13 at 12 46 44 AM](https://user-images.githubusercontent.com/6329898/90108012-89cdef00-dcfe-11ea-9846-f7faafa9899d.png)

**Comment by KentShikama** [comment]
@michaelzhang43 This is now in https://dev.recordsponge.com/ if you want to review directly.
