### ISSUE TITLE
Unlawful Possession of a Weapon by a Prison Inmate, ORS 166.275

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#1102]
Unlawful Possession of a Weapon by a Prison Inmate, ORS 166.275, is marked as a Felony Unclassified but is punishable by up to 20 years, which is the same as a Class A Felony. We should therefore mark is as a Class A Felony and treat it as such (type-ineligible if convicted)
--

--

### This task is done when:
 -
 -

**Comment by KentShikama** [comment]
What if it is marked as a Felony Class B (person felony)? Do we just assume that the classification is a mistake and overwrite it as Felony Class A?
