### ISSUE TITLE
Add NMA charges to charges summary panel

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#1105]
See https://github.com/codeforpdx/recordexpungPDX/pull/1104#issuecomment-626020172

**Comment by wittejm** [comment]
@michaelzhang43 the needs more analysis charges are already listed (but as case numbers) in the section immediately below the summary:

![nma-sections](https://user-images.githubusercontent.com/2104990/81736084-e513eb00-944a-11ea-82c7-94b5baa2d843.png)

Should we keep both the NMA charges list and the NMA cases block? Or should we basically merge this section into the Summary panel?

A merged version would look something like this:

**Needs more analysis** (2)
*These charges need clarification before an accurate analysis can be determined.*
(?/checkmark) Charge1
(?/checkmark) Charge2

We could make the charges into clickable links, which we should then add to all the charges for consistency. 

@hmarcks  what do you think?

**Comment by hmarcks** [comment]
To me it makes sense to put them in the Summary panel, and once the input is provided, then move them to their respective categories.

**Comment by wittejm** [comment]
Resolved with #1147
