### ISSUE TITLE
Export record summary pdf from the webapp 

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#1138]
This will be a button at the top of the summary panel. The standalone script should still function as normal to allow mass-export from a csv file. 

### This task is done when:
 - migrate the shared code for the two export features into the backend
 - add the frontend button and endpoint functionality that download the generated pdf in-browser
 
Tagging @hmarcks for input on what the export button could look like. I was thinking it could go on the right side of the line saying "Search Summary"

**Comment by KentShikama** [comment]
Going to close as the only remaining part is documented with https://github.com/codeforpdx/recordexpungPDX/issues/1148
