### ISSUE TITLE
Add download icon to pdf download button 

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#1148]
Here's an option:
https://fontawesome.com/v4.7.0/icon/download

Added in as is, it looks a bit crowded: 
![pdf_icon](https://user-images.githubusercontent.com/2104990/82106502-456a8d00-96d6-11ea-97b8-8f4a44f51671.png)

**Comment by KentShikama** [comment]
A related issue is that it takes a noticeable amount of time until the backend returns the PDF. It may be worth changing the status of the button to "loading" when it is clicked.

**Comment by hmarcks** [comment]
If the icon is added (I think it's fine with or without), there should either be a space between PDF and the icon, or a `pl1` class on the icon to give it some room.

For the loading state, you could apply the `loading-btn` class to the button while it's loading.

The css background-color attribute should also be removed from the `.loading-btn` class, not sure why I added that...
