### ISSUE TITLE
Show "No Results found" if and only if there are no charges returned from search

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#1157]
I just noticed that, ever since we added the summary panel, we no longer show the "no results found" message if no results are found and instead show a summary panel with zeros.

![summary_of_no_results](https://user-images.githubusercontent.com/2104990/82367646-020b6980-99c9-11ea-9290-312c54f2f76e.png)

@hmarcks @michaelzhang43 Which one would we rather show here? I think I prefer the message over the panel. 

We also show "No results found" before doing the initial search. We should definitely not be showing it yet.

![no_results_pre_search](https://user-images.githubusercontent.com/2104990/82368256-f9fff980-99c9-11ea-8b8a-8a96b6569422.png)

**Comment by hmarcks** [comment]
Agree on both accounts
