### ISSUE TITLE
Potentially increase contrast for "Possibly Eligible Now"

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#1158]
I have no trouble reading it but this is something we might want to look into.

![Screen Shot 2020-05-20 at 5 20 20 AM](https://user-images.githubusercontent.com/6329898/82445450-ab01a500-9a59-11ea-9a73-2d3cd97521e0.png)

**Comment by hmarcks** [comment]
Totally, this is on my list, thanks
