### ISSUE TITLE
Documentation Edits

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#1159]
Criminal Forfeiture Documentation:
"Criminal Forfeiture is a proceeding in which the government attempts to prove that certain property is the fruit of a crime, and therefore may be seized by the State. This is a civil proceeding and the criminal expungement statute does not specifically refer to it. However, this charge is usually tried in the same proceedings as the underlying criminal case, and prosecutions of this charge type receive criminal procedure protections. As such, there is a reason to think that these charges are type-eligible. 
Therefore, best practice would be not to file on these charges standing alone, but if the case on which the charge appears is otherwise eligible for expungement, then add this charge to the list of charges to be expunged."

Traffic:
Where currently it says Chapter "800", instead write Chapter "800 and 481-483 (old sections)"

### This task is done when:
 -
 -

**Comment by KentShikama** [comment]
Resolved with https://github.com/codeforpdx/recordexpungPDX/pull/1164
