### ISSUE TITLE
Fugitive Complaint in another form

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#1172]
We currently have Fugitive Complaint as a casetype. These are not eligible, whether they are dismissed or convicted, or with any other disposition. 

One form of this is when the case name is 'Fugitive Complaint' or something like that. 

Another form, which we currently do not catch, but should, is 'Extradition'.
Extradition characteristics for an extradition to Washington State:
Charge name: "/WA"
Statute: "WA"
Case Type (in OECI): "Extradition"

My proposed way of catching these would be to search Charge name as "/WA" or "/CA". These are the most common States that will seek extradition. 

### This task is done when:
 - Update the Charge Classifier with this new criterion
 - Add a unit test

**Comment by wittejm** [comment]
@michaelzhang43 can you sent me example cases that have these keywords?

**Comment by wittejm** [comment]
@michaelzhang43 would "/WA" or "/CA" be the complete text of the charge name? Or would that just appear at the front of the charge name, like "/WA Criminal Mischief" or something?

**Comment by michaelzhang43** [comment]
It would be the complete text

**Comment by michaelzhang43** [comment]
Also, is 'Case Type' in OECI something that we already track? If so, we could just see if the Case Type is an "Extradition:

**Comment by wittejm** [comment]
Yep, cool let's do that. To devs: this field is the `violation_type` used in ChargeClassifier:
https://github.com/codeforpdx/recordexpungPDX/blob/692138344b34be82a7895556aa1d91d1eca9e5b5/src/backend/expungeservice/charge_classifier.py#L43

**Comment by KentShikama** [comment]
So to summarize, do we want a new charge type that is called Extradition and classify the charge as such whenever "Extradition" is in `violation_type`? Or is it acceptable to put this under the existing [CivilOffense](https://github.com/codeforpdx/recordexpungPDX/blob/master/src/backend/expungeservice/models/charge_types/civil_offense.py#L11-L15) charge type?

**Comment by wittejm** [comment]
Let's add it under Civil Offense, since it already includes contempt and fugitive complaint.

**Comment by KentShikama** [comment]
@michaelzhang43 @wittejm Based on some further research, I'm going to change the matching logic to if the charge name contains any of the following strings:

```
['/AL', '/AK', '/AS', '/AZ', '/AR', '/CA', '/CO', '/CT', '/DE', '/DC', '/FL', '/GA', '/GU', '/HI', '/ID', '/IL', '/IN', '/IA', '/KS', '/KY', '/LA', '/ME', '/MD', '/MA', '/MI', '/MN', '/MS', '/MO', '/MT', '/NE', '/NV', '/NH', '/NJ', '/NM', '/NY', '/NC', '/ND', '/MP', '/OH', '/OK', '/OR', '/PA', '/PR', '/RI', '/SC', '/SD', '/TN', '/TX', '/UT', '/VT', '/VI', '/VA', '/WA', '/WV', '/WI', '/WY']
```
