### ISSUE TITLE
User survey form

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#1188]
I think we need to know about app usage as much as we can, and since we are not saving user data directly, I think asking our users to self-report could work. I expect many of our serious users will be tracking their own numbers anyway.

For example, being able to report the following publicly and with confidence would be awesome: “Working with 10 users/organizations, we helped 1000 individuals analyze their records this month for eligibility. 200 of those clients are following up to expunge their records.”  

This could be on a Google Form that we ask our users to fill out e.g. every month. It needs to be short and as painless as possible. 

I will bring this up tomorrow!

**Comment by wittejm** [comment]
I made this Google form. It's a standalone one-time form, so there's a bit more work to set it up to work as a monthly report. https://forms.gle/MJpm2ctnRC52nsu7A

**Comment by hmarcks** [comment]
Just noting here that we could use the [Mailchimp survey](https://mailchimp.com/help/create-a-survey/) platform since it would integrate nicely with our mailing list.

**Comment by hmarcks** [comment]
Here's a draft of the email and survey, feedback please and let me know if other items should be added to our features update in the email.

![Screen Shot 2020-07-26 at 11 27 29 PM](https://user-images.githubusercontent.com/6887982/88503564-c1673800-cf97-11ea-97aa-038d97c32597.png)

**Comment by wittejm** [comment]
This looks great!

Maybe the first survey question question could say, "last month" instead of "this month"? Just to be clearer that it's not asking, "In the last 30ish days"

To make it even more explicit, how convenient is to specify the month for each survey? Would each one be created in Mailchimp as an independent dataset?

**Comment by hmarcks** [comment]
> Maybe the first survey question question could say, "last month" instead of "this month"? Just to be clearer that it's not asking, "In the last 30ish days"

Yeah, updated

> To make it even more explicit, how convenient is to specify the month for each survey?

The survey could be updated each month since I think the emails will need to be done manually each month as well as I don't see a great process for automation (we sometimes will want to add content and probably not always send on the last day of the month)

> Would each one be created in Mailchimp as an independent survey and collected as an independent dataset?

We could do this, but I think just updating the text each month then attributing the submission dates might be easier.

**Comment by wittejm** [comment]
All sounds good.
