### ISSUE TITLE
Changing B Felony convictions with subsequent arrests to type-ineligible

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#1189]
Not sure if this will require major changes in logic. If it does, please just make a note and I'll take this down, because it's not a major issue. 

A user saw a case (ping Michael Zhang for case no) displaying Type Eligible (and Time Ineligible) for a B Felony Manu/Del 2. This is correct, but the user reported this as confusing. 

If it's easy, let's change B Felonies with subsequent arrests to Type-Ineligible. If not, just post a comment below and I'll close the issue

### This task is done when:
 -
 -

**Comment by KentShikama** [comment]
Hmm, Class B Felonies are type eligible though. I realized we never wrote down the formal definition of this internal term: "a charge is type eligible if it can be time eligible under some context (no matter how rare)". Perhaps the user is telling us that this information isn't useful. We probably want a larger discussion around how to hide "internal information" such as the diamonds for ambiguous charge types and now type eligibility once the edit charges feature is in.

**Comment by michaelzhang43** [comment]
Agree. I'm writing up another issue right now that would subsume this. Closing this issue.
