### ISSUE TITLE
Display $ owed in summary

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#1191]
As per recent discussion, we should mark $ owed cases more clearly: 

1. put any $ owed in the summary panel next to each case where $ is owed. Something like:
Charge Name - Arrested m/d/y - $20 owed in case
I realize that for cases with multiple charges, multiple charges will get that tag, making it seem the person owes many times their actual debt. hence the "owed in case" - am open to other phrasings. 

2. Make a separate section for cases with $ owed, below the section for Eligible Now cases

### This task is done when:
 -
 -

**Comment by wittejm** [comment]
Do we still want to indicate in the case detail block, the info "This becomes eligible after the case balance has been paid" ? Something other than the green eligible banner?

**Comment by michaelzhang43** [comment]
Oh yes @wittejm . I had forgotten about that step. Yes, we should put cases with $ owing in a separate section below the Eligible Nows

**Comment by michaelzhang43** [comment]
Let me actually edit the original query

**Comment by hmarcks** [comment]
Here are some thoughts on how to show this:

![balance](https://user-images.githubusercontent.com/6887982/83806033-7ce5ad00-a676-11ea-8511-050d84cfc303.png)

**Comment by KentShikama** [comment]
I realized that if there are multiple charges in a case, it is not clear which charge the balance due is attached to.

**Comment by michaelzhang43** [comment]
Sorry, just seeing the updates now:

I personally like the combination of Summary Option 2 and Case Option 1. I think in both of these, the balance due is attached to the case itself, rather than any of the charges specifically. in Summary Option 2, the charges are implicated as being ineligible until paid off, but the dollar amounts aren't duplicated, creating the illusion of owing multiple times the actual amount

**Comment by hmarcks** [comment]
> I realized that if there are multiple charges in a case, it is not clear which charge the balance due is attached to.

Does it matter what charge in the case it relates to, or do we just need to know the case has a balance.

After our last discussion I also like Summary Option 2 + Case Option 1 because the Summary categories get a bit complex, although it does reveal more detailed information in Summary Option 3.

**Comment by wittejm** [comment]
The current open PR #1218 applies the dollar badge in the summary panel. The other two new features proposed here are separated into new issues #1226 and #1227 and can have independent PRs.

**Comment by wittejm** [comment]
The issues there support @hmarcks and @michaelzhang43 's own endorsements for Summary option 2 and Case option 1.

**Comment by wittejm** [comment]
completed in various recent PRs
