### ISSUE TITLE
Adjust error message: "Technical difficulties..."

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#1195]
This includes "please contact system administrator" but there is no way for a user to do so. We need to provide contact information. Maybe create a support account with forwarding like "help@recordsponge.com"?

**Comment by wittejm** [comment]
Assigning Kent for setting up the email forwarding part, not necessarily the text update part.

**Comment by wittejm** [comment]
@KentShikama is still assigned to set up the email alias as the owner of our namecheap account. But someone else can update the message text. We'll use the email address: help@recordsponge.com

**Comment by KentShikama** [comment]
Resolved with https://github.com/codeforpdx/recordexpungPDX/pull/1214
