### ISSUE TITLE
Post-authentication removal redesign of header

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#1198]
Since we no longer have a login button, the header for  https://dev.recordsponge.com/ might need some adjustment. I'm guessing either we would want to highlight the "search" a bit more or perhaps have a big button on the landing page so that users are directed at our app's main function.

Pinging @hmarcks for comments.

**Comment by hmarcks** [comment]
Yeah, I'll look at updating the landing page.

We'll also need to edit some language on the landing page and Manual regarding accounts. I'll suggest some edits in the [Manual doc](https://docs.google.com/document/d/1Su078uVl_tg0TuvyAUGr8n2IBQolhWl0H3rN1LUFRNI/edit?usp=sharing).

**Comment by hmarcks** [comment]
Do you think we should have a way to log out of OECI since we don't have an account they can log out of? Otherwise terminating the OECI session upon closing the browser window might be fine, if possible.

**Comment by KentShikama** [comment]
I don't think it is necessary to provide a log out. OECI expires sessions in ~15 minutes and our token that holds the OECI credentials in [2 hours](https://github.com/codeforpdx/recordexpungPDX/blob/0a3ee77382978718fa87c0e205033e44aeaee282/src/backend/expungeservice/endpoints/oeci_login.py#L43). Since the OECI credentials are encrypted server side, OECI credentials can only be used in ways that our server intends. In other words, even if you happened to use our site through a public computer, the next nosy person can only further search public records until the OECI session expires (but not do things like reset your OECI password or any other functions the main OECI site provides).

**Comment by KentShikama** [comment]
And you can navigate back to the landing page by clicking the RecordSponge logo/icon on the top left.

**Comment by KentShikama** [comment]
That said I could see arguments for accessibility reasons or to give people a sense of "unnecessary" security.

**Comment by hmarcks** [comment]
@michaelzhang43 and all, what would you like the process to be for new users now that we don't have accounts?

Should we encourage them to fill out a form that gives us their contact info (email, name, org)? This would be helpful for surveys/analytics and announcements.

Or simply say that they only need to get OECI credentials to use the software?

**Comment by wittejm** [comment]
I support having verbiage on the front page saying this: we ask anyone using the software to be in touch so that we better maintain, scale, and improve our work and community. It could be as minimal as providing @michaelzhang43 's email, but I definitely like having a link to our own form to fill out.

**Comment by michaelzhang43** [comment]
1. Let's present the 'Search' button like we did with the 'Login' button before
2. I agree that we don't need a logout button
3. Perhaps we could have a mailing list?

**Comment by hmarcks** [comment]
I propose creating a simple form (built by us or Google?) that collects email, name, and org. We can then use the emails to push out mass communications or to contact individually. We'll need a system to manage email subscriptions, I can look into that, any suggestions?

**Comment by hmarcks** [comment]
Mailchimp has a good free tier: https://mailchimp.com/pricing

The free tier only allows one email address (user) to access the account, so I wonder if we should create an mailchimp@recordsponge.com (or something more generic) email address for us to share. Bad idea?

**Comment by KentShikama** [comment]
Linking https://github.com/codeforpdx/recordexpungPDX/issues/1188
