### ISSUE TITLE
Webpage: list associated organizations

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#1200]
Our networking and outreach just accelerated in the last few days and I think we need to share our connected organizations on the website. This would both support our legitimacy and amplify their direct efforts. 

This belongs on separate page but should be linked on the landing page.

It could have expungement organizations using recordsponge. It could also include our own endorsements of social/criminal justice organizations. 
 
### This task is done when:
 - @michaelzhang43 start the list we should share
 - Someone design / write copy for the new page, and the linking blurb on the landing page.
 - Implement the page html, the link in the header, and the blurb.

**Comment by michaelzhang43** [comment]
Portland Community College: Paralegal Program
https://www.pcc.edu/programs/paralegal/
contact: Leni Tupper

Medford Probation and Parole, Community Justice Center
https://jacksoncountyor.org/community-justice
contact: Eric Guyer

Criminals Anonymous, peer-led addiction recovery group
https://crimanon.org/ 
contact: Bear Cubbedge

Redmond Housing Works, Redmond OR 
https://www.facebook.com/OregonHousingWorks/
contact: Andy Hall

**Comment by michaelzhang43** [comment]
Others to come - just waiting on permission to list them as partners

**Comment by michaelzhang43** [comment]
Additional Partners:
Lane Public Defender Services
http://www.lanepds.org/
contact: Zara Lukens

**Comment by michaelzhang43** [comment]
In the absence of organizing immediately into a 501(c)(3), I think that with RecordSponge's newfound publicity, we should 'borrow the credibility' of our partners and code for America. 

@wittejm @KentShikama @hmarcks what do you all think of making this high priority so that people seeing the page for the first time due to new publicity won't think we're a scam?

**Comment by hmarcks** [comment]
Agreed, and I think we should put this on the main page so it's more prominent. I'll mock up a design...

**Comment by hmarcks** [comment]
@michaelzhang43 and if you have any short testimonials from any of the partners we could quote, that would be helpful as well.

**Comment by michaelzhang43** [comment]
I don't have any of these currently, and only Sarah has used it extensively at this point. I'll ask her for a quote.

**Comment by hmarcks** [comment]
Here are a couple options that would be quick to implement. One with more info one with less. Both link out to the partner websites:

![Artboard](https://user-images.githubusercontent.com/6887982/84440821-4a9cf800-ac00-11ea-9d34-16c740aad7ce.png)

**Comment by michaelzhang43** [comment]
Ooh I really like Option 1. For Lane PDS, can you change the location from 'Lane County' to 'Eugene'

**Comment by michaelzhang43** [comment]
Another One: 

Clackamas Workforce Partnership
www.clackamasworkforce.org
contact: Amanda Wall
