### ISSUE TITLE
Remove the icon next to type eligibility

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#1206]
As suggested in this issue: #1190

This is an immediate improvement: Remove the check mark or "X" mark that appear next to charge type.

As discussed in issue #1190, this icon is sometimes confusing. Removing the symbol in all cases is the cleanest solution, and there's no loss of information to the user, I believe. More thoughts on why in the other issue.

**Comment by Ark20** [comment]
pull request #1225
