### ISSUE TITLE
Remove redundant error banner (missing disposition) when the case is Open 

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#1223]
This is a behavior fix that we made some time ago but the issue re-appeared due to other recent changes:

I'm pretty sure this is undesired behavior, but pinging @hmarcks to verify.

In this example, the same case number appears twice.

![repeated_error_banner](https://user-images.githubusercontent.com/2104990/84431683-8a53e780-abe0-11ea-95f1-4c3fb636ce8f.png)

The "missing disposition" error should only show if the cause of the error is for something other than the case being open. If the case is open, the disposition is expected to be missing. 

These errors are generated in the backend, so the logic check for this should appear there.

**Comment by hmarcks** [comment]
Agreed, if the missing disposition is for an open case, don't show the banner.
