### ISSUE TITLE
Add a Balance Due by Case section in summary panel

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#1226]
Related to #1191

**Comment by swervinerv** [comment]
@wittejm should this breakdown only display cases that still have a balance or should it display all cases even if they have a $0 balance?

Basing the changes on this mockup that was called out in #1191 
<img width="1151" alt="Screen Shot 2020-06-14 at 9 12 04 AM" src="https://user-images.githubusercontent.com/6025685/84598515-333c5580-ae20-11ea-876d-c23fd1581abe.png">

**Comment by wittejm** [comment]
It shouldn't show cases with zero balance.

**Comment by wittejm** [comment]
completed with #1242
