### ISSUE TITLE
Add Balance Due banner in case detail block

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#1227]
Related to #1191 
 
See mockup for Case Option 1 on that issue.

**Comment by Ark20** [comment]
Where should the paying balances text link to on this? I've added the div & styling

**Comment by wittejm** [comment]
I don't think a good target for that link exists yet. It will need to part of the intended changes to the manual. I'd say for now you can defer that part and just leave the link out of this banner.
