### ISSUE TITLE
Link to case in summary brings you to the top of the first eligible charge rather than the case. 

### ISSUE THREAD

**Issue by zeayan** [codeforpdx/recordexpungPDX#1228]
User cannot see the case number if they click on the link to case under Search Summary. It should bring you to the top of the case rather than the top of the first charge. User would need to scroll up in order to see case number, status, and balance. 

It's hard to tell which case corresponds with the case the user tapped on because the case number is not listed in the summary. First time users can think it's the first full case on the screen or have trouble finding information about the case that's in the header. 

EDIT: This might behave correctly. I've realized that it takes you to the top of the charge for cases with multiple charges. This issue is regarding cases with only one charge or if the charge is the first one listed. In that case, this behavior seems like a bug. 

### This task is done when:
 -
 -

**Comment by KentShikama** [comment]
We could choose to always snap to the top of the case.

**Comment by wittejm** [comment]
Case links (in the Balances section) are going to the case detail block; Charge links are correctly going to their charges.
