### ISSUE TITLE
Align the information in the case headers. 

### ISSUE THREAD

**Issue by zeayan** [codeforpdx/recordexpungPDX#1229]
Information in the case headers (case, status, country, balance, name, DOB) are not aligned to each other in difference cases.

**Comment by wittejm** [comment]
We've brought this up before and I'm pretty sure we had a consensus to leave it as is. Tagging @hmarcks in case I'm mis-remembering but also closing this issue.

**Comment by hmarcks** [comment]
I was going to explore fixed column widths it but i don't think it's urgent. The add/edit feature will affect this quite a bit so it should at least wait until that's done.
