### ISSUE TITLE
Change one line print for non-blocking Charges to say "charged on DATE"

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#1231]
Instead of "arrested on DATE". For example, you do not get arrested for getting a parking ticket.

**Comment by KentShikama** [comment]
@michaelzhang43 Pinging for possible help on phrasing.

**Comment by michaelzhang43** [comment]
Hmm. "Charged on" is not always accurate since a charge that was No-Complainted does not produce a 'charge' technically. 

What if we just got rid of the "Arrested on" language and didn't replace it?

**Comment by hmarcks** [comment]
I'm not sure if this is the same area you're talking about, but it has been bugging me that we say "arrested" in the summary and "charged" in the charge details. And wouldn't we also have to worry about saying "charged" for No-Complaints in the charge details?

![Screen Shot 2020-06-13 at 11 54 17 AM](https://user-images.githubusercontent.com/6887982/84574571-e77ca400-ad6c-11ea-994f-f076c2cf741a.png)

**Comment by KentShikama** [comment]
> as to the “charged” v “arrested” issue, I think we can resolve by replacing arrested with charged in the summary panel. For no complaints we don’t need to do anything different since the date still serve as a useful heuristic

- @michaelzhang43

**Comment by victorjz** [comment]
It seems decision is pending but when you decide you can let me know if you'd like me to do this one.  I'm staring right at the responsible line. We could also change the variable name if that sounds nice.
```
       def to_one_line(self) -> str:
        short_name = self.name.split("(")[0]
        arrested_date = self.date.strftime("%b %-d, %Y")
        disposition = str(self.disposition.status.name)
        owed = f" $ owed" if self.balance_due_in_cents > 0 else ""
        return f"{short_name} ({disposition}) - Arrested {arrested_date}{owed}"
```

It seems also that `test_record_summarizer` could use changing since it has test data with 'Arrested'
```
     assert record_summary.eligible_charges_by_date == {
        "Eligible Jan 1, 2030": [
            (
                case_possibly_eligible.charges[0].ambiguous_charge_id,
                "Theft of services (CONVICTED) - Arrested Jan 1, " "2010",
            )
        ],
```

**Comment by wittejm** [comment]
I endorse making this change now @victorjz . Yep, adjusting the test will be needed.

**Comment by wittejm** [comment]
Completed with #1254
