### ISSUE TITLE
Create HTML fixtures for full mock records

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#1238]
Linking related PR https://github.com/codeforpdx/recordexpungPDX/pull/964

Please contact @KentShikama for details.

**Comment by wittejm** [comment]
Shall we close this in light of the separate approach in #1304 ? I think the only potential reason for html fixtures is that the user could view the mock OECI page, which may be weird in the context of the ahistorical examples.

**Comment by wittejm** [comment]
Displaced #1304
