### ISSUE TITLE
Create editable forms out of forms in https://recordsponge.com/manual#appendix

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#1239]
Field names should be the same as https://www.mcda.us/index.php/documents/conviction-motion-and-affidavit-form.pdf/ if applicable.

**Comment by wittejm** [comment]
Making this lower priority than our webapp dev issues. Let's be confident that our software users think this should become a priority.

**Comment by KentShikama** [comment]
Multnomah county is done with https://github.com/codeforpdx/recordexpungPDX/pull/1321; potentially 35 more to go.
