### ISSUE TITLE
Landing page audience shift and potential intake form

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#1249]
Now that we have some partners using RecordSponge, we would like to shift the focus of recordsponge.com to clients. The main messaging should talk to folks who may be interested in expunging their record, with a secondary focus on orgs who are interested in using RecordSponge.

We could potentially create a form for clients to fill out, and direct that info to our partner orgs (perhaps based off zip code, or chosen by client).

Mockup with more info:

![landing-page](https://user-images.githubusercontent.com/6887982/84690583-52aead80-af08-11ea-9932-68d6ca088cbd.png)

**Comment by michaelzhang43** [comment]
I love the aesthetics of this, although I think the content still commingles RecordSponge with my law firm too much. In the next re-design we should switch me to just being listed as one of the partners. 

**Market of providers**
Another idea I'm having now that I'm looking at your design is to have transparent pricing to drive down price by eliminating implicit price-fixing. 
@KentShikama #radicalmarkets
Like for QQ Law, I can say, "analysis free; paperwork costs $100 per eligible case; no income restrictions; Portland"
Then I imagine PCC's would be "analysis and paperwork free; income restrictions; Portland"
etc., listing 
1) price for analysis only
2) price for filing materials
3) whether the price includes court fees
4) whether income restrictions apply (esp. for non-profits)
5) location

In fact, later on I can set my own price to be like $500/case to 1) price myself out of the market, 2) encourage reliance on other partners, and 3) funnel any incidental profits back into RecordSponge to pay for its own OECI creds and hosting

**Comment by hmarcks** [comment]
> ...the content still commingles RecordSponge with my law firm too much.

Do you want QQ Law to still be mentioned in the **Who We Are** section? Another option is to mention you by name, and perhaps link to a bio.

**Market of providers:** cool, so we could collect all this info from partners if they want to be listed in the market.

5. location: this is one of my main questions about how we would route clients. Should it be based off where the client lives currently? Obviously clients could have cases all over the state.

**Comment by michaelzhang43** [comment]
One of the points that came up in last Thursday's meeting was that having some close affiliation with a law firm helps the legitimacy, so I think we should keep it. 

Yes

In general I think clients could just route themselves to providers if we post the provider's location. It would then be on the client to file the paperwork themselves in most cases

**Comment by wittejm** [comment]
This looks awesome. I think the front page should mention that it's open-source software; maybe in the bottom Code for PDX blurb. 

Let's make the Eligibility Check form a lower priority and just direct people to service providers for now. We'll need to make sure our user orgs can benefit from and also handle a rapid-intake setup, like what Michael already has. 

That won't be too hard to set up: we just generate and send them an email from the form. But this front page change looks great and is really low-hanging fruit.

**Comment by hmarcks** [comment]
Sounds good, figured we might want an intermediate step before the intake form.

My main questions are:
1. What info we want to show for each Partner (Michael outlined some) and directions for contacting them.
2. Content for **Who We Are** section.

Updated mockup without intake form:
![landing-page-phase1](https://user-images.githubusercontent.com/6887982/84730794-d7c3b200-af5c-11ea-9c73-67238bf8b10f.png)
