### ISSUE TITLE
Do not show "Charges are ineligible until balance is paid" if charge is already ineligible

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#1253]
![Screen Shot 2020-06-16 at 6 31 29 AM](https://user-images.githubusercontent.com/6329898/84780942-0e202200-af9b-11ea-85d7-5aceed71e3dc.png)

**Comment by Ark20** [comment]
@KentShikama I'm not super clear on the backend but want to fix this one. How would I check the charge eligibility in the case file ?

**Comment by KentShikama** [comment]
Since the banner is applied on the case, the logic more precisely is that if all charges on the case are ineligible, then don't show the banner. Everything comes as part of the record summary object from the backend. See the response object for the /api/search endpoint request at `Tools -> Web Developer -> Network`.

**Comment by Ark20** [comment]
Thanks @KentShikama! With that logic I can still see the banner if say one charge is ineligible but others aren't. @hmarcks used the language "Eligible charges become eligible when balance is paid" can we make the banner say that or "Eligible charges are ineligible until balance is paid" while keeping this same logic 
<img width="832" alt="Screen Shot 2020-06-17 at 1 28 39 AM" src="https://user-images.githubusercontent.com/20876942/84875469-dd8fc500-b03a-11ea-9c06-7d1f8b3ef67d.png">

**Comment by Ark20** [comment]
The updated logic ` let ineligibleCharges = 0; 
    let allIneligible = 0
    for (let i = 0; i < charges.length; i++){ 
      let typeEligibility = charges[i].expungement_result.type_eligibility.status
      if (typeEligibility == "Ineligible") {
        ineligibleCharges++
      }
    }
    if (ineligibleCharges == charges.length) {
        allIneligible=1
      }`
