### ISSUE TITLE
Maintain search results

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#1257]
We would like to keep the search state unless another search is performed, the site is navigated away from, or the browser is closed. The reason is because folks may need to reference the Manual and return to the search they performed.

Currently if you perform a search, then go to the Manual or landing page, then return to the search view, your search results are cleared. We want to maintain them.

**Comment by swervinerv** [comment]
Do we also want to save the search state if the user refreshes the page or should this only focus on keeping the state during navigation?

**Comment by KentShikama** [comment]
I have already taken care of this in my form filling branch.

**Comment by hmarcks** [comment]
I’m thinking it would be expected that a refresh would clear it.

Nice!

**Comment by wittejm** [comment]
This actually requires some additional work messing with the AppRouter and replacing `<a>` tags with `<Link>` tags, which is largely independent of the change made in #1307. @KentShikama Alright to unassign you can decouple this as a new PR?

**Comment by KentShikama** [comment]
@wittejm I don't understand off the top off my head why the additional work is needed but sounds good.
