### ISSUE TITLE
Branch feature to censor case numbers and names

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#1258]
We want to make some user guide videos with the app. To hide personal information, we can use a version of the app that replaces case numbers with "**********" and replaces names with "LAST, FIRST MIDDLE "

This feature won't go into master and will just remain in its own branch on the repo.

**Comment by wittejm** [comment]
I'm not sure what would look best for what actually gets displayed for these. @michaelzhang43 what do you think?

**Comment by michaelzhang43** [comment]
Your suggestion sounds great

**Comment by wittejm** [comment]
I have a branch for this in my repo:
 https://github.com/wittejm/recordexpungPDX/tree/censor_private_info_in_search_result
