### ISSUE TITLE
Bug Report: PCS 1 B felony not prompting 'Is This Marijuana' differentiation

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#1259]
Possession of a Controlled Substance in Schedule 1, B Felony (with subsequent arrests) is type-eligible if the underlying drug is marijuana. We should be prompting the "Is This Marijuana" differentiation question in these cases. 

Currently, these show up as Ineligible based on B Felony rule. 

<img width="702" alt="Screen Shot 2020-06-18 at 1 22 32 PM" src="https://user-images.githubusercontent.com/59623009/85068146-c5b55f80-b166-11ea-8b72-33fec59f6683.png">

### This task is done when:
 -
 -

**Comment by wittejm** [comment]
Looks like our classifier applies the marijuana question for just Manu/Del. How should we identify possession? Using the statute, or charge name? And if it's the charge name, how robust of a charge name pattern?

**Comment by michaelzhang43** [comment]
Ah right - we used to have the 'pcs is eligible' rule so it would have been redundant to include possession

Characteristics:
It's annoying because they've renumbered the statute (formerly 475.992.4A) several times. It's now 475.840. 

B Felony status, Statute = 4759924A OR 4757521A

OR Chargename contains "1" AND "Poss" AND "Sub"

**Comment by KentShikama** [comment]
> we used to have the 'pcs is eligible' rule so it would have been redundant to include possession

Could you remind me about this? I don't think it is a rule in our codebase now right, @wittejm ?

**Comment by michaelzhang43** [comment]
Ah yes, that's right. 

And then we took out the PCS rule to comply with actual statutory law.

**Comment by KentShikama** [comment]
@michaelzhang43 I see. Currently we categorize 475.860 (or if it has mj or marij in the name of the charge) as MarijuanaEligible without any questions. Are you suggesting 4759924A or 4757521A should be MarijuanaEligible if mj and otherwise just follow level-based classification? And what about 475.840 that you mention?

**Comment by michaelzhang43** [comment]
Yes, 4759924A or 4757521A (and former section 475.840) refer generally to pcs 1, which could be of marijuana. These are all old statutes that didn't distinguish between marijuana and meth/heroin. So they might be eligible

**Comment by KentShikama** [comment]
But no charges have ever been filed under 475.840 - it is always either 4759924A or 4757521A?

**Comment by michaelzhang43** [comment]
I'm not sure - it's just that it appears in Oregon Laws as a statute that 4759924A was renamed to. Then they re-renamed it so it's no longer 475.840

**Comment by KentShikama** [comment]
Will a PCS under 4759924A or 4757521A ever be "Felony Unclassified"?

**Comment by michaelzhang43** [comment]
Good question. Perhaps. But possession is never charge-able as a Class A Felony, if that helps. I'm thinking now that you say this that a better way to search for this type of case is in the Charge Name, either "PCS" & "1"   or   "Poss" AND "Sub" AND "1"

**Comment by KentShikama** [comment]
What if the charge name has no schedule number?

**Comment by michaelzhang43** [comment]
Hmm

If it's just "PCS" or "Possession of a Controlled Substance" AND it's a B Felony or Unclassified, then we can ask if it's of marijuana. If it's a C felony we don't need to ask, of course

**Comment by KentShikama** [comment]
@michaelzhang43 I've summarized the changes in the commit message as follows:

> After identifying a PCS, we mostly mirror the question generating logic for manu/del. The notable difference is that a schedule 2 PCS that is Felony Unclassified is either a B or C felony whereas a schedule 2 manu/del that is Felony Unclassified is either an A or B felony.

Does this sound right?

**Comment by michaelzhang43** [comment]
Yes that's right
