### ISSUE TITLE
Collect Partner Info

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#1260]
We want to direct folks interested in expungement to our partners, but before we do that more aggressively in the landing page redesign #1249 , we need more information about their services and contact info.

For each partner we want to collect the following info:
**1. Analysis price** (should we encourage this to always be free?)
**2. Filing Cost**
**3. Court Fees Included?**
**4. Income Restrictions?**
**5. Locations** (locations of charges?)
**6. Preferred contact email, phone, web form, name of contact**

We will direct all clients to submit the same info: full name, previous names (including aliases and maiden names), and date of birth.

This will probably be an email @michaelzhang43 or @wittejm will send to collect the info.

**Comment by michaelzhang43** [comment]
Sarah Kolb
1. Analysis price (should we encourage this to always be free?)
Free
2. Paperwork Cost
$100/case
3. Court Fees Included?
No
4. Income Restrictions?
No
5. Locations (locations of charges?)
Jackson County
6. Preferred contact email, phone, web form, name of contact
medfordexpungementclinic@gmail.com, 5417784473

Criminals Anonymous
1. Analysis price (should we encourage this to always be free?)
Free
2. Paperwork Cost
$100/case
3. Court Fees Included?
No
4. Income Restrictions?
No
5. Locations (locations of charges?)
Multnomah County
6. Preferred contact email, phone, web form, name of contact
hrcubbedge1776@gmail.com, https://www.qiu-qiulaw.com/crimanon

Coming soon - PCC

**Comment by hmarcks** [comment]
@michaelzhang43 here is all the info I'm using for the directory on the landing page. I made some assumptions like the "Location". Please add or edit any info here: https://docs.google.com/document/d/1l7x9Ql_icbU66cOenhZ_FBSXbhbzAHCHGDhiJvEe-yg/edit?usp=sharing
