### ISSUE TITLE
Update html to Reorganize Manual (redesign Phase 1)

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#1267]
Apply the design changes from @michellelsfong 's design ( .sketch file is linked in the slack channel).

**Comment by michellelsfong** [comment]
Here are the designs! They shouldn't be used as reference for body copy, some of it is already out of date. The task:
1. Create new pages with the same template as the manual, but without the sidenav. The new pages are [FAQ](https://github.com/codeforpdx/recordexpungPDX/files/4829060/03.FAQ.pdf), [Appendix](https://github.com/codeforpdx/recordexpungPDX/files/4829062/04.Appendix.pdf), [Privacy Policy](https://github.com/codeforpdx/recordexpungPDX/files/4829063/05.Privacy.Policy.%2B.License.pdf). License and short list of credits will be under the Privacy Policy.
2. Update the privacy policy link in the footer. Add FAQ and Appendix links to the right of it. These should be spaced pr5 apart. For context, pr5 is defined as spacing to the right of something. [Here are the specs for that.](https://github.com/codeforpdx/recordexpungPDX/files/4829075/06.Footer.specs.pdf)
3. Remove FAQ, Appendix, Privacy Policy, and License from the manual and its sidenav. Follow this [manual spec](https://github.com/codeforpdx/recordexpungPDX/files/4829082/02.Specs.pdf) to update sidenav padding, remove an extra divider, and update 4 anchor links.

**Comment by wittejm** [comment]
Thanks @michellelsfong ! Just to confirm, it looks like the Manual header should be removed from the manual page? For html style the page should still have a single page header with  `<h1>` tags, but we can put that on the same "Manual" text and make it `visually-hidden`.
