### ISSUE TITLE
Disclosure functionality for new landing page

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#1271]
We want an expandable (disclosure) for our new Partner list.

I recommend this React component for it's accessibility considerations: https://reacttraining.com/reach-ui/disclosure

The work can be done on this PR (feature branch): #1276. It has the markup for the styles in the mockup below. I've paused on it until this issue is complete.

![disclosure](https://user-images.githubusercontent.com/6887982/85501787-a3c73d00-b5ab-11ea-899e-e0469d9d9fed.png)

**Comment by wittejm** [comment]
merged into Landing page feature branch
