### ISSUE TITLE
Welcome email for Mailchimp listserv signup

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#1278]
- The email draft is [here](https://docs.google.com/document/d/1rMU6tyjHHspj2G9SAn5ZNouBtTXZGJ2sxeZ-K24_DMY/edit?usp=sharing)
- Mailchimp needs an origin email address and for now we can just use michael@qiu-qiu-law , unless we change some of the email content. 
- We need to link our new-user-profile survey. 
- Set up auto-reply and send to all pre-existing email addresses on the list.

**Comment by hmarcks** [comment]
1. I'll create the email template
2. michael@qiu-qiu-law is currently set as the sender
3. I'll work on creating the [onboarding survey](https://docs.google.com/spreadsheets/d/1_pYyghxow7k_K-IyFaK4S-NyWF0A4c5kqmf4iF8B1oM/edit#gid=1401585335)
4. What do you mean by "set up auto-reply"?
5. Do we need to add and contacts to Mailchimp who are not already in there?

**Comment by wittejm** [comment]
1-3 great.
4. Ah, yea. 
5. Yea. tagging @michaelzhang43 for his prior contacts to include.

**Comment by wittejm** [comment]
@hmarcks  This just needs a trigger to auto-send when someone signs up for the listserv, otherwise looks done

**Comment by hmarcks** [comment]
The automation is in place, closing
