### ISSUE TITLE
Content for 'who is the software for' page

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#1306]
RecordSponge is made for organizations to become expungement service providers. We provide both the software and supervision by volunteer attorneys - organizations provide the clients and, to a large extent, the expungement service. We are therefore looking to partner with organizations who have contact with many people with criminal records. If you would like a demonstration of the software and to learn more about partnering, contact jordan.witte@code4pdx.org

### This task is done when:
 -
 -

**Comment by hmarcks** [comment]
Here is a potential layout with more content.

Instead of contacting Jordan directly we could embed the existing contact form. Please review the additional content as well:

![potential-partner](https://user-images.githubusercontent.com/6887982/86877286-266ff200-c0ac-11ea-9378-04c7aed10f5b.png)

**Comment by wittejm** [comment]
I like Option 2, and also the new check box in the subscribe form. I think we'll generally want to contact everyone but checking the box is a good pretext for the email to say, "Yes, let's give you that demo!" 

I would remove "a demonstration of the software" and just have:

"If you would like to learn more about partnering please get in contact below." 

I think having just the checkbox below is a gentler way to offer the demonstration, and it's easier for people to be explicit on whether they're just interested in more info generally, or getting the demo as well.

**Comment by hmarcks** [comment]
Sounds good, do you want to create a placeholder for this view in #1304 or in a separate PR? Then I can start the HTML and put the form in.

![potential-partner](https://user-images.githubusercontent.com/6887982/87109830-44179580-c22b-11ea-8fa6-9e76ab4fa3c2.png)

**Comment by wittejm** [comment]
Completed with #1323
