### ISSUE TITLE
Add explanatory text in form filling page

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#1312]
Origin https://github.com/codeforpdx/recordexpungPDX/pull/1307#issuecomment-656323186

@wittejm has proposed the following

> This will fill and download the required pdf forms for the [#] cases that have charges eligible for expungement:
> [Case number 1]
> [Case number 2]
> [Case number 3]
> 
> Please read the complete [instructions in the manual](url) for filing the required forms for expungement. After downloading the pdfs, review their contents to verify that all the required information is present and correct. 
> 
> 
> The following required information is obtained from OECI and will be provided in the form:
> Case number
> Name of charge 
> Date of arrest 
> Date of conviction
> 
> The following information might be missing from OECI. If available, it will be provided in the form. If it is not present in OECI, some of the information may or may not be required in the application; please consult the manual. 
> Arresting Agency
> DA number
> ...etc.

**Comment by KentShikama** [comment]
> "You can also optionally provide your identifying information here to pre-populate the forms. We do not save any of your information."

**Comment by KentShikama** [comment]
@wittejm Can this now be closed?

**Comment by wittejm** [comment]
Yep
