### ISSUE TITLE
De-duplicate pdfs in frontend and backend

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#1315]
This is an issue in I noticed in #1307 that I forgot to mention:

The pdf forms to file for expungement are replicated in the frontend and backend folders. They can share though. The backend versions should be used -- they have been modified to have fillable fields.

**Comment by KentShikama** [comment]
Could you expand on this? In my head, the forms are just in the backend.

**Comment by wittejm** [comment]
https://github.com/codeforpdx/recordexpungPDX/tree/master/src/frontend/public/docs

https://github.com/codeforpdx/recordexpungPDX/tree/master/src/backend/expungeservice/files

**Comment by wittejm** [comment]
I'm pretty sure we decided to leave the original files intact, and now that the Generate feature is clearly referenced, it's easy to also get the fillable version for the relevant county. Closing this, but if I'm mis-remembering someone can re-open.
