### ISSUE TITLE
Update link for https://recordsponge.com/manual#payBalances

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#1328]
This link anchor no longer exists https://github.com/codeforpdx/recordexpungPDX/blob/9003dc6ac7e5bb3a29d20fa7be18270ca837e37f/src/frontend/src/components/RecordSearch/Record/RecordSummary/CaseBalances.tsx#L38

**Comment by wittejm** [comment]
I'm working on this. The problem is that `<Link>` doesn't support anchors (?!?) but we can instead use `HashLink` https://stackoverflow.com/questions/40280369/use-anchors-with-react-router
