### ISSUE TITLE
Form filling button in Summary

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#1341]
1. Add "Generate Paperwork" button
2. If there are no eligible charges, when button is pressed present a dialog that says, "There must be eligible charges to generate paperwork"
3. Change "Download PDF" to "Summary PDF"

<img width="1031" alt="Screen Shot 2020-07-15 at 10 13 33 PM" src="https://user-images.githubusercontent.com/6887982/87623159-635e6900-c6ea-11ea-91f7-1392aa49e9f5.png">

`<div class="flex flex-wrap justify-end"><h2 class="mv3 mr-auto f5 fw7">Search Summary</h2>
<button class="ma2 nowrap mid-gray link hover-blue fw6 br3 pv1 ph2"><i aria-hidden="true" class="fas fa-bolt pr2"></i>Generate Paperwork</button><button class="ma2 nowrap mid-gray link hover-blue fw6 br3 pv1 ph2"><i aria-hidden="true" class="fas fa-download pr2"></i>Summary PDF</button></div>`

**Comment by wittejm** [comment]
What if in addition to the "Can't do that" message response to a click, the Generate button is grayed out? I just often feel annoyed when I see a button for "Do a thing!" That responds, "Can't do the thing". But a grayed button would help with this.

**Comment by hmarcks** [comment]
The issue I have about graying out buttons is the decrease in contrast required to make a visual difference pushes the contrast ratio below WCAG's recommended ratio. I get the scenario you described but I think here we won't have a lot of folks trying to generate paperwork if they don't have any eligible charges, and if they do it's a learning moment.

Other option is to only show it if eligible charges are present.

**Comment by wittejm** [comment]
Gotcha. Leaving it as is sounds good then.
