### ISSUE TITLE
Clean up unnecessary double space before a new line in markdown

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#1355]
See https://github.com/codeforpdx/recordexpungPDX/blob/master/src/backend/expungeservice/pdf/markdown_serializer.py#L64 for example. This is fixable using a combination of multi-line strings and `textwrap.dedent`.

**Comment by nvengal** [comment]
Looking for initial feedback on the approach here: https://github.com/codeforpdx/recordexpungPDX/pull/1688

This solution is more complex than refactoring to remove the extra spaces. However, as a new dev to the project, I was having trouble mentally parsing what the markdown file should look like as the strings were built piece by piece in the existing MarkdownSerializer class. This seemed like a good opportunity to use flask's built-in jinja templating to make a more readable version of the serializer. Looking for :+1: / :-1: level feedback before I spend more time finishing this approach.

**Comment by nvengal** [comment]
PR is complete and ready for review.
