### ISSUE TITLE
Alignment issue with OECI login sceen

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#1363]
See screenshot below

![Screen Shot 2020-07-22 at 11 54 25 AM](https://user-images.githubusercontent.com/6329898/88216622-2e827280-cc12-11ea-9889-aded5b68e8f6.png)

**Comment by hmarcks** [comment]
Looks like this is an issue in Firefox, is that where you took this screenshot? It's not misaligned in Chrome and Safari.

**Comment by KentShikama** [comment]
It seems to depend on the screen size. It is centered when on a large screen.

![Screen Shot 2020-07-22 at 12 05 10 PM](https://user-images.githubusercontent.com/6329898/88217594-a4d3a480-cc13-11ea-9204-95da5b0c7f06.png)

**Comment by KentShikama** [comment]
And yes I am on Firefox.
