### ISSUE TITLE
Mention the form-filling feature in the Manual and Appendix

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#1370]

**Comment by hmarcks** [comment]
Thinking we should also include it in the Manual and possibly on the partner page and landing page

**Comment by wittejm** [comment]
@michaelzhang43  will provide explnantory copy for the Manual.  Move lengthy instructions in manual section into a Disclosure.

**Comment by michaelzhang43** [comment]
The next step is to fill out expungement paperwork, which involves
1. Selecting the right form
2. Inputing information from RecordSponge
3. Inputing the client's personal information

If a client has eligible charges, the Summary Panel will display a button to Generate Paperwork. Click on the button and you will be directed to input identifying information, Inputting identifying information is optional but can help save you time. 

After you input the information, RecordSponge will generate a .zip file with the expungement paperwork for all of your charges, at least in the following counties:
Multnomah, Washington, Clackamas, Jackson, Eugene, Benton, Josephine, Deschutes, Umatilla, Morrow

Instructions on how to do this step manually can be found [here (hyperlink?)]

**Comment by KentShikama** [comment]
Linking https://github.com/codeforpdx/recordexpungPDX/issues/1389

**Comment by hmarcks** [comment]
Here's the updated copy. I'll create a different issue for the Landing page and Partner page as I'm still thinking that thorugh.

![from-fill-copy](https://user-images.githubusercontent.com/6887982/88959834-3ec8cc00-d268-11ea-89ac-74bfbb4dd179.png)
