### ISSUE TITLE
Create a Record object

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#138]
## Description
Create a Record class in the models directory. This record class will have a data attribute `cases` which will be a list of cases. The record object will be able to respond a `charges` and `total_balance_due` method.

For the charges method it will enumerate through all the cases creating a list of charges to be returned.

For the total_balance_due method it will enumerate through all the cases summing up the `balance_due_in_cents` attribute. Once all cases have been summed. Divide the result by 100 and return the result.

Unit tests for the two methods can be put here: src/backend/tests/models/test_record.py
### This task is done when:

- [x] Record object exists
- [x] Record class has data attribute cases
- [x] Record class has the following methods:

- charges()
- total_balance_due()

**Comment by wittejm** [comment]
See request for changes described in the merged PR #214

**Comment by NickSchimek** [comment]
This was completed. New issue created to update tests #253
