### ISSUE TITLE
Add videos to Manual

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#1382]
Create YouTube account

Add the first video to the Manual

The second video is in progress

**Comment by KentShikama** [comment]
@hmarcks I'm thinking of taking on this task as there are no more backend items left on for the August milestone. I just want to clarify the steps here:

1. Create a Youtube account under the name RecordSponge
2. Upload @aemrich 's video at https://codeforpdx.slack.com/archives/CDCPHD8T1/p1595383926310500 to that account
3. Insert the Youtube video into the Manual page using an iframe under the "Search" section

@hmarcks @aemrich @wittejm Does that sound good?

**Comment by hmarcks** [comment]
Have at it if you would like, but I'll have it done before the milestone.

A couple other things:
• YouTube account to use contact@recordsponge.com
• The video will need to be in a responsive container
