### ISSUE TITLE
August survey and updates email

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#1383]
Send email that links to impact survey for August

Determine what updates or news to include

**Comment by hmarcks** [comment]
@michaelzhang43 @wittejm @KentShikama hey yall, let me know if you have any edits or additions to the email for this month:

![Screen Shot 2020-08-31 at 10 55 36 AM](https://user-images.githubusercontent.com/6887982/91740235-a1b7c680-eb78-11ea-87ff-bb2e371c37f8.png)

**Comment by wittejm** [comment]
LGTM!
