### ISSUE TITLE
Update copy in Form Filling page to reflect we support all counties on the Appendix page

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#1389]
See https://github.com/codeforpdx/recordexpungPDX/blob/d69322e86181ef3c4bbbc3d70e03ddbc2bc63a26/src/frontend/src/components/FillForms/index.tsx#L79-L95

**Comment by hmarcks** [comment]
Here is some proposed copy. Should we say anything more about the Stock Form? Not sure if we're confident it will be accepted.

"RecordSponge supports automatic form-filling for all the counties in our [appendix](https://dev.recordsponge.com/appendix), and will use the Stock Form for those not listed."

@michaelzhang43

**Comment by michaelzhang43** [comment]
Yes that sounds good

**Comment by hmarcks** [comment]
Updated:

![from-fill-copy](https://user-images.githubusercontent.com/6887982/88959894-54d68c80-d268-11ea-9f91-28baf04ca7ba.png)
