### ISSUE TITLE
Allow real search endpoint to be used followed by the demo endpoint without refresh

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#1404]
We never call `STOP_DEMO`. Hard refreshing the page will clear out the redux store and thus set `demo` to `false` (the initial state) but this feels like a workaround.

**Comment by wittejm** [comment]
Looks like this should flip when you click the "Or, log into OECI" link. I think that was my original intention. 

It's also possible to get from `/demo-record-search` to `/record-search` by clicking the Search button in the upper right, so it could flip `demo` to `false` then also.
