### ISSUE TITLE
Accessibility statement

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#1415]
**Accessibility Statement**
RecordSponge is committed to ensuring digital accessibility for all people. We strive to meet level AA standards from the [Web Content Accessibility Guidelines (WCAG) 2.1](https://www.w3.org/TR/WCAG21/#requirements-for-wcag-2-1). We are continually improving the user experience for everyone, and applying the relevant accessibility standards.

**Conformance Status**
The Web Content Accessibility Guidelines (WCAG) defines requirements for designers and developers to improve accessibility for people with disabilities. It defines three levels of conformance: Level A, Level AA, and Level AAA. RecordSponge is largely conformant with WCAG 2.1 level AA. We’re working to bridge the remaining gaps.

**Technical Specifications**
Accessibility of RecordSponge relies on the following technologies to work with the particular combination of web browser and any assistive technologies or plugins installed on your computer:
• HTML
• WAI-ARIA
• CSS
• JavaScript
These technologies are relied upon for conformance with the accessibility standards used.

**How We Test**
We test in most modern browsers, we use toolkits like [axe](https://www.deque.com/axe/), and we use VoiceOver in Safari to review our site.

**Limitations**
Despite our best efforts to ensure accessibility of RecordSponge, there may be some limitations. Please contact us if you observe an issue: contact@recordsponge.com

This statement was created on August 12, 2020 with guidance from the [W3C Accessibility Statement Generator](https://www.w3.org/WAI/planning/statements/).

**Comment by hmarcks** [comment]
Accessibility statement for review, cc @michaelzhang43

**Comment by michaelzhang43** [comment]
Looks great overall if true!

Do we 'use toolkits like axe and voiceover?

For the Limitations section, please put my email, michael@qiu-qiulaw.com

**Comment by hmarcks** [comment]
Yeah I use them and I know Kent has run one before.

**Comment by michaelzhang43** [comment]
Fantastic - let’s publish it and include a link on the Manual near the top. Something simple and obvious for PCC’s quality control people like, “Read our accessibility statement {here}”
