### ISSUE TITLE
Add feature list to landing page

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#1433]
Let me know if you have any feedback @michaelzhang43 @wittejm @KentShikama or others:

![Screen Shot 2020-09-11 at 5 02 20 PM](https://user-images.githubusercontent.com/6887982/92976699-c2bdc880-f450-11ea-9147-ab93137ed1f9.png)

**Comment by KentShikama** [comment]
This looks great!

**Comment by wittejm** [comment]
Yep! Looks great!
