### ISSUE TITLE
Move NMA section to top of Summary

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#1438]
Yoonjung gave some good feedback that NMA should might be best on top of the Summary panel because it needs attention before an accurate analysis can be given.

I moved it to the top and put it all in purple to highlight it more.

I also adjusted colors, font size, borders, and spacing to make the hierarchy a bit more clear.

![move-nma](https://user-images.githubusercontent.com/6887982/93731763-083a6e00-fb94-11ea-8fc5-427bb7796aee.png)

**Comment by KentShikama** [comment]
LGTM; @michaelzhang43 any opinions?

**Comment by michaelzhang43** [comment]
That makes sense. Let’s do it
