### ISSUE TITLE
September monthly survey email

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#1445]
Here's the content for the monthly email I'll send out tomorrow, let me know if you want to add anything @michaelzhang43 @wittejm @KentShikama 

![Screen Shot 2020-09-29 at 2 17 55 PM](https://user-images.githubusercontent.com/6887982/94605411-b3b38480-025e-11eb-9da3-b41fa19434ee.png)

**Comment by wittejm** [comment]
Looks good!
