### ISSUE TITLE
October Impact Survey Email

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#1451]
It's that time again! Let me know if you have anything you'd like to add @michaelzhang43 @wittejm @KentShikama 

<img width="638" alt="Screen Shot 2020-10-29 at 10 06 13 PM" src="https://user-images.githubusercontent.com/6887982/97655484-2a48cb00-1a33-11eb-8685-c01cdfa8d740.png">

**Comment by wittejm** [comment]
LGTM!
