### ISSUE TITLE
Add filling fee total to summary panel

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#1457]
Add filing fees and update balance section so they are both organized by county since that is how they are paid.

![filing-fees-and-balance](https://user-images.githubusercontent.com/6887982/98873722-80a80780-243e-11eb-987c-84bc02337483.png)

[filing-fees-and-balance.html.zip](https://github.com/codeforpdx/recordexpungPDX/files/5527218/filing-fees-and-balance.html.zip)

**Comment by hmarcks** [comment]
@wittejm @KentShikama I added the mockup and attached some markup, thanks

**Comment by wittejm** [comment]
Awesome.
