### ISSUE TITLE
Marijuana expungement form

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#1471]
The State recently published a **State-wide** expungement form for "qualifying marijuana convictions", available at 
https://www.courts.oregon.gov/forms/Documents/MJ-PCR-Mo_Decl-2020-01-01.pdf

These are the violation of a conviction for possession of less than an ounce of marijuana

Can we get this into the form filler?

**Comment by hmarcks** [comment]
I'm thinking we should also introduce logic to not include the conviction (and fingerprint?) fee for these convictions, right?

**Comment by michaelzhang43** [comment]
Great point, Hunter. I didn't think to check for these yesterday

**Comment by KentShikama** [comment]
@michaelzhang43 This feature is now enabled if you want to give a test.
