### ISSUE TITLE
Reorganizing fines and fees information

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#1530]
**Background** 
The new expungement law makes cases eligible on a faster timeline. As a result, a larger percentage of otherwise eligible clients are now blocked only by fines and fees they owe on cases. The new expungement rule further specifies that only fines and fees owed on a particular case can block that case - owing money in general or on a different case does not block that case. To account for these changes, we should make changes to our Summary Panel. 

Each "Case" is composed of one or several "Charges" and the "Balance" associated with each Case is for the Case as a whole, rather than any of the Charges in particular. 

**Current state**
In our current summary panel, we display the case numbers on which clients owe money in "Balance due by county." All criminal charges are listed under "Charges", irrespective of whether any money is owed on the charge's case. Current sections are Needs More Analysis, Eligible [date] (i.e. Future Eligible), Eligible Now, Ineligible

**Re-arrangement description**
- Create new sections for "Eligible Now if Balance Paid" and "Eligible [x date] if Balance Paid". No need to differentiate for Ineligible and Needs More Analysis sections. There may be multiple future eligibility dates Order should be 
1) Needs More Analysis 
2) Ineligible
3) Eligible Now
4) Eligible Now if Balance Paid
5) Future date 1 (no balance)
6) Future date 2 (no balance)
7) Future if Balance Paid date 1
8) Future if Balance Paid date 2

- In new sections, charges should be listed with Case Number, County, and $balance

Example: 
**Eligible Now**
Theft in the Second Degree (CONVICTED) Charged May 8, 2014

**Eligible Now if Balance Paid**
Multnomah 15CR15555 - $400
Theft in the Second Degree (CONVICTED) Charged May 8, 2014
Theft in the Second Degree (Dismissed) Charged May 8, 2014
Washington 15CR25555 - $410
Theft in the Second Degree (CONVICTED) Charged May 8, 2010

**Eligible July 15, 2025**
Theft in the Second Degree (CONVICTED) Charged May 8, 2014

**Eligible July 15, 2025 if Balance Paid**
Washington 15CR35555 - $420
Theft in the Second Degree (CONVICTED) Charged May 8, 2018

### This task is done when:
 -
 -

**Comment by wittejm** [comment]
Completed with #1531
