### ISSUE TITLE
Update all rules references to match legal changes

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#1535]
Some changes in the law going into effect January 1st may have changed the relevant subsections for the charge type eligibility rules. These rules need to be updated in each charge type's source file in `models/charge_types`

 The text diff for the updated law is here:

[SB 397.pdf](https://github.com/codeforpdx/recordexpungPDX/files/6896231/SB.397.pdf)

Charge types are independent of one another so multiple contributors can work on this in parallel. As contributors check/update these, please check them off in this list:

- [x] Civil Offense
- [x] Criminal Forfeiture
- [x] Dismissed Criminal Charge
- [x] DUII
- [x] Diverted DUII
- [x] FareViolation
- [x] Felony Class A
- [x] Felony Class B
- [x] Felony Class C
- [x] Juvenile
- [x] Marijuana Eligible
- [x] Marijuana Eligible (Below age 21)
- [x] Marijuana Violation
- [x] Marijuana Ineligible
- [x] Misdemeanor Class A
- [x] Misdemeanor Class B or C
- [x] Parking Ticket
- [ ] Person Felony Class B
- [ ] Reduced to Violation
- [ ] Severe Charge
- [ ] Sex Crime
- [ ] Young Offender Sex Crime, Needs More Analysis
- [ ] Young Offender Sex Crime, Ineligible
- [ ] Subsection 6
- [x] Traffic Offense
- [x] Traffic Violation
- [x] Unclassified
- [x] Violation

**Comment by KentShikama** [comment]
Done with https://github.com/codeforpdx/recordexpungPDX/pull/1533 and various follow ups.
