### ISSUE TITLE
July survey email

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#1538]
@michaelzhang43 @wittejm @KentShikama anything you want to include in this month's email?

**Comment by wittejm** [comment]
I'm guessing no; while the new version is still being debugged and patched we can avoid publicizing it, but probably share it next month. @michaelzhang43 ?

**Comment by michaelzhang43** [comment]
Sorry for late response - clinics have been a shitshow wrt updating forms. 

Nothing we need to include in this month's email. But yes, let's share as soon as we debug.
