### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by giosce** [codeforpdx/recordexpungPDX#1555]
Hi,
this is a great project!
I'm working on making https://projects.brigade.network/ more relevant.
For this reason I'm reaching out to Code for America Brigades projects to ask/recommend to have some tags (topics) in your repos.
This project falls under Priority Action Areas, "CREATING PATHWAYS TO RECORD CLEARANCE", I'm not dictating how to tags the projects, one idea could be paa-record-clearance or just record-clearance or something you find relevant (right now you don't have any topic).
If you'd like to discuss further you can write me at giosce@verizon.net, I hope to list your project soon!

**Comment by KentShikama** [comment]
Thank you for the notice! We've added some GitHub topics.
