### ISSUE TITLE
Upgrade frontend npm dependencies

### ISSUE THREAD

**Issue by monocle** [codeforpdx/recordexpungPDX#1634]
Per the Slack discussion, I'll start working on this.

- [x] switch from node-sass (deprecated) to dart-sass (current primary implementation)
- [ ] upgrade all dependencies to current
- [x] switch out of moment.js per [their recommendation](https://momentjs.com/docs/#/-project-status/)

Notes:
[Reach UI is not currrently maintained](https://github.com/reach/reach-ui/issues/972). This is blocking from updating React to 18x. The Reach UI team mentions alternative:

- [Radix UI](https://www.radix-ui.com/)
- [Ariakit](https://github.com/ariakit/ariakit)
- [Reac Aria](https://react-spectrum.adobe.com/react-aria/)

It would probably be better for long term maintenance just to use plain HTML/CSS.

**Comment by KentShikama** [comment]
@monocle Nice! Feel free to submit PRs one bullet at a time (or even in more granular chunks). My guess is swapping moment.js to dayjs would be a nice chunk.

**Comment by monocle** [comment]
In trying to upgrade the dependencies, I've run into a lot of little fixes. [Here is my fork](https://github.com/monocle/recordexpungPDX/commits/update-frontend-deps) with the commits so far. The commits are pretty atomic. I could rebase if that would be better.

Questions:

- I'm using Prettier through VS Code and some of the commits have whitespace changes due to that. Is there some configuration that I should set on my local machine to avoid those whitespace changes?
- The changes are building up and other things still need to be upgraded. Should I just keep going in the same branch? Or should we try to merge the other non-upgrade related commits separately?
- I've noticed some [minor content issues](https://github.com/monocle/recordexpungPDX/issues/3) that I have not fixed yet. Should we fix those and move them into production before the other things?
-  To avoid spamming you and the Slack channel, I'm planning to tee up things, including issues, in my fork. Let me know if you'd like to be more in the loop with anything and, if so, what the prefer communication method would be.

**Comment by KentShikama** [comment]
I realized I missed this post. There should be a husky hook in this repository that you can run or make into a git commit hook. In general, smaller chunks are preferable at first. Feel free to reach out wherever. Tagging me will make it easier for me to follow @monocle.

**Comment by monocle** [comment]
@KentShikama Would it be okay to change our node image to 18-bullseye? I think we need to upgrade node for the other package upgrades. Also, I'm trying to use VSCode's dev container feature to access the node_modules (ex. prettier) within the Docker container and they have a node 18 bullseye version for their typescript-node image.

**Comment by KentShikama** [comment]
Sure! @monocle
