### ISSUE TITLE
Expungement # update

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#1641]
On front page, update "Over 5,600 analyses delivered as of January 2022" to "Over 10,000 analyses delivered as of January 2023"

**Comment by monocle** [comment]
Let's combine this with #1640 and these other content issues that I've been keeping track of on my fork https://github.com/monocle/recordexpungPDX/issues/3.

**Comment by KentShikama** [comment]
@monocle Did @michaelzhang43 tell you about https://recordsponge.com/access_packet/ and the password?
