### ISSUE TITLE
Bounding box on cases in expanded analysis section

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#1643]
Put a bounding box on cases in expanded analysis section. This will make the cases more visibly grouped

**Comment by monocle** [comment]
@michaelzhang43  Here's the current state on my Mac (demo data):

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/120387970/212483954-39d64f38-1926-48f6-a72f-fad024ccbf65.png">

This is with a black border:

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/120387970/212484004-c697c7fe-2573-44d0-89f6-b6c086ceb846.png">

This adds a darker background color, if you think that's needed:

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/120387970/212484093-3afc0f83-c880-45e4-af40-033a275b4831.png">


The PCC monitors seemed to have contrast than I probably see on my computer. I'm sure the lighting there also is brighter than my home. Let me know what you think. I think for deployment, maybe we push this and other changes to the dev server, and I'll plan to visit again next Friday to see what people think.

**Comment by hmarcks** [comment]
@michaelzhang43 @monocle I suggest we only update the background color and not add the black border because it's a bit jarring with the rest of the design and feels unintentional. Here's what just the background update would look like:
<img width="2256" alt="contrast" src="https://user-images.githubusercontent.com/6887982/212525776-7afa8ea1-8361-49e7-9c31-18a9899ebdd4.png">

**Comment by monocle** [comment]
@hmarcks Thanks for taking a look at that! I'll remove the border and use #E6E9EF.

I noticed that that `blue-gray-2` color is also being used with different elements:

* Alias button
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/120387970/212559850-e82d429b-e659-4a10-94eb-4dad07a82f35.png">

* Manual
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/120387970/212559703-eb07147c-0e96-4676-8a24-76844c90ef04.png">


Should we update the global `blue-gray-2` to keep everything consistent or just create a new color for the issue at hand (Case display)?

**Comment by hmarcks** [comment]
Good spot @monocle , hmm, I know it's subtle but I think if the buttons are updated as well then they start to look a bit too much like they are disabled because they loose some contrast with the text inside them.

So I think we should just create a new `blue-gray-3`
