### ISSUE TITLE
Provide alternative search summary display

### ISSUE THREAD

**Issue by monocle** [codeforpdx/recordexpungPDX#1652]
On visiting last Friday, @michaelzhang43 thought it would be helpful to have a search summary display that was sorted by case. It would be a condensed form of the displayed cases.

## Current Search Summary
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/120387970/212758482-855ce7d1-99c8-4aaa-b0b5-f043a6eab5f1.png">

## More info needed
@michaelzhang43 

* Do we want to have the heading to be clickable to toggle the displays? Ex:
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/120387970/212760398-7554ba6d-0a8a-4308-b33a-beb8541231b9.png">

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/120387970/212760463-a0696b58-8129-45a8-a835-24037420f0a7.png">

* What fields do we want displayed? Something like this?

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/120387970/212962754-6bd37407-ad68-4255-9a94-2c591ec136e7.png">

The top line has: case date, case number. Clicking on the case number scrolls down to the case details.

The changes can be seen here
https://monocle.github.io/recordexpungPDX/

Just navigate to the demo.

(Note some things, like the icons, are broken due to how I'm hosting it. But at least you can see and click things as a webpage.)

**Comment by monocle** [comment]
Related to this component, currently when the search results come up empty, the `Generate Paperwork` button is still present. If the user clicks the button, an error message is displayed:

![image](https://user-images.githubusercontent.com/120387970/213010213-b25df524-c5ee-41c2-92bc-64e826ac06d5.png)

Since I'm refactoring this component, should we just hide the button when the search results are empty?

**Comment by KentShikama** [comment]
Note that you can manually add cases and so if there is no search results but a case is manually added, then we still should show the paperwork generation button.

**Comment by hmarcks** [comment]
I think both options should be visible, maybe something like this:
<img width="1039" alt="Screenshot 2023-01-17 at 11 10 46 PM" src="https://user-images.githubusercontent.com/6887982/213089849-27086d50-6e7b-4b93-be5e-5f3ba5d7cc11.png">

**Comment by monocle** [comment]
Here's where I'm at now with the new display. 

* John Common demo data:

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/120387970/214409269-719a4837-c818-4d63-9976-ef2b8a416d24.png">

* Multiple Charges demo data

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/120387970/214409503-ec97795d-b70b-4561-9b79-2d08376a6f96.png">

The date I'm displaying is the top level `date` field for `CaseData`:

https://github.com/codeforpdx/recordexpungPDX/blob/77cccb450e7ce11b80922c950ea441846891c127/src/frontend/src/components/RecordSearch/Record/types.ts#L20-L30

@KentShikama is this the arrest date? (@michaelzhang43 asked me, but I couldn't figure that out.)

@hmarcks What are your thoughts on the eligibility "badges"

<img width="227" alt="image" src="https://user-images.githubusercontent.com/120387970/214412440-78756148-2f10-49d3-a6b6-934dcd4a6693.png">

especially since #1656 will be adding more eligibility types that are longer. This is the styling I'm using

<img width="824" alt="image" src="https://user-images.githubusercontent.com/120387970/214413302-d2e6d998-56b4-4ce3-ba3d-5c5c9a577603.png">

If you know how to get rid of the extra space on the right side of the blue badge, please let me know.

**Comment by KentShikama** [comment]
@monocle It might be worth studying the scraper a bit. And the OECI site - as in what the raw display looks like (@michaelzhang43 can help you there). The arrest date is attached to the charge. The case date is separate. See https://github.com/codeforpdx/recordexpungPDX/blob/77cccb450e7ce11b80922c950ea441846891c127/src/backend/expungeservice/crawler/crawler.py#L138 for the relevant line.

**Comment by hmarcks** [comment]
@monocle I think the badges look good. One thing to consider is maybe making "Eligible now if balance paid" green as well, thanks!
