### ISSUE TITLE
Add new Partners to the landing page

### ISSUE THREAD

**Issue by monocle** [codeforpdx/recordexpungPDX#1660]
@michaelzhang43 had some extra partners to add. This would be an easy update and would just need the info to be added to currentPartners.ts

https://github.com/codeforpdx/recordexpungPDX/blob/77cccb450e7ce11b80922c950ea441846891c127/src/frontend/src/components/PartnerTable/currentPartners.ts#L1-L15

**Comment by monocle** [comment]
Hi @michaelzhang43. If there are still more partners to add to the website, if you can get me the info, I can work on that.

**Comment by michaelzhang43** [comment]
Hey Henry -

No need to add at this time. It's pretty low priority and our intention was mostly to just make an easy update for new contributors

**Comment by brennanbutler01** [comment]
@michaelzhang43 i'm super interested in starting to contribute and would be happy to make this my first go. is there anyway I could have the partners that need added so I can make a pr please?

**Comment by michaelzhang43** [comment]
Thanks Brennan! 
Please add the first three entries from the attached. 
Additionally, please delete the "Court Fees" section entirely - court fees have been eliminated by statute. 

[Compiled Sheet - RS users.pdf](https://github.com/codeforpdx/recordexpungPDX/files/11655020/Compiled.Sheet.-.RS.users.pdf)

Also, please let me know your email - would love to invite you to upcoming recordsponge events

**Comment by brennanbutler01** [comment]
@michaelzhang43  thanks for the quick response - brennanbutler01@gmail.com is my best email address.
