### ISSUE TITLE
Add Arrest Date information to all expungement forms

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#1661]
From Michael Zhang: I received word from our partners in Douglas County that the court there is requiring the Arrest Information to be filled out on ALL expungement paperwork. 

Currently, Arrest Information for a case is not filled out if there is at least one Conviction on the case (which is correct, if one actually reads the forms). However, the Douglas County isn't accepting the forms unless the Arrest information is also filled out. Adding this information on ALL forms should not present any issues for other counties since the information is extraneous but doesn't detract from the request to also expunge the Convictions. 

Here is the ask:
For ALL case paperwork, provide the Date(s) of Arrest in the "Date of arrest" line, and check the appropriate box corresponding to "no accusatory instrument" or "accusatory instrument was filed" - basically, the information that goes here (Arresting Agency doesn't need to be provided). 

<img width="601" alt="Screen Shot 2023-01-27 at 5 40 36 PM" src="https://user-images.githubusercontent.com/59623009/215219744-d7575cca-8ea2-4c36-b391-128ef2ca8124.png">

Thank you

### This task is done when:
 -
 -

**Comment by monocle** [comment]
@michaelzhang43  For the check boxes, we're not changing how RecordSponge would currently check those boxes correct?

**Comment by monocle** [comment]
@michaelzhang43 This looks to be related to Request 1 in #1673. Just need some clarity on how the behavior changes from how it does it currently.
