### ISSUE TITLE
Remove `#paybalances` links

### ISSUE THREAD

**Issue by monocle** [codeforpdx/recordexpungPDX#1662]
There are some links that go to `/manual#paybalances`, however, this section of the manual was removed in commit https://github.com/codeforpdx/recordexpungPDX/commit/adf9ceb1babf19bd364a7239ad805c2a6f48962f .

Unless there should be new instructions on outstanding balances, I'll remove these links from the website.

**Comment by hmarcks** [comment]
Nice find @monocle , maybe check with @michaelzhang43 if we want new instructions
