### ISSUE TITLE
Typo in "manual" page

### ISSUE THREAD

**Issue by devrisby** [codeforpdx/recordexpungPDX#1663]
I spotted 2 minor typos on the [manual page](https://recordsponge.com/manual):

![image](https://user-images.githubusercontent.com/118779687/216723803-39d580fb-6cc5-4ae7-8f09-51c87ffc450a.png)

I believe the text should be:

> Every State has different expungement rules. [Recent changes](https://olis.oregonlegislature.gov/liz/2021R1/Measures/Overview/SB397) to Oregon's expungement law make more types of criminal records eligible than ever before, and on a much faster timeline. Nevertheless, the complexity of the expungement statutes, ORS [137.225](https://www.oregonlaws.org/ors/137.225) and [137.226](https://www.oregonlaws.org/ors/137.226) pose a significant barrier for people seeking expungements on their own.

**Comment by monocle** [comment]
The "recent changes" was fixed with the last Matt's last PR, but is still waiting to be deployed.
