### ISSUE TITLE
Clackamas County 

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#1665]
After a Motion to expungement a case is accepted, the court signs an Order that has the expungement take legal effect. Clackamas County is apparently requiring people to provide their own Orders using the template below. 

For all Clackamas County cases (and only Clackamas County cases), include as part of each Motion paperwork, a corresponding filled out Order. 

Only these slots need to be filled out:
- Replace NAME with Defendant Name as it appears in the name of the case. 
- Full Name
- Date of Birth
- SID Number
- Case No
- Charge(s)
- Arrest Date
- Disposition

In particular, Agency and FBI number do not need to be filled out. SID Number is OK if not filled out

[Expungement Order Template.docx](https://github.com/codeforpdx/recordexpungPDX/files/10677030/Expungement.Order.Template.docx)

**Comment by monocle** [comment]
@michaelzhang43 This form doesn't provide a lot of room for the charge names. Okay to use two rows for one charge? Also, is there a practical maximum number of charges that a case can have?

<img width="819" alt="image" src="https://user-images.githubusercontent.com/120387970/225373840-d70f7184-956f-4b2f-b27a-a5ae9b54bf20.png">

<img width="910" alt="image" src="https://user-images.githubusercontent.com/120387970/225374558-4f7e78df-e54b-4472-aec4-f5fdeb77a2cd.png">

**Comment by michaelzhang43** [comment]
Unforunately the charge list sometimes gets really lengthy, like upwards of 30 charges. Usually it's less than 10. Still, I'd like to keep the charges in one cell even if it decreases readability. It doesn't really need to be actually read by anyone for practical purposes; more important that the cell contains the correct info.

**Comment by monocle** [comment]
@michaelzhang43 There are issues with the different PDF renderers (Chrome browser vs Adobe Reader vs. Apple) that makes knowing what actually fits in a form field unpredictable.

From what I saw with the other order forms (Oregon, Multnomah), we couldn't fit 30 charges on those lines. What if we do this for the Clackamas form:

The first two charges go on page one:
<img width="965" alt="image" src="https://user-images.githubusercontent.com/120387970/225686024-ebf539bf-a7c0-413b-b376-9a89b7b1e652.png">

After that, the other charges have to go on the second page, so we might as well put them in the white space:
<img width="862" alt="image" src="https://user-images.githubusercontent.com/120387970/225685542-13aa988d-415f-46b9-a7af-5b37616df4f8.png">

**Comment by michaelzhang43** [comment]
Yes, let's do that
