### ISSUE TITLE
Implementing an "Expanded View" 

### ISSUE THREAD

**Issue by monocle** [codeforpdx/recordexpungPDX#1669]
This is take two on the work that I've been doing. This feature is to have an "expanded" view that is targeted for the more complicated and longer records. 

For these cases it can be hard to navigate the case details and a lot of scrolling is needed. Here is a video of the proposed changes:

https://youtu.be/lA06rtEF70M

Some points:

* Try to keep the default view the same for less complicated cases and for people who are happy with that view. For this, the only difference is the extra `View Options` section.
* I was told that some of the volunteers will print the screen to give the client a more inclusive summary of all charges. There was a concern about having too much color would use too much toner ink. This is why the `Show Color` checkbox is there. A better solution could be implemented in the future.
* `Hidden Traffic Charges` checkboxes for records with a lot charges that may not be of interest. 
* Shortened labels to take up less screen space. 
* A sidebar case/charge navigator to help prevent being lost.
* Download buttons at the bottom of the screen to avoid needing to scroll back up.
* Abbreviated assumptions and form filling information.
* No page navigation to fill out client information.
* Reset the search when done working with the client.

Appreciate any feedback here or on Slack.

@michaelzhang43 If we are interested in going forward with this, maybe we could share the YouTube link to get some feedback from the app users?

**Comment by michaelzhang43** [comment]
This is fantastic! Will send to group now for feeback. Missing you at the clinic this week!
