### ISSUE TITLE
Birth year should default to an empty string

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#167]
## Description
Birth year is not present on all case files and we're seeing some failures here: https://github.com/codeforpdx/recordexpungPDX/blob/master/src/backend/expungeservice/models/case.py#L7 

Need to update this so that Birth year defaults to an empty string when it is not present.

### This task is done when:
 - Create test case to expose bug (probably two tests: unit and functional)
 - Implement fix

**Comment by hmarcks** [comment]
@NickSchimek does this affect searching for cases if we require date of birth?

For example, if a person has a single case with an empty birth year, would you not be able to find that because we require date of birth?

Or is the date of birth stored separately from the cases?

**Comment by NickSchimek** [comment]
@hmarcks That's a good question... One I don't have an answer for. Do you want to ask Michael about it?

**Comment by hmarcks** [comment]
@NickSchimek are we only looking at this birth_year attribute on the cases when performing a search?

Looks like Michael didn't get transferred to this github project, I'll ask via slack if he ever searches or will anticipate searching without date of birth.

**Comment by NickSchimek** [comment]
I'm not quire sure I understand this. My initial answer would be I don't know how OJCIN handles the search when it receives a birth_year argument.
> are we only looking at this birth_year attribute on the cases when performing a search?

**Comment by NickSchimek** [comment]
The birth_year parameter on the cases class is what is from the information being parsed on the OJCIN website. It doesn't have anything to do with actually performing a search. It is simply the data returned to us after a search. @hmarcks Not sure if that better answers the above question

**Comment by hmarcks** [comment]
Ah, I see! Thanks @NickSchimek , I was confusing this with search
