### ISSUE TITLE
NEW FORMS

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#1672]
Oregon Judicial Department has issued new forms that all new expungements have to use. Pretty annoying because it's almost identical to the old form, but some counties have already told us they're not going to accept the old form starting in March. But also hopefully not difficult since the new form is essentially the same as the old form. 

Please update the non-Multnomah County forms to the one attached, (and keep using the Multnomah County form for Multnomah County cases for now - no word yet on Multnomah County's procedure). 
[new CriminalSetAside_AdultCases.pdf](https://github.com/codeforpdx/recordexpungPDX/files/10799240/new.CriminalSetAside_AdultCases.pdf)

**Comment by monocle** [comment]
@KentShikama Let me know if/how I can help.

I haven't done any PDF work before. I see `pdfrw` is being used to fill the forms out. Here are things I noticed.

I put the new form in to replace the existing "oregon.pdf" form and it give this error


<img width="838" alt="image" src="https://user-images.githubusercontent.com/120387970/220707907-d877f126-6648-4451-8456-891882b51d9b.png">


***Does the PDF need to be fillable?***
From what I can tell, the form Michael attached isn't fillable. Have you guys been manually converting the PDFs into fillable forms? If so, how are you doing that?

Here are the differences in the forms that I can see:
### Existing form used by RecordSponge:
* Plaintiff is filled out with "State of Oregon"
<img width="407" alt="image" src="https://user-images.githubusercontent.com/120387970/220709125-979fddd2-4a2f-4c25-abc1-8101d005a022.png">
* Two prechecked boxes here 
<img width="799" alt="image" src="https://user-images.githubusercontent.com/120387970/220709308-129c50e6-346d-4981-a67f-74a1ca029689.png">

### New form
* Motion is broken out into subsections 
<img width="750" alt="image" src="https://user-images.githubusercontent.com/120387970/220709633-2be15a38-da92-4c59-b1d8-e1f2687382da.png">
* New line "If no arrest date, date of citation, booking, or incident"
<img width="741" alt="image" src="https://user-images.githubusercontent.com/120387970/220709828-0bb14866-c6b1-4937-bb49-72db311ec340.png">

**Comment by KentShikama** [comment]
@monocle In short, I've been using Adobe Acrobat. We create text fields and name them in a way that the program expects. I've just been paying for the subscription when needed but I'm sure @michaelzhang43 would be happy to reimburse you for the monthly cost.

**Comment by monocle** [comment]
@KentShikama @michaelzhang43 
The new form has a new field "If no arrest date, date of citation, booking, or incident"
<img width="722" alt="image" src="https://user-images.githubusercontent.com/120387970/221254823-783ed766-16d5-4b39-a8ab-9091fdd1a49a.png">

Would we ever put anything on this line? I'm not seeing that we are capturing this information in the app.

**Comment by michaelzhang43** [comment]
Got it - 

No, we don't need to ever put anything in that line. Those would be for minor citations that don't make it into OECI anyways

**Comment by wittejm** [comment]
Hey @monocle are you currently working on this or #1673 ? If not I can pick them up since courts will start taking the new paperwork soon.

**Comment by monocle** [comment]
@wittejm I opened up a PR this weekend https://github.com/codeforpdx/recordexpungPDX/pull/1675

I found some problems displaying check marks last night. I have a solution that I'm testing now. Hoping to update the PR here this afternoon.

**Comment by wittejm** [comment]
Ooh thanks, sorry I missed that

**Comment by monocle** [comment]
@wittejm I've been doing. I've been trying different approaches to get the check marks to show up consistently. However, I keep running into new problems with what I'm doing. If you have time, maybe it's best that jump in on it disregarding the work I've done. I can submit later if I can get things to work.

**Comment by wittejm** [comment]
Shoot, I offered too soon. I'm having trouble getting a dev environment working since the new Mac hardware doesn't support python very well yet. I'm sorry! But if I can help out by pairing with you on your own work, let me know!

**Comment by monocle** [comment]
@wittejm I just submitted a PR with the changes I've been using to get the backend Docker to work on Apple silicon. https://github.com/codeforpdx/recordexpungPDX/pull/1676 The PR is failing the backend check because of unrelated tests that are failing due to some being tied to today's date. So you could just pull those files from my fork it you want.

I think the changes I committed yesterday will work. If you are able to get your dev environment to work and can test the changes on your end, that would be greatly appreciated!

**Comment by monocle** [comment]
@wittejm @KentShikama @michaelzhang43 
As far as I can tell, things are working appropriately with the new code in this PR. Here are the generated forms use John Common demo data. Please disregard the county name for these test files. The way RecordSponge picks the forms should be unchanged but should be tested in the dev/prod servers. 

* New Oregon PDF
[COMMON A NAME_120000_baker_oregon.pdf](https://github.com/codeforpdx/recordexpungPDX/files/10855952/COMMON.A.NAME_120000_baker_oregon.pdf)
[COMMON NAME_110000_baker_oregon.pdf](https://github.com/codeforpdx/recordexpungPDX/files/10855953/COMMON.NAME_110000_baker_oregon.pdf)
[COMMON NAME_200000_benton_oregon.pdf](https://github.com/codeforpdx/recordexpungPDX/files/10855954/COMMON.NAME_200000_benton_oregon.pdf)

* New Oregon PDF with old arrest order 
[COMMON NAME_200000_benton_arrest.pdf](https://github.com/codeforpdx/recordexpungPDX/files/10855957/COMMON.NAME_200000_benton_arrest.pdf)

* New Oregon PDF with old conviction order
[COMMON A NAME_120000_baker_conviction.pdf](https://github.com/codeforpdx/recordexpungPDX/files/10855959/COMMON.A.NAME_120000_baker_conviction.pdf)

* Old Mutnomah with conviction PDF (Didn't touch it. Just making sure it works still.)
[COMMON A NAME_120000_baker_multn_conviction.pdf](https://github.com/codeforpdx/recordexpungPDX/files/10855963/COMMON.A.NAME_120000_baker_multn_conviction.pdf)

* Old Mutnomah with arrest PDF (Didn't touch it. Just making sure it works still.)
[COMMON NAME_200000_benton_multn_arrest.pdf](https://github.com/codeforpdx/recordexpungPDX/files/10855965/COMMON.NAME_200000_benton_multn_arrest.pdf)

* Old OSP PDF (Didn't touch it. Just making sure it works still.)
[OSP_Form_oregon.pdf](https://github.com/codeforpdx/recordexpungPDX/files/10855969/OSP_Form_oregon.pdf)

**Comment by michaelzhang43** [comment]
Awesome - thank you!

Could you put it into dev so I can test it out?

**Comment by michaelzhang43** [comment]
Just tested out - looks fantastic, including the additional view options. 

Could you please push this to prod?
