### ISSUE TITLE
Add "the older" marijuana ineligible statute #'s that were revised

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#169]
## Description
We're currently checking statute numbers for marijuana charges, however there are some statutes that are no longer used that need to be added to the list since statute numbers do not get updated on the OJCIN database when they're revised.

Need to get list from Michael or research on https://www.oregonlaws.org

### This task is done when:
 - Add unit tests
 - Add remaining statute numbers here: https://github.com/codeforpdx/recordexpungPDX/blob/master/src/backend/expungeservice/models/charge.py#L49

**Comment by KentShikama** [comment]
@michaelzhang43 Do you know whether the latest version of https://dev.recordsponge.com/ has resolved this?

**Comment by KentShikama** [comment]
Or to put it differently, is this issue related to the conversation we had at https://github.com/codeforpdx/recordexpungPDX/issues/1259?

**Comment by NickSchimek** [comment]
It looks like its related @KentShikama. It would probably be good to do an audit to see if all the available statutes have been captured.

**Comment by KentShikama** [comment]
Resolved with @michaelzhang43 today on our weekly meeting.
