### ISSUE TITLE
Generate Paperwork button bug

### ISSUE THREAD

**Issue by monocle** [codeforpdx/recordexpungPDX#1696]
The Generate Paperwork button throws a console error in certain cases.

To reproduce in production, search for 'single conviction' in the demo.
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/120387970/235790507-d6b6d074-8411-4154-a216-d94586fc2536.png">

In dev, here is more info
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/120387970/235791107-460ac2dc-53a1-42ae-89f6-2c7dc9469c27.png">

@wittejm I think this might be related to some of the recent changes?

**Comment by wittejm** [comment]
PR'd a fix, thanks for reporting this.
