### ISSUE TITLE
Hosting Docker images on Docker Hub

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#184]
We now have a Docker Hub account at 
https://hub.docker.com/u/recordexpungpdx

It's currently an "individual" account tied to my primary email (wittejm@gmail.com) . It's possible to change the primary email address and also upgrade to an "organization" account whose pricing begins at $7/month. 

Images can be pulled from the Dockerhub with the identifier:
[username]/[repository]:[tag]

For example, our only image currently hosted on the Hub is:
 
recordexpungpdx/recordexpungpdx:expungeservicebase

It might be more appropriate to host our project images at an account shared by all Code for PDX projects while maintaining the repository name for this project.  

I don't think that hosting the other Docker images for our stack is currently a priority, because the images are built from scratch in the dev environment and for deployment to prod. The expungeservicebase image is available to speed up project build time, because this docker image is updated infrequently.

### This task is done when:
 - The primary email account is changed to one on the codeforpdx.org domain, such as recordexpungpdx@codeforpdx.org or similar.
 - Information related to the docker profile and management of its repositories is transferred to project documentation (the wiki and/or readme files) 
 - A policy on hosting the project docker images on the hub is decided.

**Comment by wittejm** [comment]
pinging @NickSchimek and @erikjasso to get their opinions. It's not as much of an "action item" as other issues so it might make sense for me to move this info to some other place in the documentation (like the wiki, maybe?)

**Comment by NickSchimek** [comment]
This would be something to ask @htharker42 about

**Comment by ForrestLonganecker** [comment]
@NickSchimek Does this relate to the paperwork that you were speaking about at the last meetup? @wittejm

**Comment by NickSchimek** [comment]
@ForrestLonganecker and @wittejm Remind me to discuss this at the next meetup.
