### ISSUE TITLE
Remove authentication test from database

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#186]
## Description

I'm not sure this is a very useful test, and it forces developers to set a password on the development database that is not 'wrongpassword', and we're basically testing the database authentication system which is already under test by the vendor.

https://github.com/codeforpdx/recordexpungPDX/blob/master/src/backend/tests/database/test_database.py#L40

@wittejm What do you think about removing this test so that developers aren't forced to setup a password (that is not 'wrongpassword') on their dev machines?

**Comment by wittejm** [comment]
Removing the test case makes sense. I think I sometimes go a little far with trivial tests :/
