### ISSUE TITLE
Expand install instructions to include docker stack

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#187]
Building and deploying the docker stack is not mentioned in the Readme's install instructions. Also the test cases that hit the database need a .env file correctly in place to obtain the database connection information.

Related to issue #118 which will refactor how to set environment variables to configure the database.

### This task is done when:
 - instructions to install docker and build the docker stack, and to set up a local .env file, added to the readme

**Comment by wittejm** [comment]
The main Readme will mostly just need to point users to the docker.md file:
https://github.com/codeforpdx/recordexpungPDX/blob/master/doc/docker.md

Setting up the .env file currently requires a user to make a copy of .env.example that is named .env.

**Comment by wittejm** [comment]
I just realized these steps could just be added to the `make install` target. It could even prompt the user to create their database password and then write the new .env file into place. @NickSchimek what do you think of this?

**Comment by NickSchimek** [comment]
Yeah, that is good idea. I would create a separate `make setup` task to create the database and run the script. I think installing the dependencies and setting up the database should be separate commands. Regarding the password, I generally don't like the password requirement, obviously it should have a password in production, as I just created a ticket asking you about it. https://github.com/codeforpdx/recordexpungPDX/issues/186 Let me know what you think.

**Comment by wittejm** [comment]
So the database is only installed virtually as part of the docker stack and in my opinion the full docker stack should be running in any dev's setup. Similarly a test script will run the set of test cases within the docker stack, when issue #174 is completed. So in that case I don't see a reason to have a separate make target for this since they are both just steps for installing the dev environment.

I'm fine with keeping the database password setup essentially as it is now with a default password. I think having a password at all is good to keep the setup similar to what we'll see in prod, though the specifics of prod itself is obviously a step we can worry about later. But using just a default password for the dev environment so that the user doesn't need to think about it sounds good to me.

**Comment by NickSchimek** [comment]
yeah, there are a lot of good reasons to use docker in development too. This is something we had discussed a while back, but at that time we weren't close to having a docker setup. It is definitely something we can discuss again at the next meeting as I'd like to give everyone a chance to express their opinion on using docker for development.

**Comment by wittejm** [comment]
I added a few missing steps to the install instructions, realized with help from @ash-tamraz that you need to configure docker [to not require sudo,](https://docs.docker.com/install/linux/linux-postinstall/) because sudo messes with the way pipenv pathing works. I don't see any similar instructions for Mac, so I don't know if this step is also required there. Any feedback on whether folks (both on Mac and Linux) successfully get docker working following these instructions is much appreciated!

**Comment by wittejm** [comment]
Pretty sure the readme files have been all updated with this info, closing issue.
