### ISSUE TITLE
Sync parser and analyzer data classes

### ISSUE THREAD

**Issue by a-ilango** [codeforpdx/recordexpungPDX#25]
The parser has some data classes (e.g. Case) which are also duplicated in analyzer. Sync the two so that analyzer can understand objects generated by parser.

OR

Have the main app convert from one to another. The analyzer has predefined enums defined for some of the data types which basically stems from the expunge analysis flowchart while the parser objects are likely to have strings as types mostly.

Child of #9

**Comment by maxkwallace** [comment]
@cameron2018 Hey! How is this going? Did you have finished work in your fork you wanted to merge in? This issue hasn't been updated in a while so if I don't hear back I'll go ahead and unassign this from you and open it up to someone else to work on.

**Comment by NickSchimek** [comment]
This is not needed. The analyzer uses the python objects created by the crawler.
