### ISSUE TITLE
Set default values on disposition fields to a string

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#259]
## Description
This is mainly being done to match the setup on the CLI. It can also improve the readability on the front end. The disposition fields are currently set to None which may imply that there is no disposition rather than the disposition was not found since some charges that have been disposed do not explicitly set a disposition

### This task is done when:
 - Update tests in `test_crawler.py`
 - Change default value for result and date fields

**Comment by wittejm** [comment]
disposition behavior is cleaned up now
