### ISSUE TITLE
Implement remaining rules in analyzer

### ISSUE THREAD

**Issue by a-ilango** [codeforpdx/recordexpungPDX#26]
The analyzer has a few rules setup. Implement the rest.

Child of #9

**Comment by cameron2018** [comment]
i think ive done them all , but there is still some things that need to be worked out, its in my rapsheetanalyzer branch on my fork of the repo

**Comment by cameron2018** [comment]
my functions is_crime_marijuana_list and is_charge_PCS_schedule_1 dont work yet

**Comment by maxkwallace** [comment]
@cameron2018 Hey Cameron! Just wanted to check in on this issue and see how things are going. Are there changes you still wanted to integrate into this repo?

**Comment by maxkwallace** [comment]
@cameron2018 Hey there-- haven't heard from you since my last comment two weeks ago so I'm going to unassign this from you and open it up for other people to work on. Thanks!

**Comment by maxkwallace** [comment]
This task isn't assigned to anyone so I'm assuming no one is working on it, and I'm going to move it back to "Ready to Work". 

If you're working on it please assign yourself and move it back to "In Progress" in our Project.

**Comment by NickSchimek** [comment]
This is no longer needed.
