### ISSUE TITLE
Look into speeding up the search function

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#260]
## Description
Currently the search function iterates through all cases found and requests case info sequentially from the OJCIN site. Typically this does not take too long, but for some instances it can take up to 4 to 6 seconds depending on the number of cases returned from the search.  We could possibly run these requests in parallel using threads. Here is a good article to get started: https://www.shanelynn.ie/using-python-threading-for-multiple-results-queue/

Creating thread objects docs: https://docs.python.org/3/library/threading.html#thread-objects

### This task is done when:
 -
 -

**Comment by keppel2** [comment]
Can we work to get bulk API access?
