### ISSUE TITLE
Append errors to record object

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#261]
## Description
Currently any errors that are recorded within the expunger are added to the error attribute on the expunger. Now that we have a record object these should be appended to error attribute on the record object. 

This is needed because the search endpoint will return a jsonified record object to the frontend and whatever data is left in the expunger will not be sent. After this the expunger should only have a private attributes. 

### This task is done when:
 - Move current test for error field from expunger test file to the record test file
 - The error field is moved to the record object

**Comment by erikjasso** [comment]
I think having an "errors" object in the JSON is fine given the response includes the correct 4xx and 5xx HTTP status code and standard error message. Flask [make_response](https://flask.palletsprojects.com/en/1.1.x/api/#flask.make_response) is one way to do this

If an error occurs is there a record to return?

BTW Flask has a decorator `@application.errorhandler` for handling errors. One way it's used is by intercepting calls to `Flask.abort()`. See [this page](https://flask.palletsprojects.com/en/1.1.x/errorhandling/) for more info. One way I've used `abort` and `errorhandler` together is to trap the error in `errorhandler` and return a JSON object w/`make_response`

I don't know if we've talked about how the Flask application should handle errors. Maybe a topic for tonight?

**Comment by NickSchimek** [comment]
Sorry I wasn't at the last meeting. I will be at all of the next meetings for the foreseeable future. Was this discussed at all? This issue would be more of an errors field for the record object that would list any potential/possible issues with the returned data.  I believe what you are referring to is needed as well for the JSON response given there is an issue with the request.  I suppose we could combine them, However I'm not sure that is "best practice".  Perhaps we can discuss more in person?
