### ISSUE TITLE
Scripts for dumping and restoring the database

### ISSUE THREAD

**Issue by erikjasso** [codeforpdx/recordexpungPDX#299]
We will periodically want to sync our local database w/the production database. PostgreSQL provides two utilities, `pg_dump` and `psql` that we can use to do this.

### This task is done when:
 - We have a script that dumps a PostgreSQL database using `pg_dump` and produces a gzipped `.sql` file
 - We have a script that takes a gzipped `.sql` file and restores it into a PostgreSQL database using `psql`
 - We have a process (automated or otherwise) for passing around these database dump files. One option is to use cloud storage (i.e., the database dump scripts uploads a dump file to the cloud and the database restore script downloads a dump file from the cloud). Another is Slack allows file uploads of size up to 1GB. DropBox is another option

**Comment by keppel2** [comment]
Do you mean sync as in merge the contents? This sounds more like of a copy one way or the other.

**Comment by kenichi** [comment]
This target is called "prod_db_sync" but in fact it does overwrite the local dev database. It currently uses postgres:10-alpine container to dump the prod db to a file, scps that locally, drops local dev db, and restores local dev db from prod backup file, before cleaning up. A next step could be setting all credentials to something well-known, cleaning any PII, etc.
