### ISSUE TITLE
Add error to record when there are charges without a disposition

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#358]
## Description

Currently when there is a charge without a disposition a message is written to `type_eligibility_reason`, however type eligibility is determined upon charge creation not during expungement, and it would only affect time eligibility. Need to move the message from type_reason to time_reason, and add a message to the record so that the user can be informed that errors may exist in the records time analysis.

This task requires #261 to be completed first. Could also combine the two tasks into one PR.

Also it requires PR #357 to be merged in order to avoid conflicts.

### This task is done when:
 - `record.errors` has error message appended to its array stating that closed cases containing charges exist without a disposition, and that time analysis may not be correct for the record. The only exception to this if the charge would normally skip time analysis (some level 800 charges are like that). If that's the case then there shouldn't be an error message on the record object.
 -

**Comment by NickSchimek** [comment]
Further clarification. This is needed because the case may have a disposition, but OECI failed to properly log it.

**Comment by wittejm** [comment]
Type eligibility based on a missing or unrecognized dispo should still be Needs More Analysis, and is set here:
https://github.com/codeforpdx/recordexpungPDX/blob/a40b678af5ef523996f7a3cc81d93b339d24def2/src/backend/expungeservice/models/charge.py#L28

Although the rest of this issue will be resolved by #686
