### ISSUE TITLE
Add Redux Middleware to add authorization header for applicable requests

### ISSUE THREAD

**Issue by maxkwallace** [codeforpdx/recordexpungPDX#379]
See my comment at https://github.com/codeforpdx/recordexpungPDX/pull/371#discussion_r325462866

Note: https://auth0.com/blog/secure-your-react-and-redux-app-with-jwt-authentication/

Waiting on https://github.com/codeforpdx/recordexpungPDX/pull/371 to be merged and then I'll start this.

**Comment by ForrestLonganecker** [comment]
Just letting you know that #371 is now merged

**Comment by maxkwallace** [comment]
@ForrestLonganecker yup, I'll work on this tonight.
