### ISSUE TITLE
Only set eligibility date if type eligibility is true

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#385]
## Description

Currently eligibility date is set regardless when a charge is currently not time eligible, however it came to my attention that it could cause some confusion for users of the app. This could lead them to think that the charge will be eligible at that given date even though it says the charge is not type eligible. 

Currently the `TimeAnalyzer` is using the method `set_time_ineligible` in `BaseCharge.py`. The method can definitely be refactored/improved so that the change can be easily implemented.

Please add appropriate test cases for expected behavior.

Please reach out to `@poppa_nick` on slack if any questions.

### This task is done when:
 - Eligibility date is only persisted when a charge is type eligible. We should check on `type_eligibility != False` instead of `type_eligibility == True`, because type_eligibility can also be None when it "needs further analysis".

**Comment by wittejm** [comment]
There are still some record results that have this bug, listed on the expungement the bug reports page

**Comment by wittejm** [comment]
Completed by a recent logic change in the backend (always compute time eligibility) and a change to the frontend (hide time eligibility for type-ineligible changes)
