### ISSUE TITLE
Flow Diagram Access?

### ISSUE THREAD

**Issue by MatthewJMcAllister** [codeforpdx/recordexpungPDX#390]
Hello from Code for Denver!

On the Wiki, the process flow diagram is linked, but then requires authentication to view. Is it possible to make the read-only version open?
https://www.draw.io/#G1aLwddaCPTUMazWIat-U6nMyWf0Qdgvfe 

Thanks all,
Matthew

**Comment by hmarcks** [comment]
Hello! [Can you access it here?](https://drive.google.com/file/d/1aLwddaCPTUMazWIat-U6nMyWf0Qdgvfe/view?usp=sharing)

It may be a bit outdated unless @NickSchimek has updated it recently.

**Comment by MatthewJMcAllister** [comment]
@hmarcks that worked! Thanks for the speedy reply.

**Comment by NickSchimek** [comment]
@MatthewJMcAllister Thanks for letting us know about the locked link. Yes that flow is a bit inaccurate, and outdated. I am planning to get it updated in the next few months, and will also be consolidating all of our docs to our new documentation website. https://codeforpdx.github.io/recordexpungPDX/
