### ISSUE TITLE
Endpoint: registration & login

### ISSUE THREAD

**Issue by erikjasso** [codeforpdx/recordexpungPDX#46]
Write an endpoint to log the user into the internal website. Take the user's credentials, validate against information stored in the database, and return a token.

This endpoint should handle POST, with the body containing username and password in JSON:

    {
        "username": "<USERNAME>",
        "passowrd": "<PASSWORD>"
    }

See issue #42

**Comment by erikjasso** [comment]
See `src/backend/expungeservice/endpoints/hello.py` as an example of a Flask endpoint

**Comment by a-ilango** [comment]
I'm going to take a stab at this.

**Comment by a-ilango** [comment]
Added the following API endpoints in #66 
`/api/v0.1/users`: new user registration
`/api/v0.1/auth_token`: authenticate user and return JWT

**Comment by maxkwallace** [comment]
@a-ilango FYI moved this to "In Progress" since it's assigned to you. Let me know if that's not right.

**Comment by wittejm** [comment]
The login endpoint /auth_token is completed, and the endpoint for creating a new user , users.PO
