### ISSUE TITLE
Improve logging for all environments

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#463]
Our current logging approach for the backend app simply appends to a single file, which gets inconveniently large. For the Dev environment we are writing log files into the project directory. In deployment we might be able to use a Heroku logging mechanism for saving the logs. 

When we're writing log files:
 - Create a new log file for each day, to improve readability
 - Delete older logs on a regular basis, e.g. those more than a month old.
 
For production:
 - Identify and apply the best approach for the Heroku platform. You can follow the app logs in the heroku CLI, but how accessible is the older logging output?

**Comment by wittejm** [comment]
@NickSchimek Rewrote your ideas here. Feel free to add anything!

**Comment by NickSchimek** [comment]
Thanks @wittejm  it looks good

**Comment by KentShikama** [comment]
Sounds like a job for [logrotate](https://linux.die.net/man/8/logrotate). 

Here is an example configuration file to rotate the log file daily and then delete after 30 rotations.
```
example.conf

/path/to/file {
     rotate 30
     daily
     copytruncate
}
```

And then have a crontab to run

`logrotate -f example.conf`

daily.

**Comment by kenichi** [comment]
```
$ ls -l /var/log/recordsponge
total 248            
-rw-r----- 1 syslog recordsponge   4006 Apr 20 15:56 prod.log
-rw-r----- 1 syslog recordsponge     77 Apr 17 23:16 prod.log.1
-rw-r----- 1 syslog recordsponge  10932 Apr 20 15:43 staging.log
-rw-r----- 1 syslog recordsponge 227639 Apr 19 01:11 staging.log.1

$ cat /etc/rsyslog.d/99-recordsponge.conf
local1.*        /var/log/recordsponge/staging.log
local0.*        /var/log/recordsponge/prod.log

$ cat /etc/logrotate.d/rsyslog
[ snip... ]
/var/log/recordsponge/staging.log
/var/log/recordsponge/prod.log
{
        rotate 4
        weekly
        missingok
        notifempty
        compress
        delaycompress
        sharedscripts
        postrotate
                /usr/lib/rsyslog/rsyslog-rotate
        endscript
}
```

I've only appended the new log files to the default second section of `/etc/logrotate.d/rsyslog`, which uses a 4 day rotation. If we want to use @KentShikama's rotation config above, this would be the place to do it.
