### ISSUE TITLE
Endpoint: /api/users/

### ISSUE THREAD

**Issue by erikjasso** [codeforpdx/recordexpungPDX#47]
Endpoint for making and getting users. Endpoint should handle POST and GET requests.

`POST /api/users/` to create a user:

    {
        "username": "<USERNAME>",
        "email": "<EMAIL>",
        "admin": "<TRUE|FALSE">
    }

`admin` is optional and will default to False

`GET /api/users/USER_ID` to get a user

The `GET` response is TBD but will include some set of columns in the `users` table. It could be:

    {
        "user_id": "",
        "username": "",
        "email": "",
        "admin": "",
        "date_created": "",
        "date_modified": ""
    }

**Comment by erikjasso** [comment]
See `src/backend/expungeservice/endpoints/hello.py` for an example of a Flask endpoint

**Comment by wittejm** [comment]
closed because redundant with issue #172
