### ISSUE TITLE
Endpoint: /api/stats

### ISSUE THREAD

**Issue by erikjasso** [codeforpdx/recordexpungPDX#49]
Endpoint for reporting on system statistics such as number of searches done, number of records expunged, and anything else we think is interesting

**Comment by erikjasso** [comment]
See `src/backend/expungeservice/endpoints/hello.py` for an example of a Flask endpoint

**Comment by erikjasso** [comment]
This endpoint could also return data for displaying in a chart

**Comment by wittejm** [comment]
We've decided against keeping or using any results data
