### ISSUE TITLE
The dependency bot is clogging the PR's.

### ISSUE THREAD

**Issue by keppel2** [codeforpdx/recordexpungPDX#522]

**Comment by wittejm** [comment]
It sure is! I think @ForrestLonganecker had suggested the idea of reconfiguring dependabot to only bump patch updates for security dependencies. I imagine there are a few options for making other dependency bumps less frequent. @keppel2 you want to look into it?

**Comment by wittejm** [comment]
From a comment that I pulled off of PR #521 :

So far we've been managing the risk of breakages from version bumps by reviewing dependabot's PRs as they come in. 

Should we change that approach? Start locking more of our dependencies? Just do a better job staying on top of PRs? 

The frontend in particular has so many dependencies and updates that it's a ton of overhead. 

Pinging @maxkwallace @NickSchimek @KentShikama for opinions.

**Comment by NickSchimek** [comment]
I can definitely configure the frontend to only bump security patches. It's what I've done on my other projects. @ForrestLonganecker what do you think?

**Comment by ForrestLonganecker** [comment]
@NickSchimek I think that is not a bad idea. I have my projects set to alert for security updates and then I am able to update the others as needed. But I am open to other opinions!

**Comment by NickSchimek** [comment]
Dependabot is set to never open more then 10 PR's. Unless there is a security update then dependabot creates a PR immediately regardless.

What I will do is setup the frontend to only receive security updates. And then we can update non-security updates every 6 months or so. We will just have to be diligent about it.
