### ISSUE TITLE
Account HTML template

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#53]
Create view in HTML / CSS for the Account view.

This is very similar to the "Add user" view.

Wireframes: https://marvelapp.com/644d2f9/screen/50214083
Design system: http://dev.huntermarcks.net/design-system

Will probably want to build in the prototype for now. You can fork this repo: https://github.com/hmarcks/expunge-pdx-frontend

**Comment by maxkwallace** [comment]
@drewlearnsabout Hey! I'm not trying to nag, just hoping to understand where the project is and what tasks are available for people to work on. How's this issue going, and do you have any in-progress code you can push up in a branch? If you're working on this I want to make sure that any changes I make in the frontend code aren't going to conflict with or duplicate what you're already working on.

**Comment by drewlearnsabout** [comment]
@maxkwallace Hey Max.  No worries, I've been distracted by other things these past few weeks to get it done.  When I was at the meetup yesterday, I was finally able to start getting the markup together, and I'm hoping i can get a draft finished by this month. I'll try to push to the branch soon.

**Comment by maxkwallace** [comment]
@drewlearnsabout sounds good, thanks for the update! If you push the branch up to this repo (not your own fork) that would be ideal, since it'll be easier for other folks to check out your work that way. If you have anything completed I would say just go ahead and push it up right away-- then post the name of the branch back here. 

That way it'll be easy for anyone who comes across the issue to see how things are going, and make sure any code they're writing isn't going to conflict with the work you've already done.

**Comment by hmarcks** [comment]
@maxkwallace this work is actually on a separate repo for now (https://github.com/hmarcks/expunge-pdx-frontend) where we're working on the HTML templates, so @drewlearnsabout you can make a pull request to that repo when you're ready.

Once we have the frontend on this repo set up (I think we're close), we can transfer these templates and css over.

**Comment by maxkwallace** [comment]
@hmarcks my bad, thanks for the clarification!

**Comment by hmarcks** [comment]
@maxkwallace no problem, It's kind of a strange process, thanks for checking in on the tickets!

**Comment by a-ilango** [comment]
I saw this on the front end specific repo:
> We have this separate repository because it's quicker than getting the full local environment running.

Just curious. What makes it slow when running it in the main repo? Sorry, I'm not familiar with the front-end.

**Comment by hmarcks** [comment]
@a-ilango I remember having trouble with my machine getting our repo running locally, might have just been me. But I think the main advantage of keeping it in a separate repo was that I could easily make a github pages site public so I could share the click-through prototype.

**Comment by a-ilango** [comment]
@hmarcks, thanks for clarifying. I didn't know about github pages before. That's pretty neat!

**Comment by hmarcks** [comment]
Completed, see http://dev.huntermarcks.net/account and http://dev.huntermarcks.net/admin/edit-user (also added edit account view)
