### ISSUE TITLE
Fix KeyError: 'oeci_token' when user tries to search before OECI login

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#545]
The error message is as follows

```
2019-11-13T08:59:05.042120+00:00 app[web.1]: File "./expungeservice/endpoints/search.py", line 28, in post
2019-11-13T08:59:05.042123+00:00 app[web.1]: decrypted_credentials = cipher.decrypt(request.cookies["oeci_token"])
2019-11-13T08:59:05.042129+00:00 app[web.1]: KeyError: 'oeci_token'
```

We should never have a 500 server error. The simplest fix is to return a 40x error when the `oeci_token` is missing. Ideally we should make it impossible for the user to search before they login to OECI based on front-end flows.

**Comment by NickSchimek** [comment]
How can I duplicate this error?

**Comment by KentShikama** [comment]
Do a valid search without logging in to OECI.

**Comment by NickSchimek** [comment]
oh I see. We need to prevent access to search page when login creds don't exist. When that occurs it should redirect user to login screen. Thanks for reporting this! One thing I haven't done yet is play around with the UI. Great catch

**Comment by ForrestLonganecker** [comment]
Just opened a PR that redirects on the client side if no OECI token is present.
#587
