### ISSUE TITLE
Cleanup of files that don't end in line feed

### ISSUE THREAD

**Issue by keppel2** [codeforpdx/recordexpungPDX#555]
Running this `find . -type f -exec echo -n {}, \; -exec hexdump -ve '/1 "%02X"' {}  \; -exec echo \; | grep -v 0A$` shows a few files that don't end in a line feed. This is in a category of text problems that can lead to issues later. There's no carriage returns in the entire repo--so that's good. This should only be considered complete when it's part of the automated tests.

**Comment by keppel2** [comment]
It's fine to just clean them up occasionally like #693--it might be weird for beginners to see check-in test errors.

**Comment by keppel2** [comment]
We have scripts that appear to lint the frontend(husky). Fixing LF there should be fine.

**Comment by wittejm** [comment]
AFAICT the only python files without a newline are __init__ files.
