### ISSUE TITLE
Connect frontend search component to backend search endpoint

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#567]
PR #566 Creates a search component, however it does not hit the backend when the search form is submitted, and instead retrieves a fixture.

**Comment by KentShikama** [comment]
It is already connected. #566 just modifies the Case component to show more details about the Case than before.

**Comment by KentShikama** [comment]
See https://github.com/codeforpdx/recordexpungPDX/pull/533

**Comment by NickSchimek** [comment]
@KentShikama Thanks! I thought it was connected. Looks like Olli's PR wasn't rebase with master recently which explains why it wasn't working on his branch. Thank you.
