### ISSUE TITLE
Date of birth needs to be an optional argument

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#580]
## Description

Date of birth needs to be optional. The validations in the front end do not allow searches without a date of birth. The backend expunger does not place any restriction on this and allows searches without a birth date.

Note from client:
> Sometimes, people's birthdates will be incorrect or missing from the OECI altogether. In these instances, the cases will still be under their name, but won't be found under the date of birth. 

To do: 
 -  [x] Remove the validation in the front end to allow searches without a birth date.

**Comment by ForrestLonganecker** [comment]
@NickSchimek do you know if you are returned the same record information when searching for the same name with or without date of birth?

ie:  
- first name: Dave, last name: jones, Birthday: null
- first name: Dave, last name: jones, Birthday: 10/10/1990

Will these both provide the same output? Or will records including birthdays only come up if the date of birth is entered with the search?

**Comment by NickSchimek** [comment]
> Or will records including birthdays only come up if the date of birth is entered with the search?

No, that is not the case.

> Will these both provide the same output?

Yes and No. The client only uses birthdates for disambiguation. For example two people could have the same name. It is up to the client to determine which params to include. This functionality matches the OECI functionality. Hence, it should not be an issue.

The only param we are missing that OECI has is the middle name param. The backend is built to handle this. However, I believe Michael told Hunter that we did not need it and it was left off of the front end.

**Comment by ForrestLonganecker** [comment]
Okay that makes sense, so to clarify:

If a name `A` is searched, it will provide all the records under that name. 

If name `A` is searched again *but a birth day is included*, it will only show the records from above that have the matching date of birth

Thanks for the clarification!

**Comment by ForrestLonganecker** [comment]
Fixed this issue with PR #589
