### ISSUE TITLE
Use "production" configuration in Prod environment

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#581]
The backend app launch script [src/backend/expungeservice/config.py](https://github.com/codeforpdx/recordexpungPDX/blob/master/src/backend/expungeservice/config.py) only uses `development` config because there is no `TIER` environment variable specifying that the heroku app should use a `production` configuration.  
### This task is done when:
  -Create environment variable in heroku app `TIER=production`
  -Create environment variable in heroku app for `SECRET_KEY` to support persistent login state. The dev configuration uses a randomly generated key which is reset every time the app restarts. 

This is the only item remaining from issue #42 , which can be closed. The old issue includes:
- store RSA keys (must be able to handle 2 at a time for rotation)
- rotate RSA keys every 30-90 days

Is this actually required?

**Comment by KentShikama** [comment]
We do use `TIER=production` on heroku. See the config vars section on the heroku web app. Also see https://github.com/codeforpdx/recordexpungPDX/blob/master/src/backend/expungeservice/wsgi.py#L4.
