### ISSUE TITLE
A Dismissed DUII charge should be "Further Analysis Needed"

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#592]
(edited to account for charges explicitly labeled as "diverted)"
- In general, any dismissed charge is normally expungeable.
- A DUII charge can be marked with a "diverted" disposition, meaning that it was a conviction that was reclassified to a dismissal because the defendant entered a recovery program or similar. 
- In some cases a DUII charge can be marked "dismissed" even if it was diverted.
- This type of diverted charge is not expungeable. A **diverted charge** needs to be marked as **not expungeable**. 
- A dismissed DUII charge needs to be marked with `type_eligibility.reason == 'Further Analysis Needed'`

This rule is described in [Statute 137.225 (8)(b) ](https://www.oregonlaws.org/ors/137.225)

Diversion is described here: https://www.oregonlaws.org/ors/813.200

This is related to two bugs reported from the logic bug-reports page (identifying record information is omitted here) 

### This task is done when:
 - A new test case checks that a dismissed charge with "DUII" in the name is classified correctly.
 - A new Charge subclass called DUII is implemented in expungeservice.models.charge_types
 - The DUII class has `type_eligibility.reason == 'Further Analysis Needed'` if it is a dismissed charge. Otherwise (if it's a convicted charge or a diverted charge) it is ineligible.
 - the ChargeClassifier classifies a DUII charge in the `_classification_by_statute` method. The statute is 813010. This statute needs to appear in the list before `ChargeClassifier._traffic_crime(statute)` because it is a special case of a traffic crime. 
 
I'm pinging Michael and @NickSchimek to review this for correctness before I start working on this issue.

**Comment by NickSchimek** [comment]
Thanks for putting this together @wittejm  
My understanding of Oregon law is that only a DUI charge can be diverted. Is that assumption correct? or can other traffic charges (reckless driving) also be diverted?

I also found that statute 813011 is a Felony DUI charge, is it possible there are other statutes, possibly statutes no longer in use due to previous revisions, that should be classified as DUIs? These statutes do get revised from time to time so it's something to keep in mind for ease of flexibility.

With that in mind I wonder if it would be better to instantiate any 800 level traffic charge with a diverted disposition as ineligible? Then if the 800 level traffic charge is an arrest and a DUI charge then mark it as further analysis needed.

Also let's talk more about how the data is collected and ways to improve the results this wednesday.

**Comment by wittejm** [comment]
> I also found that statute 813011 is a Felony DUII charge, is it possible there are other statutes, possibly statutes no longer in use due to previous revisions, that should be classified as DUIIs? These statutes do get revised from time to time so it's something to keep in mind for ease of flexibility.

I found that Oregon Chapter 813 covers DUIIs. To my untrained eye everything except for 813010 concerns enforcement and punishments and stuff (including 813011, which is a "prior DUIIs" condition).

More details:

The Expungement statute just refers to "An arrest or citation for driving while under the influence of intoxicants" and not the particular statute or chapter.

I found a few occurrences where 8130104 (a subsection of 813010) was the reported statute in OECI.  The 4 at the end refers to the subsection of 813010. Maybe other occurrences of DUII in OECI would be under statute 8130105 (another subsection defining charge level).

A "blanket" way to classify a DUII charge is to check if the chapter is 813. I'll ping Michael on his preference between classifying by chapter 813 or only statute 813010 (and its subsections).  

> With that in mind I wonder if it would be better to instantiate any 800 level traffic charge with a diverted disposition as ineligible? Then if the 800 level traffic charge is an arrest and a DUII charge then mark it as further analysis needed.

I think that our bases are covered if we mark 
- any dismissed DUI charge as further analysis needed, 
- any diverted DUI charge as ineligible,
- other diverted charges as further analysis needed

(That last is until we incorporate more specifics; Michael has mentioned a few non-dui charges that can be diverted and be eligible).

The scope of this issue is still on DUIIs and I think that handling Diverted charges on other charge types can go in a different issue (which itself will depend on #601).

#601 will probably be a larger refactor that will include refactoring the forthcoming PR for this issue. But as a bugfix I think that starting with this completing this issue makes sense.
