### ISSUE TITLE
Create "AddUser" Component

### ISSUE THREAD

**Issue by ForrestLonganecker** [codeforpdx/recordexpungPDX#593]
Create a component that visually represents the `AddUser` component listed in the mockup:
http://dev.huntermarcks.net/admin/edit-user

The actual functionality of interacting with the backend (responding to clicks on buttons within the `AddUser` component) should be handled in a separate issue (create it if you want to work on it).

### This task is done when:
 - The component visually matches the mockup
 - When you click the "Add User" button the "AddUser" component appears

**Comment by hmarcks** [comment]
Wireframes for more context around the whole users flow:
![user-account-wireframe](https://user-images.githubusercontent.com/6887982/69019529-a78c4480-0976-11ea-853d-4c69937e0deb.png)

Accessible validation technique: https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA19

**Comment by hmarcks** [comment]
Based on PR #606, grbarker is working on this
