### ISSUE TITLE
Disposition Date is labeled with "Convicted" even on Dismissed charges

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#605]
Every charge that is rendered in the frontend search results says "Convicted" for the date even when the charge is a dismissal. Here is a screencap example of the current format.

It should instead say something more accurate, either "Date", "Date of Disposition", "Date of [Conviction/Dismissal]", etc. 

I'm pretty sure this is just a one-line change in :
https://github.com/codeforpdx/recordexpungPDX/blob/master/src/frontend/src/components/Charge/index.tsx 

I also want to confirm any design change suggestion with at least @hmarcks  , @NickSchimek .

!['convicted' date label should say 'disposition'](https://user-images.githubusercontent.com/2104990/70184732-4b772f00-169d-11ea-8439-afbb5ee4921b.png)

**Comment by hmarcks** [comment]
I had the mockup show "Arrested" for the date, which I believe Michael signed off on. Can we get the arrested date or only the date it was dismissed?

<img width="650" alt="Screen Shot 2019-12-07 at 2 05 25 PM" src="https://user-images.githubusercontent.com/6887982/70380067-208a1680-18fb-11ea-9e9e-db31fe9f1e1a.png">

**Comment by wittejm** [comment]
Currently the date comes from the final Disposition entry which is either convicted or dismissed. I like the idea of getting the Arrested date but that will require some refactor on the backend.

**Comment by wittejm** [comment]
Oh hold on that is incorrect. Sorry. There is a date in the search result (returned by the endpoint) that  associated with the charge and not the disposition. Maybe this is the date of arrest? @NickSchimek

**Comment by NickSchimek** [comment]
@hmarcks @wittejm Yes, that is not a problem, the arrest date is available. The date of arrest is the date the case is opened, which is available as `case.date` or `charge.case.date`

**Comment by NickSchimek** [comment]
Yes @wittejm you are correct. `charge.date`

**Comment by NickSchimek** [comment]
The case.date is actually the date that it was filed. so it is charge.date
