### ISSUE TITLE
Create "TermsOfUse" Component

### ISSUE THREAD

**Issue by darenschaad** [codeforpdx/recordexpungPDX#611]
Currently when a user clicks on the terms of use link, it directs them back to the login page. It should instead direct them to the terms of use page

### This task is done when:
 -Clicking on the "terms of use" link takes the user to the appropriate page

**Comment by KentShikama** [comment]
@michaelzhang43 Do you think we need a separate terms of use page when we already have the manual (https://dev.recordsponge.com/manual)?

**Comment by hmarcks** [comment]
I think we should have a statement about how we don’t collect data. We could put it in the manual and link to the section from the Terms footer since that’s a standard area to provide a link to that info.

**Comment by hmarcks** [comment]
I created a draft [document we can collaborate on here](https://docs.google.com/document/d/1YBbY9NhfFSro2QJr9I1k8iZ-C168wMn0l2-P4cGa3gY/edit?usp=sharing). I used the Basecamp policy as a template. I posted some questions in the doc, please take a look.

I started with the Privacy Policy for now since Terms are more relevant if we are selling any services, but Michael may want to lay out some basic terms.

**Comment by michaelzhang43** [comment]
Hey all
I started a squib for this on the Manual google doc, but I like the one that Hunter created a lot more. For the record, the squib is:
"
Privacy Policy

Our privacy policy is simple and meant to be read by all of our users. Please email michael@qiu-qiulaw.com if anything is unclear. 

Search criteria not collected
We care about the privacy of your clients’ criminal records. Indeed, this project’s purpose is to make these records more private. Therefore, RecordSponge does not record or collect search information. If you are using this software for clients, we have no way of identifying who they are. 

OECI login credentials not collected
We do not save your OECI login credentials. That’s why we must separately login into OECI every time you use RecordSponge. 

Search “pings” to track usage 
The only information we collect are user search “pings,” which tells us when (and only when) a user has made a search. We collect this information to track usage rates - if we see that you are searching more or less than usual, we may contact you to see if we can provide support. That’s it. 

Information we have access to
We can access your username, password, and search pings. The username doubles as an email where we can contact you or someone in your organization. We therefore highly suggest making your password different from the password normally associated with 
"
I think basically we just need to add in that we track search pings, that specifically we do not track OECI login info

**Comment by wittejm** [comment]
Correction: we don't save passwords in the app. Instead we just encrypt them in a non-reversible way (a hash) so that we can compare for a correct password upon login

**Comment by wittejm** [comment]
> We therefore highly suggest making your password different from the password normally associated with

I would say, "As with any online service, we highly recommend making your password different from other passwords you use"

**Comment by hmarcks** [comment]
Excellent, I consolidated the content in the [Manual doc](https://docs.google.com/document/d/1Su078uVl_tg0TuvyAUGr8n2IBQolhWl0H3rN1LUFRNI/edit?usp=sharing). @wittejm and @KentShikama there are some open technical questions I highlighted, thanks

**Comment by KentShikama** [comment]
@hmarcks @wittejm I'm guessing this can be closed/superseded with https://github.com/codeforpdx/recordexpungPDX/issues/1244?

**Comment by hmarcks** [comment]
yeah, I think Jordan also mentioned that our Privacy Policy covered everything we wanted to say
