### ISSUE TITLE
Create PR Template

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#616]
Whenever there are PR's that enhance/fix the expungement logic then the CHANGELOG should also be updated. Create a PR template that reminds contributors to update the CHANGELOG with their PR.

@wittejm Perhaps we want to capture other changes in the CHANGELOG too?

**Comment by NickSchimek** [comment]
Here is the documentation page for creating a PR template https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

**Comment by wittejm** [comment]
Yea, IMO the changelog only needs to show frontend fixes and expungement logic enhancements/fixes, since it's really a document for users and the devs can see everything through commit history.
