### ISSUE TITLE
A case with a conviction or dismissal is closed even if it has "Active" status

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#618]
For some cases the OECI page wrongly lists the status as "Active" in the list of search results, even if the case is closed. If all the charges in a case have a conviction or dismissal in their disposition, the case should be considered closed so that the expunger time analysis runs correctly. 

### This task is done when:
 - the `Case._closed()` method returns `True` if the disposition ruling on every charge is convicted or dismissed, even if `case.current_status == Active`
 - Add a unit test

**Comment by wittejm** [comment]
This can be completed after PRs #645 and #648 have been completed and merged

**Comment by cellepo** [comment]
I plan to get back to this when I get less busy - un-assigning from myself for now in case someone else wants to work on it in the meantime (will get back to it myself later if that did not end up happening).

**Comment by wittejm** [comment]
Design update: Charges are now marked as "meaningfully open" only if they are blocking, so we can leave the Case Status unchanged so it is matching what is in OECI. An Open Case without meaningfully open charges isn't reported as an error.
