### ISSUE TITLE
Time eligibility reasons are inconsistent

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#619]
The time eligibility reasons are inconsistent between the mockup, the logic flowchart, and the existing output from the TimeAnalyzer.

Namely, in the flowchart some of the time-constraint labels include  "Time-ineligible under [statute-subsection]", while some others say , "eligible at [date]".

The mockup and time analyzer both use some inconsistent / confusing wording IMO. For example the reason "Most recent conviction is less than three years old" (from the time analyzer): 

1. is not explicit that this is referring to itself as the conviction 
2. is misleading about what the actual rule is for time constraints generally: for example if the most recent conviction is 4 years old, it still renders all other expungements ineligible.

The reason "no more than 1 arrest in 3 years" (from the mockup) makes sense if it's attached to a dismissed charge, but is incorrect if it's attached to a convicted charge. "No conviction within 3 years" is a valid rule if it is attached to a conviction but is incorrect if it is attached to a dismissal.

There are 5 different time-constraint rules, and I propose using the following wordings:

 - Convictions are ineligible for 3 years
 - No-complaint arrests are ineligible for 1 year
 - Must have no other convictions for 10 years
 - Must have no other arrests for 3 years
 - B felony convictions are ineligible for 20 years 

Since the flowchart and time analyzer sometimes refer to the statute subsection that applies:  if we want to we could add this as another line in the result. 

Pings for @NickSchimek and @hmarcks but any opinions welcome
 
### This task is done when:
 - the `reason` values in `time_analyzer.py` have been updated.

**Comment by wittejm** [comment]
So, just because there are a bunch of ways to write this and I want to shoot for consistency more than anything, and partly to demonstrate that I think trying to make it really clear is a pain in the butt, here's a different set of reasons. Arguably, these phrases fit more naturally into reading the entry as  "Eligible at [date] because that date is...[reason]:

- Ten years from most recent conviction
- Ten years from second-most recent conviction
- Three years from most recent arrest
- Three years from most recent arrest - Recommend sequential expungement
- Three years from second-most recent arrest
- One year from No Complaint arrest
- Three years from conviction
- Twenty years from B felony conviction

The reason of "Recommend sequential expungement" occurs if there is exactly one arrest from the last 3 years. That's because the most recent arrest is time-eligible (if there are no convictions within 10 years), and once you expunge it, any other arrests become time-eligible because they are no longer blocked by the arrest that just got expunged.

Fun fact: convictions do not work the same way.

**Comment by hmarcks** [comment]
It looks like I had different language in the actual HTML than the mockup in the story, but I included the original proposal (v1) and added your suggestions (v2) (also updated the open case scenario). 

I'm down with you proposal, but let's get Michael and Nick's feedback too. Thanks!

![time-eligibility-language](https://user-images.githubusercontent.com/6887982/70591290-3b7ab600-1b9b-11ea-8747-18cf0c3540e8.png)

**Comment by wittejm** [comment]
I checked in with Michael and he likes the idea. @NickSchimek what do you think?

**Comment by wittejm** [comment]
Since we're working to add applicable statute sections to type eligibility reasons, we should add statute references to these reason strings also.
