### ISSUE TITLE
Add a repealed statute that qualifies as a PCS charge

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#624]
The statute [475.992 ](https://www.oregonlaws.org/ors/475.992) used to describe a PCS charge but has been repealed/renamed. Since it still exists in OECI records applying to PCS, we should classify it accordingly.

The OECI records actually list, for example, 4759924A and 4759924B under this statute, which refer to its subsections. So when we check to see if a charge matches the statute we could examine only the first 6 digits rather than doing a string equality 

### This task is done when:
 - update [charge_classifier.py](https://github.com/codeforpdx/recordexpungPDX/blob/master/src/backend/expungeservice/models/charge_classifier.py)
 - a new test for this use case

**Comment by NickSchimek** [comment]
Thanks @wittejm This is related to issue #169
