### ISSUE TITLE
Refactor the unit tests for the charge models

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#627]
## Description
When the type analyzer was removed/refactored the tests for the type analyzer were not refactored too. Some previous PR's have refactored the tests into their on files for unit testing each of the different charge types, but there are still some charge types remaining.

## Task
Finish refactoring the unit tests for the models

### Additionally
Update the schedule1PCS tests to include the new statute in PR #626

**Comment by wittejm** [comment]
Hi @nickbeaird , I see you've started working on a few issues besides this one as well. How is this one going?

**Comment by wittejm** [comment]
Hi @nickbeaird I'm working on #795 and part of that effort is to update their unit tests which would overlap somewhat with this issue. Do you have progress you could push for this issue? This is just to check if you've already done work that I wouldn't need to repeat for these types.

**Comment by wittejm** [comment]
Ah, I just came across the branch you're working on https://github.com/codeforpdx/recordexpungPDX/tree/627_refactor_tests Looks like you've made a lot of progress! Want to file a PR with what you have so far? I recommend you file PRs incrementally to help us keep our work roughly in sync, and reduce the risk of merge conflicts. 

My PR #813 for Subsection12 rips some old code out of `test_type_analyzer_convicted_charges.py` but other than that I don't think it should cause too much conflict with your progress here.

**Comment by nickbeaird** [comment]
I am posting here to keep everyone up-to-date. I met up with @wittejm today. I had a PR that was open for too long, and had some potential issues, so that branch was deleted from the remote repo, and I am opening a new one now. I will submit the new PR by EOD.

**Comment by nickbeaird** [comment]
Here is the PR for this project. https://github.com/codeforpdx/recordexpungPDX/pull/850. Please feel free to send me any notes in the meantime.

**Comment by wittejm** [comment]
Completed
