### ISSUE TITLE
Add SearchResultsSummary Component in React

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#630]
A new component will provide summary data about search results, appearing above search results details. 

The mockup for this feature is below. Use the HTML from http://dev.huntermarcks.net/search // [here's the relevant commit](https://github.com/hmarcks/expunge-pdx-frontend/commit/e62e80ee7ff9dac2c71c8d30679f7dc0513c1efc)

### This task is done when:
 - SearchResultsSummary component is implemented in React
 - The existing SearchResults Component should be renamed to SearchResultsDetail. These two components should be wrapped together into a single component called SearchResults, which can remain a member of AllRecords.
 - The component is integrated with `/api/search` endpoint, which must be expanded to provide the `case_summary` and `charge_summary`, and `balance_due_summary` data that get rendered in this component (see issue #631  for endpoint implementation). 
 

![Record Expunge Search Summary Copy](https://user-images.githubusercontent.com/6887982/71208008-c0399400-226d-11ea-8e8e-d225d1644be3.png)

**Comment by hmarcks** [comment]
Created the HTML/CSS and updated the description

**Comment by wittejm** [comment]
@hmarcks Awesome, thank you!

**Comment by wittejm** [comment]
completed with #756
