### ISSUE TITLE
Make Records generated from hypothesis more realistic

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#634]
See https://github.com/codeforpdx/recordexpungPDX/pull/610#pullrequestreview-328581915

**Comment by wittejm** [comment]
I was thinking of having this more realistic data for the purpose of supporting/testing frontend development, but actually I don't know if hypothesis is the easiest way to do that.

**Comment by wittejm** [comment]
Changed my mind:  we don't need much plausible fake data, -- only enough to demo the app, and these can be selected from real anonymized  examples or put together by hand. So, closing this issue
