### ISSUE TITLE
Add levels of eligible charges to saved search results

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#636]
In our search results we save the number of charges and the number of eligible charges found on a record. But we also want to count the charges by type, according to the [project requirements document](https://docs.google.com/document/d/1H9m1Xa8yDcMbR-MhD5VZSI3J_oq91Kpdw1TMM0qvZrs/edit)

### This task is done when:
 - add the following columns to the SEARCH_RESULTS table: num_eligible_felonies, num_eligible_misdemeanors, num_eligible_violations, num_eligible_arrests
 - compute and save these for the search result in [stats.py](https://github.com/codeforpdx/recordexpungPDX/blob/master/src/backend/expungeservice/stats/stats.py)

**Comment by m-murasovs** [comment]
Hi, I hope it's alright I assigned myself to this one :)

**Comment by m-murasovs** [comment]
Is there a way of seeing what the 'record' is, so that I could compute the numbers? Thank you!

**Comment by wittejm** [comment]
Yes, you're welcome to work on this issue. I think it was mislabeled and it's actually closer to Complexity 3, though, and our documentation/support for getting started to work on the record datas and expunger are not great. But for a few notes on how you would get the level info from the record data:

An example of the record data structure is here: https://github.com/codeforpdx/recordexpungPDX/blob/master/doc/results_format.json

The actual `level` is just a string on the [Charge](https://github.com/codeforpdx/recordexpungPDX/blob/master/src/backend/expungeservice/models/charge.py) object. But it's pulled directly from the OECI database and, while it gets parsed in the [ChargeClassifier](https://github.com/codeforpdx/recordexpungPDX/blob/master/src/backend/expungeservice/models/helpers/charge_classifier.py) , the string doesn't standardized and it might take more work to map the value to to a database column.   

I would recommend using an Enum and parsing various `level` strings into the particular levels as enum values: Violation, misdemeanor, felony , much like the way we handle [Disposition](https://github.com/codeforpdx/recordexpungPDX/blob/master/src/backend/expungeservice/models/disposition.py) strings that come from OECI results.

**Comment by wittejm** [comment]
In our test cases, especially the various [Factory](https://github.com/codeforpdx/recordexpungPDX/tree/master/src/backend/tests/factories) classes and the [charge classifier test cases](https://github.com/codeforpdx/recordexpungPDX/tree/master/src/backend/tests/models/charge_types) , you'll find examples of the string values of `level` that the app needs to handle for this feature.

If it looks tough for an early issue to work on, that's understandable, so feel free to ask any more questions or to switch to a different issue if you'd prefer that!

**Comment by m-murasovs** [comment]
Hi, sorry for the long absence. I'll switch to a different issue I think, as this looks beyond my backend capabilities for now. Cheers!

**Comment by wittejm** [comment]
Sounds good!

**Comment by wittejm** [comment]
we're throwing away all results like this
