### ISSUE TITLE
Search component integration

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#64]
Create a component that allows you to search records and return results.

States:
* Empty search form
* Validations on search form
  * All search fields are required.
  * The date format must be MM/DD/YYYY.
  * Technical error, please try again in a few minutes.
* Loading
* No records found
* Search results
  * See mockup below for details

HTML to use: https://github.com/hmarcks/expunge-pdx-frontend/tree/master/search

![Record Expunge Search UI Data v2](https://user-images.githubusercontent.com/6887982/62498288-50d27480-b7a4-11e9-8341-cc263fa86d3c.png)

**Comment by maxkwallace** [comment]
@josephhess Hey! (Sorry, same comment as in the other issue.) I'm not trying to nag, just hoping to understand where the project is and what tasks are available for people to work on. How's this issue going, and do you have any in-progress code you can push up in a branch? If you're working on this I want to make sure that any changes I make in the frontend code aren't going to conflict with or duplicate what you're already working on.

**Comment by maxkwallace** [comment]
@josephhess FYI, as far as I'm aware, you haven't responded so I'm going to unassign this from you and open it up to someone else to work on. Thanks!

**Comment by ForrestLonganecker** [comment]
## The `Search` component now does the following:
- Populate with empty search form
- Validates form upon search
- Displays validation errors
- Displays loading spinner
- Displays either "No search results." or returned search results

## ToDo:
- Add drop shadow #569 
- Handle "Unknown type or time eligibility" #584 / #586 
- Make Date format less strict #571

@hmarcks @maxkwallace @wittejm  It may be beneficial to close this issue as we are working on more specific integration issues regarding the `Search` component. I will leave this open for the time being, any opinions or ideas are welcome and appreciated!
