### ISSUE TITLE
Display the latest version number, launch date, and link the changelog

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#650]
### This task is done when:

 - Include the current version number and a link to the changelog document in the github repo.
 - Show the date of the last release. Ideally this is automatically updated with every push of a new version.

**Comment by wittejm** [comment]
@ForrestLonganecker What do you think is the best approach to keep the version/ date updated dynamically?

**Comment by ForrestLonganecker** [comment]
I would most likely scrape the `repo/releases` page for "Version ## - released this time ago" and then generate a component based off of that returned information.

@hmarcks would you have input on how the design of this feature would look?

We would most likely want to include:
- version number
- date/time of release
- link to the release page
- As well as expected periodic "down time"

from: https://github.com/codeforpdx/recordexpungPDX/releases

Excluding:
- Who actually pushed the release

**Comment by ForrestLonganecker** [comment]
@wittejm I just remembered that github has an api, I'm not sure if it will provide the information needed for this but we can take a look at it and see if it does:

https://developer.github.com/v3/repos/

**Comment by ForrestLonganecker** [comment]
Here we go!

https://developer.github.com/v3/repos/releases/#get-the-latest-release

We would need to make the request via the back end to keep all  sensitive login data secure but could then provide the data to the frontend to populate a component.

**Comment by ForrestLonganecker** [comment]
We should also include information on OECI's scheduled down time which occurs every 4th weekend of every month.

**Comment by KentShikama** [comment]
Accessible now through https://recordsponge.com/version.json ; see https://github.com/codeforpdx/recordexpungPDX/pull/1022
