### ISSUE TITLE
Charges with missing or unknown dispositions are record errors

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#652]
A case with a missing or unknown disposition on a charge can be closed but still affect time eligibility with unknown impact. The charge could be either convicted or dismissed which can make a big difference for expungement eligibility of other records. This error should be attached to the record and reported in the frontend, with an informative warning message, like: "This record has charges with missing or unknown dispositions, which may affect the time eligibility of other charges." 

This issue depends on open PRs #645 and #648, which already impact the way that missing/unknown dispositioned charges are being handled by the expunger. 

### This task is done when:
 - The expunger attaches charges with missing and unknown dispositions to `record.errors`

A separate PR should expand the warning message on the frontend, which is related to issue #586

**Comment by hmarcks** [comment]
When there's a missing/unknown disposition, we could notify the user of this and give them the option of running analysis with the charged marked as convicted or dismissed (similar to #586 where you run analysis ignoring the open case). Does that sound reasonable?
