### ISSUE TITLE
Reading Non-Disposition Events from OECI

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#667]
In a few cases, the Disposition doesn't provide conviction/dismissal info and only says "Conditional Discharge" or something, and you can see that the charge was either dismissed or convicted in the Sentence or the Amended Disposition.

For now, the charges with these dispositions are marked as "needs more analysis" but we could infer the exact eligilibility from the other events on the record.  

I'm not sure about this idea since I think it might be fairly major change to both the crawler and then for handling the extra (and often extraneous) information in the expunger. Thoughts, @KentShikama , @NickSchimek ?

**Comment by KentShikama** [comment]
This is one of the reasons I've pressed to refactor the case parser (https://github.com/codeforpdx/recordexpungPDX/issues/655).

**Comment by wittejm** [comment]
Oh, yes good.

**Comment by wittejm** [comment]
I'll update the bug reports page
