### ISSUE TITLE
Link in-page to individual case entries in error banners 

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#695]
The error messages for open cases and missing/unrecognized dispositions show the relevant case numbers. Those case numbers should be links that link to the case detail that is further down the page in the Search Results.

EDIT: The in-page links in the Summary panel are working as expected. Because the error banner is generated in the backend, this is probably where we want to generate the html link tag also. So this new behavrior will be reflected in the frontend but the actual code changes should be in the backend expunger file, at lines:

https://github.com/codeforpdx/recordexpungPDX/blob/ccc4160f9ff25a74a67e5d7dc8a67acfe61e9639/src/backend/expungeservice/expunger.py#L36

https://github.com/codeforpdx/recordexpungPDX/blob/ccc4160f9ff25a74a67e5d7dc8a67acfe61e9639/src/backend/expungeservice/expunger.py#L195

As well as corresponding unit tests.

**Comment by KorynLA** [comment]
Done. Merge done by Jordan.
