### ISSUE TITLE
Redirect http requests to https

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#711]
The app will load but doesn't work properly if the user provides the url with http.

Heroku doesn't automatically redirect http requests, but we can achieve this either by adding a redirect block to the nginx config, or configuring the the react app to handle it.

**Comment by ForrestLonganecker** [comment]
Helpful links:
https://medium.com/@ethanryan/making-your-custom-name-heroku-hosted-react-app-ssl-certified-f9c7fece699c
https://www.npmjs.com/package/react-https-redirect
