### ISSUE TITLE
Update case header in results

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#719]
The case header information in the search results page needs to be updated to reflect the current app design:
http://dev.huntermarcks.net/search/

Namely, field names and values for each case should appear on separate lines. Also this header should include the County name provided for the charge, which is in the `case.location` field of the json object provided by the API.

**Comment by hmarcks** [comment]
<img width="1043" alt="Screen Shot 2020-01-14 at 8 40 36 PM" src="https://user-images.githubusercontent.com/6887982/72400231-3961c500-370e-11ea-8d1d-bb0a6af64d59.png">

**Comment by keppel2** [comment]
Closing to redo branch.

**Comment by keppel2** [comment]
I closed issue instead of pr, oops.
