### ISSUE TITLE
Provide multiple search criteria in one search request

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#722]
A single person can have records that only appear in OECI under distinct aliases, and we'd like to have all of that person's records retrievable into a combined search result.

The frontend should have the option to repeatedly add additional search criteria, e.g. with a small [add] button, that expands the search panel with a copy of the input fields on a new line.

The backend will need changes in the /api/search endpoint and/or in the crawler to:
- crawl for each of the different search criteria
- accumulate all the returned cases into a single record without duplicates
- run the expunger on the entire record

The displayed results could somehow convey which cases are tied with which search criteria, either in their case headers or by being grouped and labeled together

**Comment by wittejm** [comment]
Whoever works on the frontend portion of this will need to sync with any changes reflected in #724

**Comment by wittejm** [comment]
@hmarcks With the new middle name field added and the search params bumped out to two lines, I'm not sure what this new feature should look like. What do you think?

**Comment by hmarcks** [comment]
@wittejm I've been meaning to create a design for this, I'll have one soon.

**Comment by wittejm** [comment]
sounds good.

**Comment by hmarcks** [comment]
@wittejm what do you think of something simple like this?

![multiple-searches](https://user-images.githubusercontent.com/6887982/73131262-832f9280-3fcd-11ea-9ed0-229539304a21.png)

**Comment by wittejm** [comment]
This looks really good, though I was thinking of a slightly simpler flow for now especially since we want to get this feature into the March milestone release. What I had in mind was to optionally put in extra sets of search params when beginning the search, and still run it in one  button click. If someone searches once and wants to add results from another search, they would just have to put in all their desired params and hit the search button again.

An example of adding optional additional params for one request is the Slack send invitations UI, like here (mobile lawl)

![Screenshot_20200126-131058](https://user-images.githubusercontent.com/2104990/73142057-4ac89c80-403f-11ea-9350-fad1cfc3725c.png)

I think this approach would be the simplest new feature and require very little change in how we handle frontend state changes.

Sorry, I could have been more clear on this especially with the descriptionless related issue #724 that I posted.

I think having UI features that are more interactive for adjusting the analyzed results like this and your other feature mockup #687 would potentially be really great if more involved to build, and we'll have to see how much benefit Michael or our other forthcoming users would see in them.

**Comment by hmarcks** [comment]
Ah got it, I’ll post a design with this approach soon

**Comment by hmarcks** [comment]
@wittejm how about this? Adding individual fields is cleaner anyway, although it adds more buttons:
![multiple-searches-v2](https://user-images.githubusercontent.com/6887982/73233712-f6abde00-414c-11ea-9858-abd06966b3a1.png)

**Comment by hmarcks** [comment]
Also, do you know if Date of Birth would ever be needed? Seems very unlikely to me.

**Comment by michaelzhang43** [comment]
I would prefer a combination of the two general methods already suggested: to have one button that is always available (without running a first search) that adds the option to combine results with a subsequent search

**Comment by michaelzhang43** [comment]
It's unpredictable what kinds of errors a person's online records will have. So for Michael Zhang 5/9/1993, aka Michael Pineapple I might search all of these:
M* Zha* 5/9/1993
Michael Zhang 
Michael Pin* 5/9/1993
Michael Pineapple

**Comment by hmarcks** [comment]
@michaelzhang43 After you perform a search, I believe the fields retain their values, so you could easily modify them if you wanted to adjust on a subsequent search.

To get specific combinations, I suppose we'd need to duplicate all the fields. How's this?

![multiple-searches-v3](https://user-images.githubusercontent.com/6887982/73328714-64750a00-4220-11ea-9e21-ff2ab7da4385.png)

**Comment by michaelzhang43** [comment]
That looks perfect, Hunter

**Comment by hmarcks** [comment]
For whoever will pick this up, I added some markup for the integration work here: #789

Also, here is an updated mockup:
![multiple-searches-v3](https://user-images.githubusercontent.com/6887982/73666511-8b8c6b00-4668-11ea-91a7-71c3bf9eb3cf.png)

**Comment by wittejm** [comment]
completed with #823
