### ISSUE TITLE
Eliminate the risk of timeout error from Heroku

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#725]
Maybe replace our web platform, maybe batch-yield search results

**Comment by wittejm** [comment]
@ForrestLonganecker I just realized you are a Cloud Professional In Training (tm) so let's talk about this! I discovered a limitation of the heroku postgres addon is that creating new database-access accounts is disallowed in the free version. We're outgrowing the cheap stuff and we may need to migrate sooner rather than later.

**Comment by ForrestLonganecker** [comment]
@wittejm I am unfamiliar with what you are talking about so lets talk about this more in person! 

- Are we storing more than user log-in info in the db? 

- What are database-access accounts and why do we need multiple? 

I would be happy to look into this aided with more information when I have a chance!

**Comment by wittejm** [comment]
Excellent questions. I actually jumped the gun on worrying about the heroku postgres features so I don't actually think we need to worry about that. I'm still interested in considering if we should migrate our web host because the 30-second timeout rule issue is a hard-coded feature of Heroku.
