### ISSUE TITLE
Add the middle name search field to frontend

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#726]
And include it in the endpoint call. Endpoint code already handles it as an optional field.

**Comment by hmarcks** [comment]
The prototype now has a middle name field - the markup can be copied over from here: http://dev.huntermarcks.net/search

**Comment by wittejm** [comment]
Awesome, thanks @hmarcks

**Comment by wittejm** [comment]
This is now pending a new design update to handle the feature request #722

**Comment by hmarcks** [comment]
The design is complete for #722 and HTML can be used in that #789 pull request.

**Comment by wittejm** [comment]
Cool. @nickprender12 The middle name is added in that new PR, want to give that a look/review since you were working on the feature?

**Comment by wittejm** [comment]
Hey again @nickprender12 , I'm working on the multiple search criteria issue #722, which integrates the existing middle name field markup in #789. Since that subsumes this issue, I'll unassign you and reassign myself to not duplicate work.

**Comment by nickprender12** [comment]
Hey @wittejm , Sorry I'm just now seeing your post from 3 days ago! That all sounds great, Thanks!
