### ISSUE TITLE
"Arrested" date field on a charge should say "Charged"

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#727]
Or, "Date charged:"

A Parking Ticket currently has a "Arrested: [date]" which is comical and no good. 

Calling it just the date Charged is more strictly true to OECI.

**Comment by m-murasovs** [comment]
Hi, I'd like to do this one :)

**Comment by wittejm** [comment]
Great! I think the file that needs to be changed is this one: https://github.com/codeforpdx/recordexpungPDX/blob/master/src/frontend/src/components/Charge/index.tsx

**Comment by wittejm** [comment]
closed with #730
