### ISSUE TITLE
Most makefile targets fail if a file with the same name exists

### ISSUE THREAD

**Issue by keppel2** [codeforpdx/recordexpungPDX#737]
In project root:
```
recordexpungPDX 0 % touch dev_up
recordexpungPDX 0 % make dev_up 
make: `dev_up' is up to date.
```
`make` is one of the oldest UNIX tools, and is a bit crusty. Usually this is added to the `.PHONY` target, but there may be a way to avoid repeating the targets here.

**Comment by keppel2** [comment]
I suppose not beginner friendly, but it's something I'd like to mentor someone on who wants to learn old-school Makefiles. That's why I didn't self-assign.

**Comment by keppel2** [comment]
Most modern build systems like `ant`, `maven`, and `gradle` shouldn't have this problem by default. Not necessarily a reason to switch.

**Comment by wittejm** [comment]
Thanks for finding this potential bug. I agree it looks like a good issue for a newer contributor to handle. I think `make` is still sufficient for our needs and using  `.PHONY` looks like the way to go for resolving this issue. For the scale of our project, I don't see a need to migrate our build system in the foreseeable future.

**Comment by keppel2** [comment]
All targets could be made phony with a `*`, and the redundant .PHONY targets removed.
