### ISSUE TITLE
Connect "AddUser" component to the backend

### ISSUE THREAD

**Issue by ForrestLonganecker** [codeforpdx/recordexpungPDX#746]
This task is done when:

* Admin user is able to create a new user by submitting a new user form to the back end.
* Form validates that the new user form contains:
  * Email
  * Password
* Non-Admins are unable to create a new user.
* Error messages match required fields

**Comment by hmarcks** [comment]
![account-flow](https://user-images.githubusercontent.com/6887982/72775070-96f48680-3bd2-11ea-8a1a-ea2bc733a1d6.png)

Accessible validation technique: https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA19

**Comment by grbarker** [comment]
@ForrestLonganecker I wanted to take a go at adding form validation to the AddUser component. I was going to open a new issue for it. I wanted to clarify what the validation should do. 

You mentioned that email and password need to be confirmed to exist. I spoke with @wittejm about the validation and he wanted to include the name field and a new confirm password field in the validation.

You also mentioned that the error messages should match the required fields. Does this mean that you want each field to have its own separate alert if they are missing, or can we use one alert to inform the user that one of the required fields is missing?

**Comment by ForrestLonganecker** [comment]
Thanks for taking this on @grbarker!
Looking at the error messages here:
![image](https://user-images.githubusercontent.com/42503418/73112567-c1408f80-3ec3-11ea-9e0a-47fbee9b8bcc.png)
I think we would only need to add validation messages about password being required and the password/password confirmation needing to match. You can use the same error message format that is used elsewhere but just swap out the text.

Please reach out with any additional questions!

**Comment by grbarker** [comment]
@wittejm wanted to validate that the password is 8 characters long so I put that in as well.

The email validation function catches an empty email and gives a "Invalid Email" alert. Do we want to explicitly say that it is missing like the other fields or just keep on going with the "Invalid Email" catch all alert?

**Comment by ForrestLonganecker** [comment]
I feel `Invalid email address` should suffice for both: No email present, and incorrect format

**Comment by grbarker** [comment]
I'll leave the email validation alone then. 
Just to make 100% sure I we are on the same page, are you wanting the validation in the screenshot as well as as the validation of email and password?

**Comment by ForrestLonganecker** [comment]
Yes please!

**Comment by wittejm** [comment]
completed with #889
