### ISSUE TITLE
Connect "EditUser" component to the backend

### ISSUE THREAD

**Issue by ForrestLonganecker** [codeforpdx/recordexpungPDX#747]
This task is done when:

* Edit user form is populated with the selected user.
* Admin user is able to edit an exissting user by submitting an edit user form to the back end.
* Form validates that the edit user form contains updated content.
* Non-Admins are unable to edit user information.
* Error messages match required fields

**Comment by hmarcks** [comment]
![account-flow](https://user-images.githubusercontent.com/6887982/72775076-a4aa0c00-3bd2-11ea-84a9-93aa94a5407c.png)

Accessible validation technique: https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA19
