### ISSUE TITLE
Create a `/user` endpoint

### ISSUE THREAD

**Issue by ForrestLonganecker** [codeforpdx/recordexpungPDX#750]
This is complete when:
* a `/user` endpoint is made in the backend that returns the user information for the user requesting information this will be used to populate the `Account` page.

See discussion in #731

**Comment by wittejm** [comment]
This endpoint is already built, here: https://github.com/codeforpdx/recordexpungPDX/blob/e0ef348c439c50196d4761c711547073a11c7ec9/src/backend/expungeservice/endpoints/usersview.py#L176
