### ISSUE TITLE
Create an "exercise" task to help new folks get up to speed faster  

### ISSUE THREAD

**Issue by maxkwallace** [codeforpdx/recordexpungPDX#76]
In the apps I've worked on before, we always had an exercise task that newcomers would complete just after joining. This task was designed to make sure newcomers could "learn by doing" by making a set of minimal, full-stack changes to give them something to do while they get familiar with the codebase. 

If we had an exercise task like this it would also help with triage when lots of new people join: we could immediately give them something to work on that would teach them about the codebase and help them be more useful when working on features or refactors later on.

### This task is done when:
 - There is an exercise task that meets the above requirements. This should probably be a page in the wiki that introduces the different parts of the app code and how the work together, and that walks someone through the process of making a simple, full-stack feature change or addition.

**Comment by erikjasso** [comment]
FIWI I like this idea. If I understand the objective the task could be as simple as:

* check out this Python file and increment this variable
* checkout this JavaScript file and increment this variable
* commit and push both changes

**Comment by KentShikama** [comment]
One possibility is to link to https://open-pixel-art.com/ .

**Comment by wittejm** [comment]
We've been creating enough new and low-complexity issues lately that I'm not sure we need to outline a task like this, but it's still a really cool idea if we do put something like this together.

**Comment by ForrestLonganecker** [comment]
Would it be worthwhile to create a "contributers" page and have newcomers add their name(or nickname if anonymity is a concern), to it and the month they joined? It could be a small link in the footer that could link to a growing list of contributors, with the option of including a link to their github page or something like that.

This would have them change some frontend code and initiate a pr, review and merge.

Not sure what the backend task could be, piggy backing off of @erikjasso -> potentially incrementing a variable that represents the total number of contributors to the project thus far?
