### ISSUE TITLE
The Friendly Rule shouldn't apply if the conviction is type-ineligible

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#768]
In the reported bug, a case has a convicted DUII charge and another dismissed charge. The DUII conviction is labeled time-eligible, so the Friendly Rule  (namely: if a case has a single convicted charge, the dismissed charges on the same case become eligible when the conviction becomes eligible) gets applied and it adjusts the dismissed charges to also be time-eligible. The current logic does not pick up on the fact that the DUII never becomes actually eligible because it's type-ineligible. So the Friendly Rule shouldn't take effect.

This is related to #385. The solution to this bug will depend on the implementation for #385, so that should probably be completed first.

**Comment by KentShikama** [comment]
@aemrich Looks like you were assigned to this issue. I didn't mean to steal it but I was working on https://github.com/codeforpdx/recordexpungPDX/issues/753 and I realized I had completed most of this issue as a side-effect (and thus the PR https://github.com/codeforpdx/recordexpungPDX/pull/771).

**Comment by aemrich** [comment]
@KentShikama  Ah no worries, thanks for the heads up
