### ISSUE TITLE
Fix monetary formatting for search page to match summary

### ISSUE THREAD

**Issue by keppel2** [codeforpdx/recordexpungPDX#780]
On the search page, the case component displays the balance in plain numbers (0, for example). It needs to match what is on the static design as well as the format in the summary ($1.23).

**Comment by wittejm** [comment]
I've also noticed that values over $1000 lack commas, so that can be added to all instances of balance values. This is worth abstracting to a function at this point for the different occurrences.

**Comment by wittejm** [comment]
@nickbeaird how is this issue going? Are you still active on it?

**Comment by nickbeaird** [comment]
I was assigned to this, as it was pretty small. Please anyone feel free to take this. I will pick it up later if no one else does.
