### ISSUE TITLE
Show expanded charge type documentation in search results

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#797]
Edit: Renaming and updating this issue for the next phase, of adding the frontend feature.

See below for mockups. 

To handle charge types that are essentially split between two classes (`RomeoAndJulietIneligibleSexCrime` and `DUII`), we'll need to address then in a way that both the Manual's charge types page and the entries included in the search results page both look "good" to the user, while the manual page is ideally still easily generated from the text written in the backend.  

---
older, completed phase of writing the expanded documentation.

This will need to be a work in progress as we figure out exactly how to handle detailed explanatory documentation. We want to:
- keep it tightly synced with the source code, since the documentation on our set of Charge Types should purely give explanation for why those charge types work the way they do.
- expose documentation to the user programmatically, and have no redundant doc files for the same content. On search results, there could be e.g. a mouse-over tooltip, or a "show more" button, on the charge type field. We could also have pages in the website's user manual that compile the complete rules of all charge types into one place.  

For now, we can achieve this by writing the explanation for a charge type as a string field on the charge type class object. The python doc module Phoenix relies on comment strings attached to classes and methods (`obj.__doc__`) but we should use a named string field because `__doc__` strings are meant to be developer-facing, not user-facing.

The doc for each charge type can include the following: 
- Reference the expungement statute's subsections that provide eligibility reasons: for its type eligibility, for both conviction and dismissal when there is a difference, and time eligibility if there are special rules like with the Class B felony
- Whenever skip_analysis is true, say why.
- Why do the particular classification conditions apply within the [`ChargeClassifier`](https://github.com/codeforpdx/recordexpungPDX/blob/master/src/backend/expungeservice/models/helpers/charge_classifier.py) for that charge type, especially when a charge seems like it could qualify as multiple charge types? A charge always gets exactly one type, and the order of rules getting applied is very specific. It might be useful to provide any extra context on why a charge type can be applied with higher precedence than other types (e.g., Subsection12 names some Felony statutes, so the classifier needs to check Subsection12 with higher priority than the Felony charge types).
- Include anything else generally interesting about charge type that wasn’t already covered.
- There’s some “special knowledge” that Michael has only imparted in Slack either to the general channel, or to some folks like Jordan or Kent. We’ll need to transcribe anything that applies.

The string field on each Charge type can be called `expungement_rules`

**Comment by wittejm** [comment]
We can work on this incrementally type by type, so y'all can feel free to spam smaller PRs for this issue.

**Comment by hmarcks** [comment]
Love this. Here's a proposal for revealing it on the frontend. Please take a look  @michaelzhang43 and all:

![documentation](https://user-images.githubusercontent.com/6887982/74123714-3afb9d00-4b95-11ea-9356-f2640de3f381.png)

**Comment by wittejm** [comment]
This looks great!

**Comment by michaelzhang43** [comment]
Agree with Jordan. This looks great

One thing I’m concerned about is overexposing information and potentially confusing the user. For example, for a dismissed B Felony, I think our documentation should just be that any dismissed case is type eligible for expungement.

**Comment by wittejm** [comment]
That concern makes sense. 

We already show the type eligibility reason which is usually very short. For dismissals we currently usually say "Eligible under 137.225(1)(b))" but there is an open issue #812 to clarify with  "Dismissals are eligible under 137.225(1)(b))" 

How about, to avoid overwhelming the user the link for more documentation should be a little "less welcoming" -- so the user doesn't click it thinking that they actually need that extra information. Maybe it's called "more legal details", then no one will click on it unless they really want to.

Maybe take the link off entirely, and it's only in the docs section of the website?

**Comment by michaelzhang43** [comment]
How about one of the following:
1. Citation
2. Explanation
3. Legal Citation
4. Legal Explanation
?

**Comment by wittejm** [comment]
Todo: Identify and complete the set of charge types that don't have a rules string yet.

**Comment by hmarcks** [comment]
Updated mockup to account for multiple types when a charge needs clarification:

![documentation2](https://user-images.githubusercontent.com/6887982/81254029-9f40c800-8fef-11ea-96e3-4c2ce319def5.png)

**Comment by wittejm** [comment]
Showing charge rules in the results page was completed with #1324. I'll make a new issue for part 2, the standalone page of rules for all charge types.
