### ISSUE TITLE
Epic: Search if a person has eligible expungeable records

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#8]
As a user
I would like to enter in a search name and/or date of birth.
so that I can see a list of eligible and non-eligible expungeable records.

Parent of #6, Parent of #7, Parent of #9, Parent of #10

**Comment by maxkwallace** [comment]
@cameron2018 are you still working on this, or should I unassign it and open it up for someone else to work on?

**Comment by NickSchimek** [comment]
@maxkwallace This will be complete when issue #9 is complete.
