### ISSUE TITLE
Delivery of marijuana to a minor is eligible 

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#804]
The bug report has the following as a type-eligible charge:

4758604A-Delivery of Marijuana to Minor

The eligibility is given under a different statute from the usual expungement statute:

https://www.oregonlaws.org/ors/137.226

It's probably best to create a new charge type for this, and it's possible that the charge type could include other marijuana charges, depending on the details in 137.226

**Comment by wittejm** [comment]
Request for info from @michaelzhang43 : does 137.226 have other rules that we need to implement?

**Comment by michaelzhang43** [comment]
137.226 makes all common charges related to marijuana

**Comment by wittejm** [comment]
what does that mean?

**Comment by michaelzhang43** [comment]
137.226 makes all common charges related to marijuana eligible - this would be 
Manufacturing
Delivery
Possession 
of marijuana (whether or not it's w/in 1000 ft of a school or to a minor)
These are usually classified as Class A Felonies, and are sometimes listed as 
Manu/Del CS 1 or Manufacturing Marijuana or Manufacturing of a Controlled Substance in Schedule 1

**Comment by KentShikama** [comment]
@wittejm Note I've changed the title of the post. Feel free to switch back if it should be "to a minor".

**Comment by wittejm** [comment]
It's "to". I expect "by" would just make it a juvenile charge.
