### ISSUE TITLE
ManufactureDelivery is a new charge type

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#809]
Manufacture and delivery of a controlled substance is either a Class A or Class B felony, which determines whether it is eligible. But we want a unique charge type because Class B felony is  "Needs more Analysis", and we can be definitive in the case of Manu/Del.

tied to #808 

### This task is done when:
 - Classify a ManufactureDelivery charge with the statute 475.9921b -- verify this or possible other identification method with Michael.
 - Dismissals are always type eligible under 137.225(1)(b).
 - Type Eligibility of a conviction is determined by the Level: B Felony is eligible and A Felony is ineligible. "Felony Unclassified" is a potential OECI error and "Needs more analysis". 
 - The class B felony case still follows the B felony time eligibility rule.
 - If the charge is "felony unclassified" and needs more analysis, it's still subject to the B-felony rule. 
 - Unit tests for each of these different pieces of the enhancement.

**Comment by michaelzhang43** [comment]
DRUG CRIMES
Manufacturing/Delivery/Possession
of a Controlled Substance in Schedules I or II

I. Manufacturing, Delivery, Manufacturing/Delivery and Manu/Del should be treated the same
For these, there are these possibilities:
1. The underlying substance is for Heroin, Cocaine, or Crack, in which case it usually is classified as a B Felony and follows B Felony analysis (20 years, no arrests). It is sometimes classified as a "Felony Unclassified" - in these cases, we should 
2. The underlying substance is for Marijuana, in which case it is usually classified as an A Felony BUT is type-eligible and follows time eligibility of a type eligible misdemeanor. It is sometimes classified as a "Felony Unclassified"
3. The statute numbers for this is 475.9921b

**Takeaway**
1. If the class level is B Felony, then it follows B Felony rules
2. If the class level is unclassified or A Felony, then it needs more analysis (asking the user about whether the substance was marijuana, and I'll include this in the manual)
