### ISSUE TITLE
OECI login component

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#82]
Create view for user to log in to OECI (Oregon eCourt Case Information) so that they can search records.

HTML template to transfer: https://github.com/hmarcks/expunge-pdx-frontend/blob/master/index.html
Live template: http://dev.huntermarcks.net
Design system: http://dev.huntermarcks.net/design-system

User flow:
![OECI login flow](https://user-images.githubusercontent.com/6887982/55119747-53afb100-50b0-11e9-865b-e4b947f250ee.png)

**Comment by maxkwallace** [comment]
Addressed in https://github.com/codeforpdx/recordexpungPDX/pull/285 (thanks @cjbreaux !)

The loading state for the login button is listed as an outstanding item in https://github.com/codeforpdx/recordexpungPDX/issues/75 so I think it's safe to close this issue.
