### ISSUE TITLE
If the only conviction on a case needs more analysis, the arrests need more analysis

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#820]
The friendly rule improves the arrest eligibility only if the conviction is eligible. If the conviction is needs more analysis , it may or may not apply the friendly rule.

Possibly solvable by attaching "arractors" of the friendly rule to to the charge, and then evaluating them only as part of Charge Eligibility. difficult to say what the best solution here is.

**Comment by KentShikama** [comment]
I'm going to rephrase the issue.

If the only conviction on a case has a type eligibility of needs more analysis, the arrests will be time eligible on date X if the conviction ends up being type eligible. Otherwise, the arrests will be time eligible on a later date Y.

**Comment by KentShikama** [comment]
From a UI perspective, there is no need to "link" to the conviction charge as it will be within the same case, and it would be hard to do so given how charges don't really have IDs. We will display two dates for all arrests that have a conviction in the same case with a type eligibility of needs more analysis (where the friendly rule may apply): date_will_be_eligible (assuming conviction was type eligible) and date_eligible_without_friendly_rule (assuming conviction wasn't type eligible).

**Comment by KentShikama** [comment]
Re-opening with https://github.com/codeforpdx/recordexpungPDX/pull/930
