### ISSUE TITLE
The friendly rule needs one more test case

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#821]
The bugfix #773 is probably complete. But we need a test case for a record that contains one non-violation conviction, one violation conviction, and one arrest. The date of eligibility of the violation is pushed out 10 years from the date of the conviction, but the date of eligibility of the arrest matches that of the conviction.

### This task is done when:
 -
 -

**Comment by KentShikama** [comment]
This tests already exists: https://github.com/codeforpdx/recordexpungPDX/blob/master/src/backend/tests/test_time_analyzer.py#L62
