### ISSUE TITLE
Misdemeanor documentation

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#832]
Drop into source code for misdemeanor conviction:
"
Convictions for misdemeanors are generally eligible under ORS 137.225(5)(b). 
Exceptions include convictions related to sex, child and elder abuse, and driving, including DUII
"

Drop into source code for misdemeanor arrest:
"
Dismissals for misdemeanors are generally eligible under ORS 137.225(1)(b). Exceptions include cases dismissed due to successful completion of DUII diversion.
"

### This task is done when:
 -
 -

**Comment by keppel2** [comment]
@wittejm How should I put in these separate strings?

**Comment by wittejm** [comment]
Let's just concat them as single string for the charge type, same as the others that you just PR'd.

**Comment by wittejm** [comment]
Same thing for #836

**Comment by keppel2** [comment]
Okay, I'll do the same for the other two.
