### ISSUE TITLE
Non-Traffic Violations

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#833]
Violations are eligible under ORS 137.225(5)(d). 
Examples include Fare Violation, Minor in Possession of Alcohol, Failure to Send or Maintain a Child in School. 
However, traffic violations are ineligible under (7)(a). 
Moreover, certain matters are not eligible: Contempt of Court, Extradition

### This task is done when:
 -
 -

**Comment by wittejm** [comment]
And then automatically update the `charge_types.md` doc file with the util script:

in the backend/src/ directory: 
`pipenv run python generate_charge_types_doc.py`
