### ISSUE TITLE
Parking Ticket

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#834]
Drop in source code
"
Parking Tickets are not eligible. ORS 137.225(7)(a) specifically prohibits expungement of traffic offenses. No other section specifically allows for parking offenses to be eligible. 
"
 

### This task is done when:
 -
 -

**Comment by wittejm** [comment]
And then automatically update the `charge_types.md` doc file with the util script:

in the backend/src/ directory: 
`pipenv run python generate_charge_types_doc.py`
