### ISSUE TITLE
Add Header Component that's visible to logged-in users

### ISSUE THREAD

**Issue by maxkwallace** [codeforpdx/recordexpungPDX#85]
See the mockups at http://dev.huntermarcks.net/search/

This task is for implementing the header showing the Record Expunge logo at the top left and the Search, Stats, Admin, Account, and Log Out links on the right. Like the mockup, there should be a white header with a small border / drop shadow on the bottom (see the existing HTML in the mockups).

You will probably want to add a Component in React for the header that is shown to any users that are logged in. If there isn't yet a "correct" way in React to determine whether the user is logged in, then create a dummy variable (set it to the value you need) in the Component where you'd expect to get the Boolean value for whether the user is logged in or not. 

There doesn't have to be a way to set that boolean to the value needed to show the Header Component-- it's okay if your work is only visible to people who've manually edited the code to change the value of that variable. We'll replace it later and integrate it with the login logic.

### This task is done when...
- The view described above is implemented
- The implemented view matches the style in Hunter's mockups http://dev.huntermarcks.net/search/

**Comment by hmarcks** [comment]
Note that we'll only want the "Stats" and "Admin" items to show for users who have the role of admin. Not sure if that should be included in this task but something to keep in mind.

**Comment by maxkwallace** [comment]
@hmarcks thanks for adding that detail! 

For whoever implements this, my recommendation would be to wait until we have live data coming from the backend before writing code to only show the "Stats" and "Admin" items for admin users. This should just be an "if" in the code that renders the template. 

(Independent of that, if we consider the stats info sensitive and is not something we want to expose to adversarial users, the API endpoints that serve that data will need to be configured to only send it to "admin" users. But that authorization logic can't be implemented on the frontend.)

**Comment by maxkwallace** [comment]
Hunter just pointed out to me that this was done in #104. Thanks! Closing this issue.
