### ISSUE TITLE
Add "Record Search" box to search page

### ISSUE THREAD

**Issue by maxkwallace** [codeforpdx/recordexpungPDX#86]
See the upper "Record Search" card on http://dev.huntermarcks.net/search/ 

This task is only to implement a Component that corresponds to the "Record Search" box at the top of the page under the header. The Component should contain the First, Last, and DOB fields as well as the search button. You can add HTML validation using the `<form>` tag. 

Do not implement the code to actually process the search request and send it to the backend when the user clicks the search button. (That will be in a separate task.)

If the /search URL doesn't exist in React you don't need to create it. We likely don't need actual URLs for the app, but we can add them later if needed.  

### This task is done when...
 - A Component exists in React that matches the "Record Search" box visible on http://dev.huntermarcks.net/search/

**Comment by hmarcks** [comment]
Here's a good resource for implementing accessible required fields. I'll update the HTML to help support this.

https://developer.paciellogroup.com/blog/2019/02/required-attribute-requirements

**Comment by NickSchimek** [comment]
@hmarcks Is this completed?

**Comment by hmarcks** [comment]
@NickSchimek yeah it's done, I'll close it
