### ISSUE TITLE
Automate registering of endpoint routes in expungeservice/app.py

### ISSUE THREAD

**Issue by ash-tamraz** [codeforpdx/recordexpungPDX#88]
Currently, when adding endpoints to the backend, routes for the endpoints (found in `src/backend/expungeservice/endpoints/`) must be manually added to the `create_app` method of `src/backend/expungeservice/app.py`, e.g.:

```
    # Register endpoint routes here:
    hello.register(app)
    auth.register(app)
```

The goal would be to alter `src/backend/expungeservice/app.py` to search the endpoint directory and register the endpoint routes itself, so that regardless of removals or additions to the endpoints, the backend will find them and register them.

### This task is done when...
 - Routes for new endpoints for the backend don't need to be manually added to `src/backend/expungeservice/app.py`

**Comment by ash-tamraz** [comment]
@erikjasso Does this cover all of the issue that you had in mind when we spoke last night about this?

**Comment by erikjasso** [comment]
Yes, that's what I was thinking. Good write-up.
