### ISSUE TITLE
Contempt of Court

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#891]
Is a civil offense

Is most reliable to identify by name.lower() contains "contempt of court".

### This task is done when:
 - new charge type file
 - added to charge_classifier
 - unit tests for convicted/dismissed/missing/unrec dispositions

**Comment by KentShikama** [comment]
Why wouldn't this caught by nature of the statute being 33 (which is between 1 ~ 100)? See https://github.com/codeforpdx/recordexpungPDX/blob/master/src/backend/expungeservice/models/helpers/charge_classifier.py#L109

**Comment by wittejm** [comment]
Michael requested this I think because sometimes you can have a Contempt charge without a statute number.

**Comment by wittejm** [comment]
completed with #928
