### ISSUE TITLE
Check marijuana eligibility under 137.226: person under age 21. 

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#894]
137.226 adds a narrow-case eligibility criterion for a young single-offender of a marijuana charge:

A person with:

- A single Marijuana Conviction - one of the following is in the name: "Marij", or "MJ", 
- If the name contains "Manufactur" , "Delivery", or "Manu/Del" , it must not contain "2" 
- No other convictions besides traffic violations
- Was under 21 at the time of conviction. (compute from DOB and Date of Conviction)
- convicted charge is one of: manu, possession, delivery 

Is Eligible one year after the date of conviction.

This can initially be a note in the manual. Not a 3/11 Milestone issue.

Be careful with this one. Make sure it doesn't over-apply

**Comment by KentShikama** [comment]
@michaelzhang43 Just want to double check that under age 21 is a strict inequality (aka until 20 years and 364 days).
