### ISSUE TITLE
Automate expunge decision

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#9]
Build a tool that will analyze each charge and decide if it can be expunged

**Comment by maxkwallace** [comment]
@cameron2018 @a-ilango are either of you working on this, or should we unassign it and open it up to someone else to work on?

**Comment by a-ilango** [comment]
I believe @NickSchimek is looking into this.

**Comment by NickSchimek** [comment]
Yes, this is mostly complete. Just need to confirm a few things before finishing it up.

**Comment by NickSchimek** [comment]
@maxkwallace A PR is coming soon for this
