### ISSUE TITLE
Create "Users" Component for /admin

### ISSUE THREAD

**Issue by maxkwallace** [codeforpdx/recordexpungPDX#91]
This task is to create the Component that's comprised of the second-from-the-top card on the page with the title "Users", including transferring all the HTML from http://dev.huntermarcks.net/admin.

Wireframes for more context around the whole users flow:
![user-account-wireframe](https://user-images.githubusercontent.com/6887982/69019529-a78c4480-0976-11ea-853d-4c69937e0deb.png)

Accessible validation technique: https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA19

We don't necessarily need to implement routes and/or URLs for the React app (it can be a "single page app", at least to start) but if there are routes, or you want to implement one, this Component should appear on the /admin route. I used "/admin" in the title of the issue only because it's a straightforward way to reference the mockup.

The actual functionality of interacting with the backend (responding to clicks on buttons) should be handled in a separate issue (create it if you want to work on it).

The Component should support displaying a variable-length list of Users, again matching the mockup, and you should use hardcoded data in Javascript to test this functionality if it's not yet possible to get live data from the backend. 

### This task is done when...
 - The Component described above exists and visually matches the mockup, and the user can see it when they navigate to the page.
 
If you create a PR to address this issue you're welcome to send it to me @maxkwallace for review.

**Comment by maxkwallace** [comment]
@ForrestLonganecker okay! Do you have existing work in progress on this? If you're not currently working on it, would it be feasible to open this up for someone else to work on? Again, can discuss tonight, those are the main things I'd want to know re: making sure everyone has something they're excited to work on.

**Comment by ForrestLonganecker** [comment]
I had started but didn't get far, of someone else wants to take over that's
okay with me. You can open it back up!

**Comment by ForrestLonganecker** [comment]
@maxkwallace I had started but didn't get far, of someone else wants to take over that's
okay with me. You can open it back up!

**Comment by ForrestLonganecker** [comment]
@maxkwallace to follow up I am now actively working on this ticket!

**Comment by ForrestLonganecker** [comment]
Just to update the state of this issue, currently the `<UserList/>` component renders data that it retrieves from the store.

Some of what still needs to be done:
- create a get/users request that will return a list of users and their information if the current user is an admin and place that list in the store.
- render something/redirect users that do not have admin privileges.

**Comment by ForrestLonganecker** [comment]
As of #583 the user component is now fulfilling these requirements.
