### ISSUE TITLE
Add Staging Environment and Deploy to Staging Steps

### ISSUE THREAD

**Issue by loganballard** [codeforpdx/recordexpungPDX#936]
Currently our deployment process involves a lot of manual steps, and production is run out of a home directory.  There is also not a staging environment.

### This task is done when:
 - Production is run out of a shared directory
 - Staging environment exists and mimics production (including database)
 - Deployment steps for production and staging are easy to understand and can be run by a dev with access to the production server
 - Staging environment can be taken up and down on demand

**Comment by kenichi** [comment]
see https://github.com/codeforpdx/recordexpungPDX/compare/master...kenichi:devops

goals of this branch:
* make initial developer setup and running as simple as possible (`make up initdb`)
* make staging, production, etc deploys as simple as possible (`cd src/ops; make staging`)

**Comment by kenichi** [comment]
>  - Production is run out of a shared directory

self-contained single-image deploys allow for horizontal scaling, easy rollback, platform agnostic-ism

> - Staging environment exists and mimics production (including database)

✅ though they have separate databases, `record_sponge_db` (prod) and `record_sponge_db_staging` (staging)

> - Deployment steps for production and staging are easy to understand and can be run by a dev with access to the production server

make targets in src/ops/Makefile (`staging` or `prod`), docs in src/ops/README.md and doc/, and comments in Makefile.

> - Staging environment can be taken up and down on demand

at this point, the method of doing this would be to start or stop the `staging` docker container on the recordsponge.com host.

**Comment by wittejm** [comment]
sweet. issue sounds completed to me.
