### ISSUE TITLE
Run frontend tests in automation

### ISSUE THREAD

**Issue by keppel2** [codeforpdx/recordexpungPDX#939]
We have the framework for frontend tests written in the Jest framework. There are two tests right now that are passing. These can be run in the continuous integration builds.

**Comment by kenichi** [comment]
see:
* https://github.com/kenichi/recordexpungPDX/runs/565443886?check_suite_focus=true
* https://github.com/codeforpdx/recordexpungPDX/compare/master...kenichi:devops

**Comment by wittejm** [comment]
completed
