### ISSUE TITLE
Feature: User follow-up questions

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#972]
After user runs the record search, any charges requiring disambiguation show a radio-button form to provide further information. 

(more detailed description for feature can go here)

**Comment by wittejm** [comment]
Mock-up from @hmarcks : 

![user-submitted-data](https://user-images.githubusercontent.com/2104990/77858011-c1a42200-71b5-11ea-8796-86df021b834d.png)

**Comment by wittejm** [comment]
In answer to your in-image comment, the entire analysis does need to run again because these ambiguities might impact time eligibility of other charges. With that in mind, I think the user should be expected to answer all the follow-up questions before they can re-run the analysis. It will take less time because there's no fetching from OECI this time. 

But, should all the answers be required? What if the user doesn't know yet what one of the answers was, so they want to leave that ambiguity untouched, but re-run with the answers they have?

And between these two options, should the submit button still go in-line or be at the bottom?

**Comment by wittejm** [comment]
In fact, the running time for analysis would typically be pretty short unless the the record is really long. It also varies depending on the number of ambiguities in the record.

 I'd guess the running time can be long enough that it shouldn't be forced to re-run after each answer, but short enough that it wouldn't be terrible if the user could re-run it after submitting only one or some answers, if they wanted to.

**Comment by hmarcks** [comment]
Thanks for the feedback @wittejm 

**1) If the user doesn’t know the answer**

Do you think we'd want to encourage an answer? Since the analysis won’t be accurate without an answer, at least they could see a potential scenario. And it's not locked in with the ability to edit.

So that’s an argument for keeping a single Submit button, but not actually requiring all. Just an idea, not saying it’s better than a button for each.

**2) Rerun after each submit?**

To ensure the user doesn’t have to wait for analysis between answering each question, I see a couple options:

a) Could we re-run after each submit, but keep the UI visible so they can locate any other outstanding questions?

b) Remove individual Submit buttons and provide a single button in the banner or in a sticky header/footer.

**Comment by wittejm** [comment]
> Do you think we'd want to encourage an answer?

Good point, making a good reason to not have an "I don't know" option.

> (although would multiple questions be very common?)

I've seen several longer records that have multiple ambiguities. A pattern seems to be that if a person has one instance on their record, they actually have several, with common examples being multiple DUIIs or multiple Manufacture/Delivery crimes. Or if it's an older record we're more likely to see weird or unfamiliar data because OECI is more messy. Definitely common enough that waiting to run the analysis after answering more than one question is useful.

> b) Remove individual Submit buttons and provide a single button in the banner or in a sticky header/footer.

I think I like this best. In keeping with encouraging a user to answer all the questions, they would need to scroll past all of the in-line questions and make an intentional choice to skip any. 

I think that retaining the state of answered questions after submitting each time sounds nice, and quite feasible (sending all the attached answers along to the backend, and receiving them again intact to reconstitute the display). 

@michaelzhang43 @KentShikama what do you think?

**Comment by hmarcks** [comment]
Updated mockups:
![user-submitted-data-v2](https://user-images.githubusercontent.com/6887982/77869754-45392f80-7205-11ea-8e0b-063c44cc8fad.png)

**Comment by wittejm** [comment]
This looks really good! 

I agree about the sticky banner not being necessary in this version, and we can see what it looks like to just have the banner with the update buttons in the top and bottom. It might be worth seeing how the sticky version feels in action later, but we can start with the simpler version with the stationary banners.

What should the bottom banner look like? Should it just be the same thing, replicated? 

And another thought: what if in that top/bottom banner, instead of hiding the Case ID when its questions have been answered, it instead gets a check mark next to it? If we did that, then each should probably appear in a separate line for readability. I'm thinking of this because the user may still want to easily locate those cases after updating them the first time.

**Comment by michaelzhang43** [comment]
Thank you for all the mock-ups, Hunter. They look fantastic.

I like the single submit button at the top (I don't think we also need to have one at the bottom). I also like the suggestion of having a check mark next to answered questions.

**Comment by hmarcks** [comment]
Thanks! One additional thing I added was updated banner content once all cases have been resolved. Here's an updated mockup:

![user-submitted-dat-v3](https://user-images.githubusercontent.com/6887982/78199867-7e1a1400-7452-11ea-8092-e06d3faaa5b7.png)

**Comment by wittejm** [comment]
all looks good to me!

**Comment by hmarcks** [comment]
Here is some HTML. I wouldn't mind looking it over after it's implemented because I think I'll have to make a couple adjustments that would have been too confusing to make here, thanks!

[user-entry.html.zip](https://github.com/codeforpdx/recordexpungPDX/files/4432805/user-entry.html.zip)

**Comment by wittejm** [comment]
completed.
