### ISSUE TITLE
Traffic Offense Documentation

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#977]
Add to documentation for Chargetype TrafficOffense:
"
A conviction for a State or municipal traffic offense is not eligible for expungement. Common convictions under this category include Driving While Suspended/Revoked, Possession of a Stolen Vehicle, Driving Under the Influence of Intoxicants, and Failure to Perform Duties of a Driver. 
"

### This task is done when:
 -
 -

**Comment by wittejm** [comment]
Also this is renaming TrafficNonViolation to TrafficOffense
