### ISSUE TITLE
Add how to start and run the docker containers for various components to Readme

### ISSUE THREAD

**Issue by a-ilango** [codeforpdx/recordexpungPDX#98]
### This task is done when:
 - Readme is updated with steps to run the containers for various components in the project

**Comment by wittejm** [comment]
Merged.

**Comment by wittejm** [comment]
Well I realized there was another doc for this already in the repo at doc/docker_mac.md. So I'm removing from the main README and merging in some of my verbiage there.

**Comment by wittejm** [comment]
The only section missing from this doc is the installation instructions for Windows, which I am not familiar with, so I'm unassigning myself from this task.

**Comment by a-ilango** [comment]
@wittejm Thanks for adding the documentation! I'm closing this issue since we instructions for Linux and Mac OS should be sufficient for most people. If needed, a new issue can be created to add instructions for Windows.
