### ISSUE TITLE
Create class for sanitizing endpoint input

### ISSUE THREAD

**Issue by ash-tamraz** [codeforpdx/recordexpungPDX#99]
Create a custom class based on [MethodView](http://flask.pocoo.org/docs/1.0/api/?highlight=methodview#flask.views.MethodView) which checks headers, sanitizes input, other information that is passed to our Flask endpoints.

Some of the endpoints perform the same checks for empty passed parameters: [here in `/api/v0.1/users`](https://github.com/CodeForPortland/recordexpungPDX/blob/master/src/backend/expungeservice/endpoints/users.py#L12-L13), [here in `/api/v0.1/auth_token`](https://github.com/CodeForPortland/recordexpungPDX/blob/master/src/backend/expungeservice/endpoints/auth.py#L62-L63), [here in `/api/v0.1/search`](https://github.com/ash-tamraz/recordexpungPDX/blob/issue48-search-endpoint/src/backend/expungeservice/endpoints/search.py#L30-L32). The goal would be to create a class, using `MethodView` as a base class, that would perform these and other sanitizing functions that are common to all the endpoints.

@erikjasso Thoughts/anything to add? (Pinging you because you suggested this)

#### This task is done when:
 - A class is created which uses `MethodView` as a base class and which handles sanitizing and checking methods that are used by multiple endpoints.

**Comment by ash-tamraz** [comment]
(@wittejm Feel free to remove yourself from this if you change your mind about working on it)

**Comment by wittejm** [comment]
@ash-tamraz Yea, actually I'll unassign because for now I'm working on building the docker volume to hold the static web content. Which might take a while :)
